### ISSUE TITLE
[keyword] 3장 스프링 IoC와 DI 소개 (1) 키워드 정리

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#11]
## 주제
[3장] 스프링 IoC와 DI 소개 (1) 를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요

## 연관 챕터
#10

**Comment by emiling** [comment]
### IoC와 DI

**목적**

컴포넌트의 의존성을 제공하고 이러한 의존성을 라이프사이클 전반에 걸쳐 관리하는 것보다 간편한 메커니즘 제공

**IoC 종류**
- DI (의존성 주입) : IoC 컨테이너가 컨테이너에 의존성 주입
  - 생성자(constructor) 주입
  - 수정자(setter) 주입
  - 필드 주입
- 의존성 룩업 : 컴포넌트 스스로 의존성 참조를 가져옴
  - 의존성 풀 (dependency pull)
    - [JNDI 간단 설명](https://hamait.tistory.com/331)
  - 문맥에 따른 의존성 룩업(Context Dependency Lookup, CDL)

### Bean과 Factory
- Bean : 컨테이너가 관리하는 모든 컴포넌트

```java
public class XmlConfigWithBeanFactory {
    public static void main(String... args) {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        XmlBeanDefinitionReader rdr = new XmlBeanDefinitionReader(factory);
        rdr.loadBeanDefinitions(new ClassPathResource("spring/xml-bean-factory-config.xml"));
        Oracle oracle = (Oracle) factory.getBean("oracle");
        System.out.println(oracle.defineMeaningOfLife());
    }
}
```

```java
public class DeclareSpringComponents {
    public static void main(String... args) {
        GenericXmlApplicationContext ctx = new GenericXmlApplicationContext();
        ctx.load("classpath:spring/app-context-xml.xml");
        ctx.refresh();
        MessageRenderer messageRenderer = ctx.getBean("renderer", MessageRenderer.class);
        messageRenderer.render();
        ctx.close();
    }
}
```

두 코드를 보고 ApplicationContext와 BeanFactory, BeanDefinitionReader, BeanDefinition의 
관계와 차이점을 설명할 수 있으면 좋을 듯 합니다.

**Comment by wooyounggggg** [comment]
### IoC와 DI
#### 개요
스프링은 객체지향적인 프로그램 설계를 위한 철학으로써 3가지를 제시하고 있습니다(IoC/DI, AOP, PSA)  
    
<p align="center">
<img src="https://github.com/caffeine-library/pro-spring-5/blob/main/references/images/spring%20triangle.png?raw=true" width="300px" height="280px"/>
</p>

또한, 이미 책의 많은 부분에서 IoC와 DI에 대해 언급했지만 구체적으로 이것이 어떠한 개념인지에 대해서까지 설명하고 있지는
않은 듯합니다.

개인적인 의견으로는 이 부분을 이해하는 것이 스프링의 전반적인 이해에 도움을 많이 준다고 생각해서 아래와 같은 질문들에

대해 같이 고민해보면 좋을 것이라 생각합니다.

- IoC(Inversion of Control)란?
- 프레임워크와 라이브러리의 차이는
- IoC와 DI의 관계
- IoC의 장점

**Comment by emiling** [comment]
### 요약

- XML + <bean> 구성
- XML + <context:component-scan> + 스테레오타입 어노테이션 구성
- @Configuration + @ComponentScan + 스테레오타입 어노테이션 구성
- @Configuration + @Bean (자바 구성)
- mixed(@Configuration과 @ImportResource 혼용하여 XML 설정도 함께 사용)

**Comment by wooyounggggg** [comment]
제가 발행한 IoC와 DI 키워드는 #21로 이전하였습니다~

**Comment by JasonYoo1995** [comment]
# 3.2.1~3.2.5
### 제어 역전
- Inversion of Control = IoC = DL + DI
### 의존성 룩업(DL)
1. 의존성 풀
2. CDL
- 주로 JNDL, JEE, EJB에서 사용
### 의존성 주입(DI)
1. 생성자 주입
2. 수정자 주입
- 주로 스프링에서 사용

> 의존성 룩업보다 의존성 주입이 더 유연하다

# 3.2.6
### 구성 인자
- 수동적 (단순한 값. 정보로서의 역할)
- 원시 타입 or 래퍼 타입 or 문자열 or 이들의 컬랙션
### 컴포넌트
- 능동적 (자신만의 작업을 수행)
- 객체 타입

# 3.3
* **의존 객체** : 협력 객체를 의존하는 객체
* **협력 객체** : 의존 객체에 의해 의존 받는 객체
* **의존성 룩업** : 의존 객체가 컨테이너로부터 협력 객체를 받아오는 것
* **의존성 주입** : 컨테이너가 협력 객체를 의존 객체에 넘겨주는 것
* **IoC의 핵심 원리** : 객체의 생성 및 소멸(=라이프사이클)과 객체 간의 의존 관계를 컨테이너가 자동으로 관리
* [참고](https://soft91.tistory.com/62)

# 3.5.3.1
* 예제 3-24에서 `@ComponentScan`의 역할
* [참고](https://velog.io/@hyun-jii/%EC%8A%A4%ED%94%84%EB%A7%81-component-scan-%EA%B0%9C%EB%85%90-%EB%B0%8F-%EB%8F%99%EC%9E%91-%EA%B3%BC%EC%A0%95)
