### ISSUE TITLE
[question] Spring은 어떠한 원리로 ComponentScan을 통해 의존성을 주입하나요?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#12]
## 질문
Spring은 어떠한 원리로 ComponentScan을 통해 의존성을 주입하나요?

## 상세 내용
스프링의 `@ComponentScan` annotation이나 xml 설정 파일의 `<context:component-scan>` 태그와 함께 base package를 설정해주면, 해당 패키지 하위에 위치한 모든 클래스에 대해 `@Component(또는 @Component를 감싸는)` annotation이 선언되어 있는 클래스를 빈으로 등록하고 이후 빈으로 등록된 클래스의 attribute중 빈으로 등록된 의존성을 주입합니다.

구체적으로 어떤 방식으로 스프링이 동작해서, 이러한 로직을 수행하는지 궁금해 질문 남깁니다! 😃 

## 사례 코드
```java

/* SpringConfiguration.java - 설정 파일 */
@Configuration
@ComponentScan(basePackages = {"..."})
public class SpringConfiguration {
    ...
}

/* HelolWorldMessageProvider.java */
@Component("provider") // @Component annotation을 통해 Bean 등록
public class HelloWorldMessageProvider implements MessageProvider{
    ...
}

/* StandardOutMessageRenderer.java */
@Service("renderer") // @Service annotation을 통해 Bean 등록
public class StandardOutMessageRenderer implements MessageRenderer {

    private MessageProvider messageProvider; // 여기에 어떠한 원리로 HelloWorldMessageProvider가 주입되나요?

    ...
}
```

## 연관 챕터
#10 

## 참고
조사해보기론, 아래의 `AbstractionApplicationContext`의 refresh method를 연구해보면 해당 로직을 수행하는 부분이 있는 것 같습니다. 해당 코드를 분석해보고 답을 찾게되면 댓글로 남기도록 하겠습니다.
[Spring AbstractApplicationContext - refresh method docs](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/support/AbstractApplicationContext.html#refresh--)

**Comment by emiling** [comment]
코드 분석의 경우 [해당 블로그](https://thswave.github.io/spring/2015/02/02/spring-mvc-annotaion.html)를 참고해주세요

헥심적인 로직은 분석 결과 ConfigurationClassParser.parse 에서 발생하는 듯 합니다.
블로그 내용과 ConfigurationClassParser를 추척하면 어디서 `@Bean` 어노테이션을 리졸브 하는지 알 수 있습니다.


![Screen Shot 2021-07-18 at 4 46 18 PM](https://user-images.githubusercontent.com/30731518/126059893-1a9c5af3-9c8e-4989-9557-3a7839ec4749.png)


‼️ BeanDefinitionScanner도 있고 BeanDefinitionReader도 있는데 이 두 가지의 차이도 함께 보면 좋을 듯 합니다

**Comment by binchoo** [comment]
[ClassPathBeanDefinitionScanner#L284]
```java
protected Set<BeanDefinitionHolder> doScan(String... basePackages) {
		Assert.notEmpty(basePackages, "At least one base package must be specified");
		Set<BeanDefinitionHolder> beanDefinitions = new LinkedHashSet<>();
		for (String basePackage : basePackages) {
			Set<BeanDefinition> candidates = findCandidateComponents(basePackage);
			for (BeanDefinition candidate : candidates) {
				ScopeMetadata scopeMetadata = this.scopeMetadataResolver.resolveScopeMetadata(candidate);
				candidate.setScope(scopeMetadata.getScopeName());
				String beanName = this.beanNameGenerator.generateBeanName(candidate, this.registry);
				if (candidate instanceof AbstractBeanDefinition) {
					postProcessBeanDefinition((AbstractBeanDefinition) candidate, beanName);
				}
				if (candidate instanceof AnnotatedBeanDefinition) {
					AnnotationConfigUtils.processCommonDefinitionAnnotations((AnnotatedBeanDefinition) candidate);
				}
				if (checkCandidate(beanName, candidate)) {
					BeanDefinitionHolder definitionHolder = new BeanDefinitionHolder(candidate, beanName);
					definitionHolder =
							AnnotationConfigUtils.applyScopedProxyMode(scopeMetadata, definitionHolder, this.registry);
					beanDefinitions.add(definitionHolder);
					registerBeanDefinition(definitionHolder, this.registry);
				}
			}
		}
		return beanDefinitions;
	}
```

**Comment by emiling** [comment]
### 핵심 질문
- `messageProvider`에 어떠한 원리로 `HelloWorldMessageProvider`가 주입되나요?

```java
/* StandardOutMessageRenderer.java */
@Service("renderer")
public class StandardOutMessageRenderer implements MessageRenderer {
    private MessageProvider messageProvider; 

    @Override
    @Autowired
    public void setMessageProvider(MessageProvider provider) {
        this.messageProvider = provider;
    }
}
```
![Screen Shot 2021-09-12 at 12 20 39 PM](https://user-images.githubusercontent.com/30731518/132970844-3aaf0185-89ed-483c-9101-93b531cd9188.png)

- `setMessageProvider`가 호출 될 때는 이미 setter의 파라미터로 `MessageProvider` 타입의 `HelloWorldMessageProvider` 빈이 지정되어 있다.
- 따라서 해당 질문을 다시 생각해보면 결국 `setMessageProvider`가 호출되는 시점을 추적해보면 어떻게 인터페이스로 해당 빈을 주입하는지 알 수 있을 것 같다.


### 전제사항
- 이미 이전 시간에 `ConfigurationClassParser.parse`에서 `@Component` 어노테이션을 파싱하여 `BeanDefinition`으로 관리하고 있는 것을 코드상에서 확인하였고 이젠 그러한 `BeanDefinition` 맵 중 각각의 빈 중에서 의존성이 걸려있는 빈을 어떻게 연결 혹은 주입하는지 알아보려고 한다.

### 코드 분석
- `refresh()` 의 `this.finishRefresh()` 단계에서 발생하는 로직이다.

```java
    // [AutowiredAnnotationBeanPostProcessor#251]
    public PropertyValues postProcessProperties(PropertyValues pvs, Object bean, String beanName) {
        InjectionMetadata metadata = this.findAutowiringMetadata(beanName, bean.getClass(), pvs);
        try {
            metadata.inject(bean, beanName, pvs);
            return pvs;
        } catch (BeanCreationException var6) {
            throw var6;
        } catch (Throwable var7) {
            throw new BeanCreationException(beanName, "Injection of autowired dependencies failed", var7);
        }
    }
```
- 해당 부분에서 `renderer` 빈이 들어오게 되면 `metadata.inject(bean, beanName, pvs);` 에서 이전에 만들어진 `InjectionMetadata` 정보를 토대로 빈을 주입한다
- 이후 [InjectionMetadata#61]의 `element.inject(target, beanName, pvs)`에서  inject 함수를 호출하여 실질적인 `HelloWorldMessageProvider`가 주입된다.


- [DefaultListableBeanFactory#doResolveDependency]
  - `Map<String, Object> matchingBeans = this.findAutowireCandidates(beanName, type, descriptor);`
  - `requiredType` 기반으로 이전에 생성된 빈 중에서 `candidate`를 뽑아 설정


### 추가
- 물론 `@Autowired`나 생성자 주입 과정은 살펴보지 않았지만 비슷한 원리로 적용될 것이라 생각됩니다.
