### ISSUE TITLE
[question] 과연 수정자 주입이 가장 좋은 의존성 주입 방식일까요 🤔

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#13]
## 질문

수정자 주입 vs 생성자 주입

## 상세 내용
> 기본 의존성을 제공할 때는 일반적으로 수정자 주입이 의존서에 주입에 가장 좋은 방법입니다. (p.90)

> 실제로 수정자 의존성 주입은 가장 널리 사용되며 구현하기 가장 간단한 의존성 주입 메커니즘 중 하나입니다. (p.87)

현재 많은 블로그 포스팅에서 필드 주입(Autowired) 방식보다 **생성자 주입**  방식을 사용해야 한다고 합니다.
그 이유에 대해 한 번 생각해보고 정말 수정자 주입이 생성자 주입보다 좋은지도 함께 생각해봅시다 😃

(p.93)
- 수정자 주입
  - 새로운 객체를 생성하지 않아도 의존성을 교체할 수 있을 때 좋음
- 생성자 주입
  - 컴포넌트에 의존성 주입을 보장하거나 불변 객체를 설계하는 경우 좋음
- 필드 주입
  - **단일 책임 원칙**을 위반하지 않도록 주의해야 한다
  - 어떤 타입의 의존성이 실제로 필요한지 혹은 의존성이 필수인지 여부가 명확하지 않을 수 있음
  - `final` 필드에 사용 불가
  - 테스트 코드를 작성하기 힘듦

## 연관 챕터
#10

## 참고

생성자 주입이라고 구글링하면 나오는 결과

![Screen Shot 2021-07-16 at 2 17 40 AM](https://user-images.githubusercontent.com/30731518/125830757-733ea647-e357-4974-97ab-71bcc728f06e.png)

**Comment by wooyounggggg** [comment]
스프링 공식 docs에도 관련 내용에 대한 언급이 있어 [참고 링크](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-dependencies) 남깁니다

**Comment by binchoo** [comment]
원서는 어떤 용어를 쓰는지 궁금하여 살펴봤습니다.

[원서 p.41 마지막 문단](http://silab.fon.bg.ac.rs/wp-content/uploads/2019/05/Spring-5.pdf)
 > Within the container, the dependency requirement exposed by the setDependency() method is referred to by the JavaBeans-style name, dependency. In practice, setter injection is the most widely used injection mechanism, and it is one of the simplest IoC mechanisms to implement.

[원서 p.42 마지막 문단](http://silab.fon.bg.ac.rs/wp-content/uploads/2019/05/Spring-5.pdf)
> Setter injection is useful in a variety of cases. If the component is exposing its dependencies to the
container but is happy to provide its own defaults, setter injection is usually the best way to accomplish
this. 

컨테이너에게 의존성을 노출하되 (→ 컨테이너는 수정자 메서드를 보고 컴포넌트의 의존성 요구사항을 알게 됨) 기본값 의존성을 제공해주고 싶다면, 수정자 주입이 가장 좋은 방식.


[스택오버플로](https://stackoverflow.com/questions/7779509/setter-di-vs-constructor-di-in-spring) 담론들도 보면
의존성이 Optional 하거나 합리적인 기본값이 있을 경우 수정자 주입을 써야 한다는 의견들이네요.

생성자 vs 수정자의 경우 유스 케이스에 맞게 쓰면 될 것 같고

필드 주입의 경우는, 오직 컨테이너가 리플렉션으로 의존성을 주입할 수 있는 터라
자신의 코드로 테스트용 의존성을 넣어주기가 어려워 보이네요.
