### ISSUE TITLE
[question] @Configuration이 써드 파티 라이브러리 타입의 빈 구성에 유용한 이유?

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/pro-spring-5#16]
## 질문

`@Configuration`이 써드 파티 라이브러리 타입의 빈 구성에 유용한 이유?

## 상세 내용
`@Configuration`으로 구성 클래스를 만들어  `ApplicationContext`를 설정하는 "자바 구성 방식"은
빈 타입이 써드 파티 라이브러리의 것일 때 유용하다고 합니다.

- XML + `<bean>` 구성
- XML + `<context:component-scan>` + 스테레오타입 어노테이션 구성
- `@Configuration` + `@ComponentScan` + 스테레오타입 어노테이션 구성
- `@Configuration` + `@Bean` (자바 구성)

각 구성 방식으로 "써드 파티 라이브러리의 타입"을 빈으로 구성할 때 어떤 어려움이 있을 지 생각해 보아야 할 것 같습니다.

## 연관 챕터
챕터 3.5.3.1 (#10)

## 참고
[책 p.106](https://thebook.io/006987/ch03/05/03-06/)

cc. @caffeine-library/readers-pro-spring-5

**Comment by binchoo** [comment]
## XML + <bean> 구성
본인이 만들지도 않은 써드 파티 라이브러리의 패키지 구성을 이해하여
`<bean>`의 `class` 속성 값으로 일일히 작성해 넣어주는 일은 상당히 피로할 것이라 생각한다.

## XML + 컴포넌트 스캔 + 스테레오 타입 어노테이션 구성
써드 파티 라이브러리는 수정이 불가능하므로 스테레오 타입 어노테이션을 붙일 수가 없다;

## `@ComponentScan` + 스테레오 타입 어노테이션 구성
위 케이스와 마찬가지

## 자바 구성
자바 코드로 빈을 생성하여 반환해주는 메서드를 작성하고 `@Bean`을 붙이는 것으로 `ApplicationContext`이 구성된다.
이 때 빈 타입을 IDE가 자동으로 resolve 해 주기 때문에 나머지 3가지 구성 방식보다 효율적이라 생각한다.

**Comment by emiling** [comment]
**써드 파티 라이브러리의 타입을 빈으로 구성한다** 라는 점이 가장 와닿았던 건  
application-conext.xml 설정에 의한 auto configuration 방식이 아닌 셋업시 설정을 자바 구성으로 설정해주는 경우였는데요 😃 
auto configuration으로 지원되지 않는 좀 더 자세하고 구체적인 설정이 필요할 때 주로 사용하는 것 같습니다.

ex. Swagger Java Configuration

```java
@Configuration
public class SwaggerConfig {
    @Bean
    public OpenAPI openAPI(@Value("${springdoc.version}") String appVersion){
        Info info = new Info().title("Caffeine Library API Document").version(appVersion)
                .description("Caffeine Library API Document by swagger");
        return new OpenAPI().components(new Components()).info(info);
    }
}
```
