### ISSUE TITLE
[question] 템플릿 패턴에 대해 알아봅시다

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#17]
## 질문
템플릿 패턴에 대해 알아봅시다

## 상세 내용
템플릿 패턴에 대해 알아봅시다
IoC/DI와 연관점도 같이 찾아보면 좋을 듯 합니다

## 연관 챕터
#10

**Comment by binchoo** [comment]
## 템플릿 메서드 패턴
### 개요
코드가 완전히 동일한 절차를 따르나, 일부 절차의 상세 구현에 차이가 있을 경우에 사용하는 패턴
  - 상위 클래스: 실행 절차를 정의한다. (상위 정책)
  - 하위 클래스: 실행 과정의 일부 단계를 구현한다.

### 예시
유저 인증 정책
- 유저 인증 상위 정책
  [1] id와 pwd의 **정합성을 검증**한다. 정합하지 않으면 예외를 던진다.
  [2] 정합할 경우 **인증 정보를 반환**한다.
  ```java
  public Auth authenticate(String id, String pw) {
    if (!doAuthenticate(id, pw)) // 1
      throw createException();
    return createAuth(id); // 2
  }
  ```

- 유저 인증 하위 정책
구현체에 따라 **정합성 검증** 및 **인증 정보 반환** 방식이 달라질 수 있다. 
   - `LDAPAuthenticator`는 `LdapClient`에게 정합성 검증을 위임한다.
  - `DBAuthenticator`는 DB 테이블을 조회하여 id/pwd 정합성을 검증할 것이다.
따라서 이 기능들은 추상 메서드로 정의하여 하위 클래스가 구현하거나, 상위 클래스가 기본 구현을 제공하고 `@Override` 하는 방식도 가능하다.

### IoC
프로그램 흐름을 상위 정책이 제어한다. 하위 클래스는 이 흐름에 준수하여 구체적인 구현을 제공할 뿐이다.
클라이언트는 상위 타입에 의존해 하위 구현체의 서비스를 받을 수 있다.
상위 정책은 고정된 틀을 가진 "템플릿" 이므로 템플릿 메서드 패턴이라고 한다.

### 참고
[개발자가 반드시 정복해야 할 객체 지향과 디자인 패턴](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788969090010) - 최범균 저
https://brunch.co.kr/@springboot/31
