### ISSUE TITLE
[keyword] 3장 스프링 IoC와 DI 소개 (2) 키워드 정리

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#21]
## 주제
[3장] 스프링 IoC와 DI 소개 (2) 를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요
## 연관챕터
#20

**Comment by wooyounggggg** [comment]
생각보다 키워드 크기가 커져서 해당 키워드는 발표 형태로 진행한 후에 의견 나눠보면 좋을 것 같습니다~

### IoC와 DI
#### 개요
스프링은 객체지향적인 프로그램 설계를 위한 3대 철학을 제시하고 있습니다.

<p align="center">
<img src="https://github.com/caffeine-library/pro-spring-5/blob/main/references/images/spring%20triangle.png?raw=true" width="300px" height="280px"/>
</p>

위와 같은 스프링 삼각형에서, IoC/DI, AOP, PSA 세 가지 철학을 준수하면서 프로그램을 작성하다보면 그 결과물로 `POJO(Plain Old Java Object)`를 얻을 수 있는 것을 알 수 있습니다.

그렇다면 3가지 개념들이 각자 POJO를 생산하는데 일조하고 있다는 얘기가 되는데, 어떠한 부분에서 IoC/DI라는 개념이 POJO 클래스를 만들어내지, 그 연결점을 이해한다면 스프링이 그리는 큰 그림에 대해 이해하기 수월할 것 같다고 생각하여 IoC/DI 키워드를 발행하였습니다.

- POJO란?
- IoC(Inversion of Control, 제어의 역전)란?
- IoC와 DI의 관계
- 프레임워크와 라이브러리의 차이
- IoC/DI와 POJO

#### POJO란?
[Wikipedia의 글](https://ko.wikipedia.org/wiki/Plain_Old_Java_Object)에서 다음의 내용을 찾아볼 수 있었습니다.
> Plain Old Java Object, 간단히 POJO는 말 그대로 해석을 하면 오래된 방식의 간단한 자바 오브젝트라는 말로서 Java EE 등의 중량 프레임워크들을 사용하게 되면서 해당 프레임워크에 종속된 "무거운" 객체를 만들게 된 것에 반발해서 사용되게 된 용어이다. 
참고 - [※ POJO의 탄생 배경](https://isstory83.tistory.com/94)

POJO의 구체적인 예시를 `토비의 스프링`에서 발췌하였습니다.

```java
/* 트랜잭션 로직 분리전 */
public class UserService {
    
    ...

    /* POJO 지향적이지 않은 메서드 */
    public void upgradeLevels() throws Exception {
        TransactionSynchronizationManager.initSynchronization(); // upgradeLevels()에서 트랜잭션 동기화 로직을 같이 수행함
        Connection c = DataSourceUtils.getConnection(dataSource); // upgradeLevels()에서 DB Connection 로직을 같이 수행함
        c.setAutoCommit(false);

        try {
            /* -------- upgradeLevels()의 주된 관심 로직 -------- */
            List<User> users = userDao.getAll();
            for(User user: users) {
                if(canUpgradeLevel((user))) {
                    upgradeLevel(user);
                }
            }
            /* -------- upgradeLevels()의 주된 관심 로직 -------- */
            c.commit();
        } catch (Exception e) {
            c.rollback();
            throw e;
        } finally {
            DataSourceUtils.releaseConnection(c, dataSource);
            TransactionSynchronizationManager.unbindResource(this.dataSource);
            TransactionSynchronizationManager.clearSynchronization();
        }
    }
}
```
```java
/* 트랜잭션 로직 분리후 */
public class UserServiceImpl implements UserService {
    ...
    public void upgradeLevels() {
        List<User> users = userDao.getAll();
        for (User user: users) {
            if (canUpgradeLevel(user)) {
                upgradeLevel(user);
            }
        }
    }
}

public class UserServiceTx implements UserService {
    ...
    UserService userService; // UserServiceImpl이 주입됨
    PlatformTransactionManager transactionManager;

    public void setTransactionManager(... transactionManager) {
        this.transactionManager = transactionManager;
    }

    public void upgradeLevels() {
        // Transaction 로직
        // ...
       try {
            userService.upgradeLevels();

            this.transactionManager.commit(status);
        } catch (RuntimeException e) {
            this.transactionManager.rollback(status);
            throw e;
        }
    }
}

public class SomeClient {
    public static void main(String... args) {
        UserService userService = new UserServiceTx();
        userServiceTx.upgradeLevels();
    }
}
```

`기존 코드`에서는 UserService에서 `Transaction 관리 코드`를 함께 수행하고 있으나, 
`수정된 코드`에서는 프록시 클래스인 `UserServiceTx`를 생성하여 UserService가 가지고 있는 Transaction 로직을 UserServiceTx에게 위임하고, 이후 UserService의 순수한 비즈니스 로직을 가진 UserServiceImpl 클래스의 upgradeLevels()를 호출하는 모습을 볼 수 있습니다.

`UserServiceImpl` 클래스의 코드에는 Transaction과 관련한 어떠한 로직도 찾을 수 없고, 순수하게 사용자 레벨을 조정하는
기능만을 수행하고 있는데, 이러한 모습처럼 특정 서비스에 의존하지 않는 형태의 클래스가 `POJO`가 아닐까 생각합니다.

기존 UserService의 upgradeLevels()는 Transaction Service와 강하게 결합되어 있었기 때문에, upgradeLevels()가 가진 비즈니스 로직을 Transaction 없이 재사용하는 것이 불가능합니다.
개선된 UserServiceTx, UserServiceImpl의 upgradeLevels()는 TransactionService를 수행하는 계층이 분리되어 있기 때문에
upgradeLevels()를 Transaction 없이 다른 기능과도 결합하여 사용할 수 있으므로 재사용성이 증가합니다.
이러한 부분이 스프링에서 POJO를 지향하는 이유가 아닐까 생각합니다.

#### IoC(Inversion of Control, 제어의 역전)란?
IoC는 단어 그대로 `프로그램 흐름의 제어`가 역전됨을 의미합니다. 책에서 보았던 `MessageProvider`, `MessageRenderer`에서
제어의 역전을 발견하기 좋은 것 같습니다.

```java
/* StandardOutMessageRenderer.java */
public class StandardOutMessageRenderer implements MessageRenderer {

    private MessageProvider messageProvider;

    // MessageProvider의 setter를 이용해 MessageRenderer를 사용하는 클라이언트(HelloWorldDecoupled.java) 측에서 
    // 객체를 생성하여 주입
    @Override
    public void setMessageProvider(MessageProvider messageProvider) { 
        this.messageProvider = messageProvider;
    }
    ...
}

/* HelloWorldMessageProvider.java */
public class HelloWorldMessageProvider implements MessageProvider{
    @Override
    public String getMessages() {
        return "Hello World";
    }
}

/* HelloWorldDecoupled.java */
public class HelloWorldDecoupled {
    public static void main(String[] args) {
        MessageProvider mp = new HelloWorldMessageProvider();
        MessageRenderer mr = new StandardOutMessageRenderer();
        mr.setMessageProvider(mp);
        mr.render();
    }
}
```

위의 코드가 제어가 역전된 모습이라면, IoC의 개념이 적용되기 이전의 모습은 아래와 같을 것입니다.

```java
public class StandardOutMessageRenderer implements MessageRenderer {

    // MessageRenderer가 자체적으로 객체를 생성하여 소유하고 있음
    private MessageProvider messageProvider = new HelloWorldMessageProvider(); 

    @Override
    public void render() {
        if (messageProvider == null) {
            throw new RuntimeException(
                "You must set the property messageProvider of class:"
                    + StandardOutMessageRenderer.class.getName()
            );
        }
        System.out.println(messageProvider.getMessages());
    }
    ...
}
```

IoC 개념이 적용되기 이전에는 `클래스`에서 필요한 `의존성(객체)`들을 해당 클래스에서 `자체적으로 생성하고 활용`합니다.
반면, IoC 개념이 적용된 MessageRenderer는 Renderer에서 자체적으로 의존성을 정의하는 것이 아니라, Renderer를 사용하는
누군가(Class, ...) 필요한 의존성을 생성하여 주입합니다.

그래서, 기존에 자체적으로 의존성을 생성하고 관리하던 제어 권한을 누군가에게 빼앗겼기 때문에, 이를 `제어의 역전`이라 합니다.

#### IoC와 DI의 관계

> DI is a form of IoC, where implementations are passed into an object through constructors/setters/service lookups, which the object will 'depend' on in order to behave correctly.

DI는 IoC의 일종이라고 합니다. 위의 Message 예시에서처럼, DI를 활용하여 IoC의 개념을 구현하기 때문에 그런듯합니다.
이외에도 #17 템플릿 패턴 등을 통해 IoC의 개념 구현이 가능합니다.

#### 프레임워크와 라이브러리의 차이
[블로그 글](https://dev.to/rohitrana/what-is-the-difference-between-library-vs-framework-174n) 중 하나가 좋은 내용을 담고 있어 공유합니다.

### Key Difference between Library vs Framework
>The main key difference between the Library and Framework is something known as **`inversion of control.`**
Let's understand this inversion of control more in detail.
When you import a library, you have to call the specific methods or functions of your choice so, and it's up to you when and where to call the Library. Here, **`you are in charge of flow.`**
On the other hand, Framework itself makes a call to your code and provide you with some space to write down details.
So, while using framework **`your framework is in charge of flow.`**
**In Library, your code is going to call the Library whereas, in Framework, your code is being called by Framework.**

<p align="center">
<img src="https://github.com/caffeine-library/pro-spring-5/blob/main/references/images/framework%20vs%20library.png?raw=true" width="530px" height="240px"/>
</p>

내용에 따르면, 프레임워크와 라이브러리의 차이는 `Inversion of Control`의 적용 유무라고 합니다. 🔑 
이 말을 좀 더 자세히 이해하기 위해서, `프레임워크` - `개발자` - `라이브러리` 사이의 관계를 살피면 좋을 것 같습니다.

`프레임워크`를 사용하는 `개발자`는 프레임워크가 정의한 흐름에 따라, 프레임워크가 요구하는 사항 중 일부(ex. `Bean`)를 
제공하고, 나머지는 프레임워크가 정해놓은 흐름대로 프로그램을 개발합니다. 즉, 전체적인 프로그램의 제어 권한을 프레임워크가 가집니다.

`라이브러리`를 사용하는 `개발자`는 개발자 자신이 정의한 흐름에 따라, 기능 요구사항을 구현하기 위해 라이브러리를 활용하는
형태로 프로그램을 개발합니다. 프레임워크와는 반대로, 프로그램 제어 권한을 개발자 본인이 갖게 되는 것이죠.

개발자의 관점에서 프레임워크는 자신이 개발하려는 프로그램의 흐름 제어를 빼앗아가기 때문에, 이러한 개념으로부터 IoC의
적용 유무가 프레임워크냐 라이브러리냐를 결정짓는 것이라고 생각됩니다.
라이브러리의 관점에서 보면 개발자의 프로그램이 프레임워크라고도 생각할 수 있지 않을까 하는 의견입니다. 😃
여담으로, express.js나 vue.js 등의 framework들도 `IoC 컨테이너`가 존재한다고 하네요 😃 

스프링은 프레임워크입니다. 특히 `객체지향 프레임워크`이죠.
그렇게 얘기하는 이유는 아마 객체 지향의 중심인 `객체`의 라이프사이클을 정의하고 그들간의 관계를 설정하는 일련의 작업들을  개발자가 정의하는 것이 아니라, 스프링의 IoC 컨테이너에게 위임하여 대신하게 하기 때문에, 즉 제어가 역전된 상태에서 객체를
프레임워크 수준에서 관리하기 때문에  `객체지향` + `프레임워크`라고 부르는 것이 아닐까 생각해봅니다.

#### IoC/DI와 POJO
처음의 주제로 돌아가서, 왜 스프링이 POJO를 지향하기 위해 IoC/DI를 제시했는지 생각해보아야 할 것 같습니다.
스프링 개발의 출발점은 일반 자바 객체를 `빈`으로 등록하는 것입니다. 객체를 빈으로 등록하는 행위는, 단순히 의존성 주입만을 스프링에게 기대하는 것이 아니라 개발자의 객체 제어 권한을 프레임워크에게 넘기는, 제어 역전(IoC)입니다.

제어 권한을 넘겨받은 스프링은 그 순간부터 개발자가 POJO 형태로 정의한 객체를 다양한 방식으로 조작하여 의존성을 주입하기도 하고(DI), 필요한 기능들을 덧붙이기도 합니다(AOP 등). 
역으로 말하면, '스프링이 순수 객체에 다양한 기능을 덧붙여주는 지원을 해주기 때문에, 개발자는 POJO 형태로 객체를 정의하는 것이 가능해진다'라고 생각이 되네요.

제 의견이 들어간 짧은 문장들로 키워드를 마치도록 하겠습니다.

- 스프링 3대 철학 중, IoC/DI는 객체의 `Permission`과 관련한 내용이다.
- IoC를 통해 스프링은 객체의 제어 권한을 넘겨받아 DI나 AOP 등의 `객체 조작`이 가능해진다.
- 이러한 행위들로 하여금, 개발자는 클래스가 기능을 수행하기 위해 부가적으로 필요한 부분들(트랜잭션, ...)을 클래스로부터 분리할 수 있다.
- 그렇기 때문에, IoC/DI는 POJO 클래스를 생산할 수 있게 하는 시작점이다.

### 참고
- [Plain Old Java Object - wikipedia](https://ko.wikipedia.org/wiki/Plain_Old_Java_Object)
- [POJO의 탄생배경 - google](https://isstory83.tistory.com/94)
- [Inversion of Control vs Dependency Injection - stackoverflow](https://stackoverflow.com/questions/6550700/inversion-of-control-vs-dependency-injection)
- [Framework vs Library - google](https://dev.to/rohitrana/what-is-the-difference-between-library-vs-framework-174n)

**Comment by emiling** [comment]
## 메서드 주입
### 룩업 메서드 주입
- 어떤 빈이 다른 라이프사이클을 가진 빈에 의존할 때 발생하는 문제를 극복
  - 수정자 혹은 생성자 주입을 통해 의존하는 비싱글톤 빈을 싱글톤으로 만들어버리는 경우 방지
  - 자신에게 필요한 비싱글톤 빈 인스턴스를 매번 새로 얻고 싶은 경우
  
<details>
<summary>구현 방식</summary>
<div markdown="1">       

```xml
<bean id="abstractLookupBean" class="com.apress.prospring5.ch3.AbstractLookupDemoBean">
    <lookup-method name="getMySinger" bean="singer"/>
</bean>
```
혹은

```java
@Component("abstractLookupBean")
public class AbstractLookupDemoBean implements DemoBean {
    @Lookup("singer")
    public Singer getMySinger() {
        return null; // 동적으로 오버라이드 됨
    }
    ...
}

@Component("singer")
@Scope("prototype")
public class Singer {
   ...
}

```

</div>
</details>

추상클래스는 인스턴스화를 못 함에도 불구하고 CGLIB을 통해 abstract 메서드를 동적으로 재정의 한 뒤 
이를 바탕으로 spring에서는 해당 abstract 클래스의 하위 클래스를 생성하여 일종의 스텁 구현체 생성

### 메서드 대체
- 주입 외에 수정중인 빈의 소스를 변경하지 않고 임의로 모든 메서드의 구현체 변경 가능
- 특정 메서드의 로직을 사용자의 구현체로 변경
<details>
<summary>구현 방식</summary>
<div markdown="1">       

```java
public class FormatMessageReplacer implements MethodReplacer {

	@Override
	public Object reimplement(Object arg0, Method method, Object[] args)
			throws Throwable {
		if (isFormatMessageMethod(method)) {
			String msg = (String) args[0];
			return "<h2>" + msg + "</h2>";
		} else {
			throw new IllegalArgumentException("Unable to reimplement method "
					+ method.getName());
		}
	}

	private boolean isFormatMessageMethod(Method method) 
        ...
}
```
```xml
<bean id="replacementTarget" class="com.apress.prospring5.ch3.ReplacementTarget">
        <replaced-method name="formatMessage" replacer="methodReplacer">
            <arg-type>String</arg-type>
        </replaced-method>
    </bean>
```


</div>
</details>


`MethodReplacer` 인터페이스의 구현체를 정의하고 `reimplement` 구현
그리고 `<replaced-method>` 태그로 대체할 메서드와 해당 메서드를 가진 빈의 이름 매핑

## 빈 명명규칙

<details>
<summary>요약</summary>
<div markdown="1">       

### Annotation
- `@Component("a")`  → 괄호 안에 적은 것이 빈의 `id`가 된다
- `@Bean("b")` , `@Bean(name="b")  → 괄호 안에 적은 것이 빈의 `id`가 된다
  - `@Bean(name = {"johnMayer", "john", "jonathan", "johnny"})` → 맨 첫번째 것이 `id`, 나머지는 alias
-  `@AliasFor`

### XML


- `<bean id=... />` 
- `id`가 없으면 <bean name=.../>`
- `id`와 `name` 모두 없으면 스프링은 빈의 클래스 이름을 빈 이름으로 사용
- `alias` : `id` 혹은 `name` 들에 대한 별칭 정의

→ 일반적으로는 `id`로 이름을 주고 다른 이름을 사용하는 빈과 연관시킬 때는 `alias`
→ `name`은 구분자로 하나의 문자열에 여러개 설정 가능하지만 `id`는 하나의 문자열로 설정됨

</div>
</details>

## 빈 생성방식
- 싱글턴과 싱글턴 디자인 패턴
  - 싱글턴이란 단일 인스턴스를 의미
  - 싱글턴 패턴의 경우 클래스가 단일 인스턴스로 동작하게 하면서 인터페이스를 완전히 사용할 수 없는 결합도 높은 객체 룩업을 위한 패턴
  - 스프링에서는 싱글턴 디자인 패턴을 사용하지 않고도 싱글턴 생성 및 사용 가능
- 디폴트는 싱글턴이므로 `@Scope("singleton")`하며 때에따라 `@Scope("prototype")` 사용 


## 의존성 해석하기
- 사용자가 정의한 빈 사이의 의존성을 인식시키기 위함
- `<depends-on= ... />` 혹은 `@DependsOn`
- 어플리케이션 개발 시 이 기능을 사용할 수 있게 하면 안 됨

## 빈에 자동 와이어링

## 빈 상속

**Comment by JasonYoo1995** [comment]
# IoC, DL, DI, 제어권, EJB, Spring

우영님 글을 읽고 구글링을 많이 해보고 저 나름대로 그림을 한 번 그려봤는데
틀린 부분도 있을 테니 의견 부탁드립니다.

프레임워크의 도움을 받지 않고 직접 코드를 작성했을 때는 다음과 같은 그림이 될 것입니다.

![image](https://user-images.githubusercontent.com/66045861/126861966-e3b807fd-c20b-4e3a-ac6a-1dad3abcab6b.png)

제어권

![image](https://user-images.githubusercontent.com/66045861/126861968-f5454135-33a3-4993-82fc-05c0e937e314.png)
![image](https://user-images.githubusercontent.com/66045861/126861969-305676d5-2e74-4dd3-85b0-2c69a04640e0.png)

**Comment by wooyounggggg** [comment]
@JasonYoo1995 
>여기서 의문이 있는데, DI와 달리 DL은 컨테이너가 아닌 개발자 코드가 제어권을 갖는다고 했는데, 그렇다면 Inversion of Control 즉 제어권의 역전이 이루어지지 않은 것 아닌가요?

--> DL은 왜 개발자의 코드가 제어권을 가지게 되나요?

**Comment by JasonYoo1995** [comment]
@wooyounggggg 
일단 더 구글링을 해보니 EJB에서 제어권은 DL 컨테이너가 가지는 게 맞는 것 같고요
제 의문은 뭐냐면
일단 Spring에서 DI 컨테이너가 의존 관계를 설정해놓은 상태의 객체를 넘겨주는 것이 명백한데
EJB에서 DL 컨테이너도 의존 관계를 설정해놓은 상태로 객체를 제공하는지 아니면 의존 관계는 개발자에게 맡기는지에 대한
명백한 증거(명확한 설명 혹은 소스 코드)를 아무리 구글링해도 찾기 어렵더라고요
그래서 헷갈립니다.

**Comment by binchoo** [comment]
## Scope 어노테이션
빈 스코프 = 스프링이 기본 제공하는 빈의 라이프사이클 관리 6가지
- 기본 2가지 (싱글톤, 프로토타입)
- web-aware 스프링에서 사용가능한 4가지 (리퀘스트, 세션, 어플리케이션, 웹소켓)

Scope | 설명
-- | --
singleton | (기본) 빈 정의는 각 IoC 컨테이너 단위의 싱글턴 객체에 대응.
prototype | 빈 정의로부터 임의의 숫자의 객체 인스턴스를 생성할 수 있음.
request | 빈 정의는 각 HTTP 요청 단위의 싱글턴 객체에 대응. 
session | 빈 정의는 각 HTTP 세션 단위의 싱글턴 객체에 대응. 
application | `ServletContext` 단위
websocket | `WebSocket` 단위

### XML 구성 방식 + `<lookup-method>`
룩업 하는 빈의 스코프는 알아서 `prototype`이 됩니다.

### 자바 구성 방식 + `@Lookup` without @Scope("prototype")
룩업 하는 빈의 스코프는 기본값인 `singleton`이 됩니다.

### 자바 구성 방식 + `@Lookup` + @Scope("prototype")
책에서 보여준 방식입니다. 룩업 하는 빈의 스코프는 `prototype`이 되어 XML 구성 방식과 동일합니다.

**Comment by JasonYoo1995** [comment]
## EJB와 Spring의 비교

||EJB|Spring
|:---:|:---:|:---:
|**기본적인 IoC의 종류**|DL (단, EJB 3.0부터 DI도 지원)|DI (단, 일부분 DL도 사용)
|**제어권 소유**|EJB 컨테이너|Spring 컨테이너
|**비즈니스 로직의 컨테이너 종속**|종속|독립
|**비즈니스 로직을 컨테이너로부터 분리**|불가|가능
|**프레임워크 vs 라이브러리**|프레임워크|프레임워크|
|||

추가적으로 덧불일 내용이 있다면 'Edit'을 통해 추가 부탁드립니다.

**Comment by binchoo** [comment]
## 자동 와이어링 지양하기

### 자동 와이어링이 IoC를 해치는 이유
- `byName`: 
  - XML에 정의된 빈 name에 맞추어 클래스 필드명을 작성하는 행위.
    ```java
    class Target {
        private Foo foo1;  
        private Foo foo2;  
        // XML에 정의된 빈 name에 대한 지식이 필요함.
    }
    ```
  - 클래스 필드명에 맞추어 빈 name을 정의하는 행위.
    ```xml
    <bean id="foo1" class="org.binchoo.example.Foo" />
    <bean id="foo2" class="org.binchoo.example.Foo" />
    <!-- 클래스에 정의된 필드명에 대한 지식이 필요함. -->  

    <bean id="target" class="org.binchoo.example.Target" autowire="byName" />
     ```

- `byType`:
  - 같은 타입의 빈 충돌을 해결하기 위해 `primary`, `@Primary`, `@Qualifier`라는 메타 정보를 프레임워크에게 알려주어야 함.
  - `@Qualifier`는 코드가 빈 name에 의존하거나, 빈 정의가 코드에 의존하도록 하므로 `byName`이 갖는 문제점과 동일함.

### 결론
빈 연결 설정은 XML에 몰아두어서, 코드가 프레임워크에 의존하지 않는 IoC를 실현해야 한다.
