### ISSUE TITLE
[question] Lookup 메서드 주입시 추상 클래스를 사용하는 이유가 무엇인가요?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#22]
## 질문
Lookup 메서드 주입시 추상 클래스를 사용하는 이유가 무엇인가요?

## 상세 내용
책 p.147 ~ 151에서 서로 다른 라이프사이클을 가지는 두 빈의 의존관계를 설정하기 위해, prototype scope을 갖는
빈 태그의 자식 태그로 `<lookup-method />`를 선언하고 해당 빈의 클래스를 `추상 클래스`로 선언합니다.

이후 스프링은 `CGLIB`를 통해 해당 추상 클래스의 `서브클래스`를 자동으로 생성하고, 해당 클래스를 빈으로 등록하여
bean을 요구할 때마다 `새로운 객체를 생성`하여 반환합니다.

여기서 조금 이해되지 않는 부분은, 왜 해당 클래스를 추상 클래스로 선언해서 CGLIB를 통해 서브 클래스를 생성해야만 했는지,
그 필연성이 직관적으로 느껴지지가 않습니다.

관련하여 이유를 알고 계시다면 말씀해주시면 좋을 것 같고, 그게 아니라면 같이 고민해보면 좋을 것 같습니다.

## 연관 챕터
#20

**Comment by wooyounggggg** [comment]
책을 좀 더 읽다보니 답이 나오네요!

`p.156`에서, 다음과 같은 문장을 발견할 수 있었습니다.
> **룩업 메서드를 반드시 추상화할 필요는 없지만, 추상화를 하면 룩업 메서드 구성을 해야 한다는 것을 잊고 있다가 우연히 비어있는 구현체를 사용하게 되는 상황을 방지할 수 있다는 것입니다.**

이슈는 스터디 당일에 닫도록 하겠습니다~

**Comment by emiling** [comment]
책을 읽으면서 어느 정도 다들 이해하셨겠지만 스스로 정리할 겸 몇 마디 적겠습니다 😊

사실 이렇게 `abstract` 클래스로 만들어서 하나

```java
public abstract class AbstractLookupDemoBean implements DemoBean {
    public abstract Singer getMySinger();
    ...
}

```
이렇게 일반 클래스로 만들어서 하나 
```java
public class AbstractLookupDemoBean implements DemoBean {
    public Singer getMySinger() {
        return null;
    }
    ...
}
```

결국 CGLIB에 의해 `<lookup-method name=.../>` 혹은 `@Lookup("name")` 에 표기된 `name` 메서드가 동적으로 재정의 되기 때문에  
굳이 `abstract`를 안 써도 룩업 메서드를 사용하는 것에는 지장이 없습니다.

그럼에도 `abtract`를 쓰는 것이 좋다고 하는 이유는 **추상 클래스는 인스턴스 생성을 못하기 때문에**

```xml
    ...
    <bean id="abstractLookupBean" class="com.apress.prospring5.ch3.AbstractLookupDemoBean">
        <!--<lookup-method name="getMySinger" bean="singer"/> -->
    </bean>
   ...
```
이렇게 `<lookup-method/>`를 빠뜨리고 XML 구성을 할 때 좋은 IDE에서는 syntax 에러로 아래와 같이 잡아주고

![Screen Shot 2021-07-24 at 1 36 38 AM](https://user-images.githubusercontent.com/30731518/126813769-916824e6-8c76-452f-91d4-07477313c67d.png)

이를 못 보고 실행을 하고자 해도 아래와 같이 런타임이 아닌 빌드타임에 에러를 잡아줍니다.

![Screen Shot 2021-07-24 at 1 37 52 AM](https://user-images.githubusercontent.com/30731518/126813959-2e628d80-9337-4fb0-bca5-c7442ded3fa2.png)

> 룩업 메서드를 반드시 추상화할 필요는 없지만, 추상화를 하면 룩업 메서드 구성을 해야 한다는 것을 잊고 있다가 우연히 비어있는 구현체를 사용하게 되는 상황을 방지할 수 있다는 것입니다.

이 부분을 다른 말로 하면 
추상클래스의 경우 인스턴스화를 못하기 때문에 깜빡하고 메서드 룩업 없이 실행하고자 하면 빌드 타임에 에러가 나는 반면 
추상클래스가 아닌 경우 `return null`로 인해 깜빡하고 메서드 룩업 없이 실행하고자 하면 
도중에 `doSomething()`을 실행할 때 런타임에 NPE가 발생해서 심각한 장애 상황이 발생할 수 있습니다.

(사실 책에서도 적혀있듯 저 abstract에 의한 에러 방지는 XML 구성에서만 가능하므로 어노테이션 구성으로 하면 런타임시 NPE 봐야합니다😅 )

아래의 경우 어노테이션 방식에서 `@Lookup("singer")` 를 주석처리했을 때의 결과입니다.

![Screen Shot 2021-07-24 at 1 45 17 AM](https://user-images.githubusercontent.com/30731518/126814773-ec22b4cb-8c6a-4de5-84e2-bc148d4e1153.png)
