### ISSUE TITLE
[question] CGLIB이 무엇일까요?

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#24]
## 질문

[CGLIB](https://github.com/cglib/cglib)가 무엇일까요?

## 상세 내용

> [p.146] 이 두 가지 기능을 제공하기 위해 스프링은 CGLIB의 동적 바이트 코드 확장 기능을 사용합니다 

Hibernate에서도 사용되는 기능이라고 해서 어떤 역할을 하는지 짚고 넘어가면 좋을 듯 합니다.

## 연관 챕터
#20

## 참고

- Java의 Dynamic Proxy와 CGLIB 비교 

@caffeine-library/readers-pro-spring-5

**Comment by wooyounggggg** [comment]
[해당 링크](https://objectcomputing.com/resources/publications/sett/november-2005-create-proxies-dynamically-using-cglib-library)에 CGLIB에 대한 괜찮은 설명이 있네요.

> Under the covers, the CGLIB library uses ASM, a small but fast bytecode manipulation framework, to transform existing bytecode and generates new classes. In addition to the CGLIB library, scripting languages, such as Groovy and BeanShell, also use ASM to generate Java bytecode. ASM uses a SAX parser like mechanism to achieve high performance. Using ASM directly is not encouraged because it requires good knowledge of the JVM, including class file format and the instruction set.

`바이트 코드를 조작`하여 특정 코드를 덧붙이는 역할을 수행하는 라이브러리라고 합니다.

스프링이 AOP를 적용할 때, 인터페이스를 구현하지 않은 클래스에 대한 `런타임 위빙`이 불가능하기 때문에 CGLIB을 사용하는 유즈케이스가 있는 것으로 이해하고 있습니다.

그리고 CGLIB에 대해 이전부터 궁금했던 점이 있어 저도 꼬리질문 남깁니다.

#### Q. CGLIB는 `로드 타임 위빙`인가요 `컴파일 타임 위빙`인가요?

**Comment by emiling** [comment]
이 이슈는 AOP에 대한 챕터가 나올 때 까지 열어두겠습니다.

함께 알아두면 좋을 것들은 다음과 같습니다.
- JVM 동작 과정 (클래스 로더부터 바이트 코드 실행 등등ㅇ)
- Java Reflection 동작 과정
- Java의 Dynamic Proxy와 CGLIB 비교

**Comment by JasonYoo1995** [comment]
[위 comment](https://github.com/caffeine-library/pro-spring-5/issues/24#issuecomment-886046449)의
>Q. CGLIB는 `로드 타임 위빙`인가요 `컴파일 타임 위빙`인가요?

라는 질문의 답변은, `런타임 위빙`인 것 같습니다.
