### ISSUE TITLE
[keyword] 4장 스프링 구성 상세와 스프링 부트(1) 키워드 정리

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#26]
## 주제
[4장] 스프링 구성 상세와 스프링 부트(1)을 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요
## 연관챕터
#25

**Comment by binchoo** [comment]
## `<context : annotation-config>` vs `<context : component-scan>`
```
<context : annotation-config />
<context : component-scan />
```
두 가지는 유사하면서도 차이점이 존재한다. 둘 다 application-context에 정의해서 사용할 수 있는데 헷갈리던 부분이 있어 명확하게 다시 정리해보고자 한다.


### `<context : annotation-config />`
이미 등록된 bean에 대해서만 Annotation을 활성화한다.
어딘가에 bean을 등록해놓으면 `@Autowired`와 `@Qualifier` 등의 Annotation을 해석해서 가져다 쓰겠다는 의미이다.

따라서 위 태그를 사용하더라도 xml이나 `@Configuration` 클래스에 bean을 반드시 선언해야 한다.

### `<context : component-scan/>`
bean의 등록 여부와 관계없다. 스프링이 알아서 bean 스캔을 통해 Annotation을 해석하고 활성화한다.
`@Autowired`, `@Qualifier`, `@PostConstruct`, `@PreDestroy` 뿐만 아니라 `@Service`, `@Component`, `@Controller`, `@Repository` 등 스테레오 타입도 스캔하고 bean을 작성한다.

따라서 이 태그를 사용하면 `<context : annotation-config />` 태그는 사용할 필요가 없다.

다만 이 경우 base-package를 통해 스프링이 스캔할 패키지 위치를 지정해두는 것이 일반적이다.
`<context : component-scan base-package="com.sample"/>`

출처: https://triest.tistory.com/42

**Comment by JasonYoo1995** [comment]
## 셧다운 후크
(내용 준비 중 - 내일 모임 때 자세히 설명 예정)

**Comment by binchoo** [comment]
※ `ApplicationContext` 의 부모 인터페이스인 `BeanFactory`와 헷갈리지 않게 주의.

## 팩토리 빈

### 유스 케이스
- 협력 객체를 생성하는 API가 단순히 `new`가 아닐 때
  - [스태틱 팩토리 패턴 (Effective Java 아이템1)](https://honbabzone.com/java/effective-java-static-factory-method/)을 사용하는 클래스
  - [팩토리 패턴](https://github.com/caffeine-library/pro-spring-5/issues/4#issuecomment-877691410) 클래스

### 팩토리 빈 vs. `@Configuration`
> FactoryBean의 역할은 더 많은 애플리케이션 클래스들을 IoC의 설정 방식으로 사용할 수 있도록 하는 인프라를 지원하는 것입니다.

- 팩토리 빈은, new로 생성하지 않는 빈에 유용한 팩토리이며 그 자체로 빈이다.
  - 프레임워크가 빈 생성 책임을 팩토리 빈에 위임하는 모양새가 된다.
  - 따라서 팩토리 빈 구현체는 프레임워크의 요구사항에 결합한다.


- `@Configuration` 역시 new로 생성하지 않는 협력 객체의 생성에 대응할 수 있다.
  - 이미 써드 파티 빈을 만들 때 유용한 방법 중 하나로 거론되었다. 
  - #16

#### 그럼 `@Configuration`을 쓰는 게 낫지 않을까요?

- 유스 케이스 1번의 경우 확실히 `@Configuration`이 단순합니다. `FactoryBean` 라는 어댑터 계층을 스프링과 협력 객체 사이에 끼워 넣는 행위에 의구심이 듭니다. 물론 XML만 있던 시대에서는 팩토리 빈이 유일한 선택지였겠지요 😢 
지금은 자바 구성이라는 도구가 있는 이상, 협력 객체의 생성 API를 캡슐화할 이유가 없어 보여요.
```java
@Configuration
class ConfigClass {

    @Bean public MessageDigest shaDigest() {
        return MessageDigest.getInstance("SHA1");
    }

    @Bean public  MessageDigest defaultDigest() {
        return MessageDigest.getInstance("MD5");
    }
}
```

- 유스케이스 2번의 경우, XML에 `factory-bean`, `factory-method` 속성을 정의하면 레가시 팩토리에게서 빈을 얻을 수 있습니다.  특별히 `FactoryBean` 인터페이스를 구현할 필요도 없으니 이런 상황이라면 팩터리 빈 패턴을 사용해도 괜찮겠네요.

```xml
<bean id="shaDigestFactory" 
    class="com.apress.prospring5.ch4.MessageDigestFactory"
    p:algorithmName="SHA1"/>

<bean id="shaDigest"
    factory-bean="shaDigestFactory"
    factory-method="createInstance">
</bean>
```

물론 자바 구성 방식도 여전히 이 케이스를 커버해 줍니다.
```java
@Configuration
class ConfigClassWithLegacyFactoryu {

    @Bean
    public MessageDigestFactory shaDigestFactory() {
        MessageDigestFactory factory = new MessageDigestFactory();
        factory.setAlgorithmName("MD5");
        return factory;
    }

    @Bean
    public MessageDigest shaDigest() {
        return shaDigestFactory().createInstance();
    }
}
```

**Comment by emiling** [comment]
### BeanNameAware

> [p.235] 빈에 내부적으로 사용할 이름을 부여해야 한다면, 애플리케이션 내에 setName() 메서드를 가진 Nameable과 같은 인터페이스를 만들고 이 인터페이스를 빈에서 구현한 후에 빈 이름을 의존성 주입으로 전달합니다.

책에서 `BeanNameAware` 인터페이스를 통해 비즈니스적인 의미를 부여하면 안 된다고 하므로 이를 방지하기 위해 위와 같은 방법을 사용할 것을 권장했는데요. 이에 대한 예시를 자바 구성 파일로 들어보았습니다.

```java

public interface Nameable {
    void setBeanName(String name);
    void sing();
}

public class NameableSinger implements Nameable {
    private String beanName;

    @Override
    public void setBeanName(String name) {
        this.beanName = name;
    }

    @Override
    public void sing() {
        System.out.println("Singer [" + beanName + "] - sing()");
    }
}
```
- Configuration
```java

@ComponentScan
@Configuration
public class NameConfiguration {

    @Bean
    public Nameable nameableLoanMayer(){
        Nameable singer = new NameableSinger();
        singer.setBeanName("nameableLoanMayer");
        return singer;
    }

    @Bean
    public NamedSinger lohnMayer(){
        return new NamedSinger();
    }
}
```

- Main

```java
public class NamedSingerDemo {
    public static void main(String... args) {
        AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext(NameConfiguration.class);
        NamedSinger bean = (NamedSinger) ctx.getBean("lohnMayer");
        bean.sing(); // Singer [lohnMayer] - sing()

        Nameable nameableBean = (Nameable) ctx.getBean("nameableLoanMayer") ;
        nameableBean.sing();
        ctx.close(); // Singer [nameableLoanMayer] - sing()
    }
}
```

**Comment by emiling** [comment]
### ApplicationContextAware 인터페이스를 통한 context 참조 얻기

```java
GenericXmlApplicationContext ctx = new GenericXmlApplicationContext();
ctx.load("classpath:spring/app-context-annotation.xml");
ctx.refresh(); 
```
XML 기반의 ApplicationContext를 로딩 후 `ctx.refresh()`에서 
언제 `setApplicationContext`가 호출되는지 궁금하여 가볍게만 찾아보았습니다.

`AbstractAutowireCapableBeanFactory`의 `initializeBean`에서 호출을 시작으로 
아래 코드의 `invokeAwareInterfaces` 함수에서 invoke 하고 있는 것을 알 수 있습니다.

![Screen Shot 2021-08-01 at 3 05 40 PM](https://user-images.githubusercontent.com/30731518/127761124-45b6c5ed-47dc-4994-9e8c-4fae3d5e58e2.png)

```java
// simplified version
Class<?> beanClass = beanDefinition.getClass();
Object bean = beanClass.newInstance();
if (bean instanceof ApplicationContextAware) {
    ((ApplicationContextAware) bean).setApplicationContext(ctx);
}
```

**출처**
https://stackoverflow.com/questions/21553120/how-does-applicationcontextaware-work-in-spring
