### ISSUE TITLE
[question] static 메서드를 초기화 메서드로 사용하면, 해당 메커니즘의 장점이 사라집니다?

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/pro-spring-5#28]
## 질문
"static 메서드를 초기화 메서드로 사용하면, 초기화 메서드 메커니즘의 장점이 사라진다"
이 내용을 한 번에 이해하기 어려워 좀 더 고민해 보는 시간 갖고자 합니다.

## 상세 내용
책에서 이 주장을 부연 설명하는 내용이, 번역의 문제인 것인지 한 번 읽고는 무슨 소리인지 와닿지 않네요.
관련 철학이나 예제 코드를 연구해 봐야 할 것 같습니다.

부연된 주장
1. 정적 초기화 메서드는 검증 작업을 위해 각 빈의 상태 정보에 접근할 수 없다. 
2. 메모리를 아끼려는 거면 정적 상태 정보를 인스턴트 상태 정보로 옮기고 비정적 초기화 메서드를 써라 > 싱글턴 관리 기능을 쓰면 동일한 결과를 얻을 수 있다 & 테스트도 더 쉬워진다.

## 연관 챕터
#25 챕터 4.3.1 [예제 4-3] 설명의 마지막 문단.

## 참고 (영어 원문)
> The benefits of this mechanism are negated when using a static initialization method, because you
cannot access any of the bean’s state to validate it. If your bean is using static state as a mechanism for saving
memory and you are using a static initialization method to validate this state, then you should consider
moving the static state to instance state and using a nonstatic initialization method. If you use Spring’s
singleton management capabilities, the end effect is the same, but you have a bean that is much simpler to
test, and you also have the increased effect of being able to create multiple instances of the bean with their
own state when necessary. Of course, in some instances, you need to use static state shared across multiple
instances of a bean, in which case you can always use a static initialization method.

cc. @caffeine-library/readers-pro-spring-5

**Comment by binchoo** [comment]
### 정적인 State
`static` 멤버. 이 클래스의 인스턴스들은 정적인 상태를 공유하게 됨.
```java
class WithStaticState {
  private static String nonStaticState1;
  private static String nonStaticState2;
  ...
}
```

### 비정적인 State
`static`이 아닌 멤버. 인스턴스마다 달리 값을 가질 수 있음
```java
class WithNonStaticState {
  private String state1;
  private String state2;
  ...
}
```

### 핵심 내용
  - init 메서드는 빈이 제대로 구성되었는지 확인하는 좋은 방법이다. (초기화 메서드의 장점)
  - **init 메서드는 인자를 받지 않는다.** 

#### 정적 메서드는 비정적인 state를 확인할 수 없다.
  - `static` 메서드는 `non-static` 필드에 접근할 수 없다.
  -  init 메서드는 인자가 없으니, 지금 생성된 빈에 대한 참조도 얻을 수 없다.
  - 따라서 getter와 setter로 빈의 상태를 조작하면 되는 것 아닌가? 하는 생각은.. 불가능한 것이었다.
  ```java
  class WithNonStaticState {
      private String state1;
      private String state2;
      public static void init() {
        //bean의 필드에 접근할 수 없어서 아무런 상태 검증을 할 수가 없다.
      }
  }
  ```

  하지만 `non-static` 필드에 대한 검증은 정적인 init 메서드에 맡겨도 좋다.
  ```java
  class WithStaticState {
    private static String nonStaticState1;
    private static String nonStaticState2;
    public static void init() {
        if (!StringUtils.isAllUpperCase(nonStaticState1))
          throw new RuntimeException("nonStaticState1은 영어 대문자여야 합니다.");
    }
  }
  ```

  그런데 이 방법은 스프링이 제공하는 `싱글턴 관리 기능`으로 대체할 수 있다.
  --> 싱글턴 관리 기능이 무엇인지 조사 필요

**Comment by emiling** [comment]
책(p.213)에 따르면 초기화 메서드의 경우 **제대로 빈이 구성되었는지 확인하는 방법** 으로 사용하고 있습니다.

위에서 말씀하셨듯 **non-static 멤버 변수** 상태를 검증하는 초기화 메서드를 **static 메서드**로 선언하게 되면

![Screen Shot 2021-08-01 at 11 34 36 AM](https://user-images.githubusercontent.com/30731518/127757276-a25d78e4-4ca2-44e2-baf2-a3947387f907.png)

static 메서드에서는 non-static 멤버 변수에 접근할 수 없으므로 제대로 빈이 구성되었는지 그 상태를 확인하는 것이 불가능합니다.

> static 메서드의 경우 런타임이 아닌 클래스 로딩 때 한 번 메모리(method area, JAVA8 부터는 heap area)에 올라가기 때문에 그 static 메서드가 로딩될 때는 비 static 멤버 변수가 아직 인스턴스화 되기 이전, 즉 런타임 이전이기 때문에 접근할 수 없다.

그렇다고 static 상태 정보를 사용하고 해당 상태 정보를 검증하려고 초기화 메서드에 static 메서드를 사용한다면 **이전에 생성된 bean에 상태에 영향을 받을 수 있습니다** (왜 그럴지 간단히 생각해보고 진짜 그런지는 스터디 때 보도록 하겠습니다)

static 멤버 변수를 사용하게 되면 
영향을 받으면 안 되는 각각의 빈 상태가 이전에 생성된 빈의 상태에 영향을 받을 수 있기 때문에 
코드 작성자가 의도한 대로 해당 빈이 제대로 구성되지 않을 수 있습니다.

즉, static 초기화 메서드를 사용하면 

- non-static 멤버 변수에 접근할 수 없음
- static 멤버 변수 상태가 제대로 구성되지 않을 수 있음

둘 중 하나의 상황이 발생하므로 어느 쪽도 제대로 빈이 구성되었는지 확인하기 어렵기 때문에 
해당 메커니즘의 장점이 사라진다고 생각합니다.

**참고**
https://stackoverflow.com/questions/8387989/where-are-static-methods-and-static-variables-stored-in-java
