### ISSUE TITLE
[keyword] 4장 스프링 구성 상세와 스프링 부트(2) 키워드 정리

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#30]
## 주제
[4장] 스프링 구성 상세와 스프링 부트(2)을 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요

## 연관챕터
#29

**Comment by binchoo** [comment]
## IntelliJ에서 프로퍼티 파일 한글 보이도록 설정

책에서는 국제화 프로퍼티 파일에서 한글을 표시하는 이클립스 플러그인을 설명해 주었는데요.
본인은 IntelliJ를 사용하고 있으므로 관련 설정법 공유합니다.

- Settings> Editor> File Encodings> Properties Files: `ISO-8859-1` V `Transparent native-to-ascii conversion`
  ![image](https://user-images.githubusercontent.com/15683098/128600978-78fc3e96-f59d-4d95-9190-9c704e7dfbde.png)

  ![image](https://user-images.githubusercontent.com/15683098/128601017-5419f3c3-3ef1-4745-80b5-6beeb220b8d6.png)

**Comment by JasonYoo1995** [comment]
# 4.8
## 국제화
## 이벤트 전달
# 4.9
## 리소스 접근
# 4.10
## 자바 구성 클래스
# 4.11
## 프로파일
# 4.12
## Environment 인터페이스
# 4.13
## JSR-330 애너테이션
# 4.14
## 그루비
# 4.15
## 스프링 부트

**Comment by binchoo** [comment]
## 옵저버 패턴과 발행/구독 패턴

![image](https://user-images.githubusercontent.com/15683098/128616503-d8c17639-9140-482d-92f3-15c3a9952603.png)
출처 - https://jistol.github.io/software%20engineering/2018/04/11/observer-pubsub-pattern/

### 옵저버 패턴
`Observer`가 `Subject`에게 `subscribe` 메시지를 명시적으로 보내어 자신을 인지시킵니다. 
`Subject`는 이벤트를 발생시 등록된 `Observer`들에게 메시지를 보냅니다.

### 발행/구독 패턴
중간에 `EventChannel` 레이어를 놓습니다. `Subscriber`는 `EventChannel`에 자신이 특정 이벤트를 수신한다고 인지시킵니다.
`Publisher`는 `EventChannel`에 메시지를 보내어 이벤트를 발행합니다.
`EventChannel`은 해당 이벤트 수신자로 등록된 `Subscriber`에게 메시지를 보냅니다.

`Publisher`와 `Subscriber`가 직접 결합하지 않는 장점이 있습니다.

### ApplicationContext에서 발행/구독 패턴
![image](https://user-images.githubusercontent.com/15683098/128616936-4911f655-a0b3-4ae9-a8dd-7710cadc1976.png)

### 각 방법의 특징
- 옵저버 패턴은 동일 도메인 내에서, Synchronous한 이벤트 처리 추구
- 발행/구독 패턴은 두 컴포넌트가 다른 도메인에 있을 수 있으며, Asynchronous한 이벤트 처리 추구

#### 옵저버 패턴 적용 안 좋은 예

모델 값 변경으로 뷰 모양을 변경할 때
- Worker Thread와 UI Thread는 분리되는 것이 원칙이므로
- Thread 분리가 강제되는 환경에서 아래 코드는 동작하지 않을 수 있다.

  ![image](https://user-images.githubusercontent.com/15683098/128616706-a74f3103-031f-432c-a1d3-87471374adf3.png)
  ![image](https://user-images.githubusercontent.com/15683098/128616775-009280e6-2893-4523-bcca-b4bb8b20f351.png)

#### 개선하기: 비동기적 이벤트 처리
Qt의 시그널 - 슬롯 개념
시그널 - 발행자, 이벤트를 발행
슬롯 - 구독자, 이벤트를 수신하여 비동기 처리하는 함수
![image](https://user-images.githubusercontent.com/15683098/128617045-e88e10fe-36d6-4332-a3fb-5820321ca923.png)

**Comment by emiling** [comment]
### ApplicationContext에서 MessageSource 초기화

> ApplicationContext 인터페이스가 MessageSource를 상속해 메시지를 읽어들이고 애플리케이션 환경에서 읽어들인 메시지에 자동으로 접근하는 특수한 기능을 제공하기 때문입니다



### 참고

-  IntelliJ에서 프로파일 설정 

`Run > Edit Configurations...` 에서 다음과 같이 `-Dspring.profiles.active=...` 추가

![Screen Shot 2021-08-07 at 1 10 50 AM](https://user-images.githubusercontent.com/30731518/128622994-4d1bbb45-a537-4a31-977d-ea6050a9bb34.png)
