### ISSUE TITLE
[question] 선언적인 방식(declarative way)

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/pro-spring-5#31]
## 질문
4.8에 다음와 같은 내용이 있습니다.

> ApplicationContext를 사용할 때의 가장 큰 장점은 스프링과 스프링이 관리하는 리소스를 100% 선언적인 방식(declarative way)으로 구성하고 관리할 수 있다는 것입니다.

여기서 말하는 **선언적인 방식**은 무엇을 말하는 걸까요?

## 연관 챕터
#29

cc. @caffeine-library/readers-pro-spring-5

**Comment by wooyounggggg** [comment]
관련해서 검색해봤는데 `자바스크립트` 설명밖에 없어서 자바스크립트 문법으로 남깁니다.

```javascript
/* 명령형 프로그래밍 */
var string = 'This is the midday show with Cheryl Waters';
var urlFriendly = "";

for(var i=0; i<string.length; i++){
    if(string[i] === " "){
        urlFriendly += "-";
    }else{
        urlFriendly += string[i];
    }
}

console.log(urlFriendly);
```

```javascript
/* 선언형 프로그래밍 */
const string = 'This is the midday show with Cheryl Waters';
const urlFriendly = string.replace(/ /g, '-');

console.log(urlFriendly);
```

위의 코드는 둘 다 동일한 일을 하는 코드들이지만, `명령형 프로그래밍`을 한 코드는 코드의 로직이 펼쳐져 있고,

`선언형 프로그래밍`을 한 코드는 로직을 모듈화해두고 사용하는 형태라 무슨 일을 하는 코드인지 명확하게 추론할 수 있습니다.

우리가 `ApplicationContext` 없이 리소스를 선언적 형태로 구성/관리하려고 한다면,  리소스 관리 로직을 정의하는 클래스 및 

메서드를 정의하고 관리하는 역할을 지속적으로 해주어야 하기 때문에 꽤 번거로운 작업이 될 수 있습니다.

반면 Spring은 `ApplicationContext`를 통해 리소스 관리에 대한 API를 미리 `선언`해두고, 개발자는 선언되어 있는 API들을

자신이 필요한 문맥 내에 가져다 붙이는 형태로 사용할 수 있기 때문에 훨씬 깔끔한 스타일로 개발을 진행할 수 있다는 측면을

얘기 하고 있는 것 같네요 😃 

읽어보면 좋은 글: [명령형 프로그래밍 vs 선언형 프로그래밍](https://boxfoxs.tistory.com/430)

출처: [명령형-프로그래밍과-선언적-프로그래밍-비교](https://velog.io/@hyun_sang/%EB%AA%85%EB%A0%B9%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EA%B3%BC-%EC%84%A0%EC%96%B8%EC%A0%81-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%EB%B9%84%EA%B5%90)
