### ISSUE TITLE
[question] 부모 프로젝트 / 자식 프로젝트

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/pro-spring-5#32]
## 질문
부모 프로젝트와 자식 프로젝트는 무엇인가요?

## 연관 챕터
#29 

cc. @caffeine-library/readers-pro-spring-5

**Comment by JasonYoo1995** [comment]
내용 준비 중

**Comment by JasonYoo1995** [comment]
### maven의 pom.xml / gradle의 build.gradle
[참고](https://junghn.tistory.com/entry/SPRING-Maven%EC%84%A4%EC%A0%95-%ED%8C%8C%EC%9D%BC-pomxml-%EC%9D%98-%EC%9D%B4%ED%95%B4)
프로젝트의 구조와 내용을 설명하며, 프로젝트 관리 및 빌드에 필요한 환경 설정, 의존성 관리 등의 정보들을 기술합니다. 

### gradle 기본 사용법
[참고](https://velog.io/@france1988/Gradle-%EA%B8%B0%EB%B3%B8%EC%82%AC%EC%9A%A9%EB%B2%95)

### 부모 프로젝트 + 자식 프로젝트 연결 방법
[참고](https://oingdaddy.tistory.com/298)
- 프로젝트 2개를 생성한다
- 자식 프로젝트의 pom.xml에서 <parent> 태그를 사용해 부모 프로젝트와 연결한다.

### 부모 프로젝트와 자식 프로젝트 간의 관계
[참고](https://www.aceproject.com/help/whats-the-difference-between-parent-and-child-projects/)
- 부모 프로젝트의 structure가 자식 프로젝트의 structure에 대한 template 역할을 한다.
- structure의 내용
  - Task group, Task type, Task status, Task priority values 
  - Common data : 개발자 이름, SCM 주소, 배포 관리 등
  - 상수 : 버전 번호 등
  - 의존성 : 자식들이 공통적으로 가지는 의존성들
  - 속성 : plugin, declaration, execution, ID 등
  - 리소스
  - Configuration
- 부모 프로젝트의 structure가 바뀌면, 해당 변경 사항이 모든 자식 프로젝트에 적용된다.
- 하나의 부모 프로젝트는 여러 개의 자식 프로젝트를 가질 수 있다.
- 자식 프로젝트만이 가지는 내용들은 자식 프로젝트에만 선언한다.

### 부모 프로젝트와 자식 프로젝트의 특징
[참고](https://howtodoinjava.com/maven/maven-parent-child-pom-example/)
- pom.xml을 상속함으로써 configuration들에 대한 불필요한 중복과 복제를 피할 수 있다.
- 장기적인 관점에서 프로젝트에 대한 유지 보수를 용이하게 해준다.
- 부모 프로젝트와 자식 프로젝트에 동시에 명시된 의존성이나 속성들은 자식 프로젝트에 명시된 값이 우선순위를 가진다.

**Comment by emiling** [comment]
이러한 부모-자식 프로젝트의 관계를 잘 활용하고 있는 것이 **멀티 모듈** 프로젝트라고 생각합니다.

대부분의 서비스는 단일 프로젝트로 구성되는 일이 많지 않고,
적어도 사용자와의 접점을 담당하는 모듈과 DB와의 접점을 담당하는 모듈로 구분하여 구성하게 됩니다.
그 밖에도 외부 API를 연동해야하는 모듈 혹은 배치성 작업을 처리하기 위한 모듈 등등이 따로 존재할 수 있습니다.

이렇게 될 경우 각각의 모듈에서 **공통적으로 사용되는 클래스**들은 어떻게 다뤄야 할지에 대한 고민이 발생하게 됩니다.
그에 따라 루트 패키지 하위로 기능에 따라 모듈을 분리하여 멀티 모듈 형태로 프로젝트를 구성하는 경우가 많아지고 있습니다.

주로 도메인과 어플리케이션, 유틸성 클래스와 같이 크게는 공통 기능 모듈 세 개로 나뉘는 것부터 시작해 
비지니스 요구사항에 따라 더 세부적인 모듈로 나뉘는 것 같습니다.

**참고 링크**
- https://jojoldu.tistory.com/123
- https://techblog.woowahan.com/2637/

**Comment by wooyounggggg** [comment]
코멘트 읽으면서 비슷하게 생각나는 주제가 있어서 이 부분도 같이 알아보면 좋을 것 같습니다

- `WAS 서버`와 `WEB 서버`의 차이는 무엇이고, 이것을 왜 나누나요?
