### ISSUE TITLE
[question] 컴파일 타임 VS 로드 타임 VS 런타임 구분에 대해 명확히 알고 싶습니다

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#34]
## 질문
컴파일 타임 VS 로드 타임 VS 런타임 구분에 대해 명확히 

## 상세 내용
스터디에서 얘기를 하다보면 컴파일 타임과, 로드 타임 그리고 런타임에 대한 얘기가 많이 나오는데요
이 세 과정에 대한 명확한 구분과 시점을 알아볼 필요가 있습니다.

## 연관 챕터(이슈)
#8 #24 

## 참고

이를 알기 위해선 결국 JVM 동작 과정에 대한 이해가 선행되어야 할 듯 합니다.

**Comment by JasonYoo1995** [comment]
참고 : https://joomn11.tistory.com/13

**Comment by binchoo** [comment]
## 머릿말
컴파일, 클래스 파일 로드, 바이트 코드 실행에 대한 개념을 이해하려면
자바 가상 머신에 대한 공부가 필요한 것 같아서
서적 [Inside the Java Virtual Machine](https://github.com/shshankar1/ebooks/blob/master/Inside-Java-Virtual-Machine.pdf)의Introduction(챕터1)과 JVM(챕터5) 내용을 정리해 보고 있습니다.

1997년에 작성된 Java2에 관한 내용이므로 어느 정도 deprecated 된 내용도 있을 거라 생각하지만, JVM 명세를 풀어 쓴 책으로 이 책만 발견하여 읽어보고 있습니다. (저 AOP 관련 논의는 이번 주에 참여가 어려울 것 같네요.)

# **Java 아키텍처**

`Java` 란, 프로그래밍 언어만을 의미하지 않는다.

- 프로그래밍 언어로서
- 자바 가상 머신
- 자바 API
- 자바 클래스 파일

이것들이 함께 자바가 제공하는 모든 일들을 동작하게 한다. 우리는 자바 아키텍처가 각 구성요소를 어떻게 결합해 어떤 큰 그림을 갖고 있는지 살펴 보아야 한다. (클래스 파일, API, 언어)

## **자바라는 툴**

자바는 **네트워킹 환경**에 적합한 도구로 설계되었다. 자바 아키텍처는 보안, 강건한, 플랫폼 독립인 프로그램을 작성하도록 한다. 이 프로그램은 네트워크를 통해 배포되어 매우 다양한 환경에서 실행된다.

## **자바 아키텍처**

4가지 기술로 구성된다.

- 자바 **프로그래밍 언어**
- 자바 **클래스 파일** 포맷
- 자바 **API**
- 자바 **가상 머신**

프로그래머는 자바 언어로 소스를 작성하고, 이것을 자바 클래스 파일로 컴파일한다. 클래스 파일들은 JVM 위에서 실행된다. 해당 프로그램은 다분히 시스템 리소스가 필요하여 I/O 연산을 할 수도 있는데, 프로그래머는 자바 API를 구현한 클래스들의 메서드를 호출 코드를 작성할 것이다. 그럼 프로그램이 실행되면, 해당 API를 구현한 클래스 파일의 메서드를 호출하게 된다.

### **자바 프로그래밍 환경**

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/1ee8a06f-fb15-470f-8782-1f99046b5bff/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/1ee8a06f-fb15-470f-8782-1f99046b5bff/Untitled.png)

### **자바 플랫폼**

한 편, **자바 가상 머신**과 **자바 API**는 자바 프로그램이 실행될 "플랫폼"을 제공하므로, 두 기술을 묶어서 **자바 플랫폼**이라 부른다.  특정 기기 환경을 지원하는 자바 플랫폼만 있다면, 자바 프로그램은 실행 가능하다.

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/be099512-e0f3-47f4-bdfc-d9ef2c381bc7/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/be099512-e0f3-47f4-bdfc-d9ef2c381bc7/Untitled.png)

## **자바 가상 머신**

추상 컴퓨터이다. JVM은 명세가 존재하지만 구현 방법은 매우 Optional 하다.

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a3693b12-ee18-43c8-8a8b-eaad8861691f/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a3693b12-ee18-43c8-8a8b-eaad8861691f/Untitled.png)

### **기능**

1. **Class Loader**: 클래스 파일을 읽어들인다. 실행하는 프로그램의 클래스 파일과, 이 프로그램이 필요로 하는 자바 API의 클래스 파일을 로딩해야 한다. 모든 JAVA API 클래스를 불러오지 않아도 된다.
2. **Execution Engine**: 클래스 파일의 바이트 코드를 실행한다. 구현체에 따라 동작 방식이 다양하다.
    - 소프트웨어
        - 단순한 인터프리팅 방식: 바이트코드를 하나 씩 해석하여 수행하기
        - Just-in-time 컴파일러: 메서드의 첫 호출 때 메서드의 바이트코드를 종속 기계 언어로 컴파일하고 메모리에 캐싱하여 사용하는 방식. 실행 속도가 빠르지만 메모리를 더 요구함.
    - 하드웨어

        자바 바이트코드를 네이티브 언어로 사용. 보통 임베디드 칩 내부에 Execution Engine을 내장한다.

> **JVM을 자바 인터프리터로서 인식하는 것은 옳지 않다.**
'자바 인터프리터'란 용어는, 실행 엔진 구현체가 바이트코드 해석 방식을 채용할 때는 적당하다만, 어떤 JVM들은 JIT컴파일랑 같은 기술을 채용하고 있다. 모든 자바 인터프리터는 JVM이지만, 모든 JVM은 자바 인터프리터가 아니다.

### **호스트 OS와의 작용**

자바의 메서드는 2가지이다.

- 자바 메서드: 자바 언어로 작성된 메서드이다. 바이트코드로 컴파일 후 클래스 파일에 저장된다.
- 네이티브 메서드: C, C++, 어셈블리 같은 타 언어로 작성된 메서드이다. 종속 기계 언어로 컴파일 되어있고 DLL 같은 동적 링크 라이브러리에 저장된다. 그 형태는 플랫폼마다 다르다.

호스트 OS에서 동작하는 소프트웨어 JVM에서 프로그램을 실행할 때, 호스트 OS의 네이티브 메서드를 사용할 수도 있다. 자바 메서드는 플랫폼 독립이지만, 네이티브 메서드는 당연히 아니다.

자바 프로그램에서 네이티브 메서드를 호출하려면, JVM에 해당 네이티브 메서드를 지닌 동적 라이브러리를 적재한 뒤 메서드를 호출한다. 네이티브 메서드들은 자바 프로그램과 호스트 OS 간의 연결선이다.

### **JNI; Java Native Interface**

네이티브 메서드 호출은  프로그램이 직접적으로 호스트 시스템 자원을 활용하도록 하지만, 이들을 사용하면 플랫폼 독립을 해치게 된다. 동적 라이브러리는 플랫폼 종속이기 때문이다.

자바 네이티브 인터페이스(JNI)는 해당 호스트 위에서 돌아가는 모든 자바 플랫폼에서 네이티브 메서드를 사용하게 해 준다. 자바 플랫폼 벤더들은 반드시 JNI를 지원할 필요는 없으며, "그들만의 JNI"를 제공하기도 한다.

자바는 항상 선택지를 제공한다. 자바 API만으로 도달할 수 없는 호스트의 자원에 접근해야 한다면, 특정 호스트에 의존하는 네이티브 메서드를 사용해야 한다. 하지만 프로그램을 플랫폼 독립으로 유지해야 한다면 프로그램은 오직 자바 API를 사용하여야 한다.

## **클래스 로더**

클래스 로더는 자바의 3가지 특징: 플랫폼 독립, 보안, 네트워크 이동성 중 뒤에 2가지를 커버하는 내용이다.

위에서 본 다이어그램에서 `ClassLoader`는 하나의 블록으로 표현되었으나, 실제 JVM에서 사용하는 클래스 로더는 여럿이 될 수 있다. 이 노테이션은 `ClassLoader` 서브시스템을 표현한다고 생각하자.

### **유형**

클래스 로더는 2가지 유형으로 나눈다.

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/821f3de4-3635-419c-99e4-fa814e5471ba/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/821f3de4-3635-419c-99e4-fa814e5471ba/Untitled.png)

- 원시 클래스 로더 (Primodial Class Loader)

    원시 클래스 로더는 JVM 구현체의 일부이다. JVM이 C 구현체라면 원시 클래스로더는 해당 C 프로그램의 일부이다. 원시 클래스 로더가 적재하는 클래스는 `trusted` 로 인식된다. 보통 자바 API 클래스를 로컬 디스크에서 적재한다.

- 클래스 로더 객체 (Class Loader Objects)

    자바 응용은 실행 시간에 클래스 로더 객체를 사용해서 커스텀 방식으로 클래스들을 적재할 수 있다. ex) 네트워크에서 클래스 파일을 다운로드 후 적재하기. JVM은 클래스 로더 객체가 적재하는 객체를 `untrusted`로 본다.

원시 클래스 로더는 JVM 구현에 내장된 구성요소인 반면에, 클래스 로더 객체는 자바 언어로 작성되어, 클래스 파일로 컴파일되고, VM에 적재되어 객체로 인스턴스화 되는 요소이다. 이들은 자바 응용 실행 코드의 구성요소라고 할 수 있겠다.   

### 동작

클래스 로더가 클래스를 로드하면 JVM은 이 클래스를 어떤 로더가 적재했는지 기억한다(원시 클래스 로더건, 클래스 로더 객체이건). 적재된 클래스에서 다른 클래스를 처음 참조할 때, JVM은 동일한 클래스 로더가 참조된 클래스를 적재하도록 하고 있다. 

예를 들어, `Volcano` —> `Lava` 라고 하자. 

특정 클래스 로더가 `Volcano`  클래스 적재했다면, JVM은 다시 동일한 클래스 로더에게  `Lava` 를 적재하도록 요청한다. 이렇게 적재된 `Lava` 는 `Volcano`와 동적으로 링크된다.

- 이런 동작 때문에, 기본적으로 한 클래스는 동일한 클래스 로더가 적재한 타 클래스만 볼 수 있다.
- 그렇기 때문에, 하나의 자바 응용에서 다양한 종류의 클래스 로더를 사용하면, 그들은 자신만의 네임스페이스를 형성한다.

### 클래스 분리와 보안 (자바 애플릿)

자바 응용은 여러 가지 클래스 로더 객체를 사용할 수 있다. 각 로더가 적재한 클래스들은 서로만 볼 수 있기 때문에 클래스 로더 하나는 네임스페이스로서 작용하게 된다.

이 구조는 클래스들을 서로 다른 원천에서 구해와 사용하는 케이스일 때 적용해 볼 수 있다.

웹 브라우저에서 실행되는 자바 응용은 `애플릿 클래스 로더` 를 사용하여 HTTP 프로토콜로 클래스 파일을 얻어 온다. 자바 응용이 실행할 애플릿은 브라우저 페이지 로딩 시에 동적으로 결정되는 사항이다. 

자바 응용은 클래스 파일을 가져오는 원천에 따라 `애플릿 클래스 로더` 객체를 따로 생성하여 사용하는데, 그 결과 서로 다른 원천에서 가져온 클래스들은 서로 구분되므로 악의적인 애플릿이 다른 애플릿을 침해하는 행위를 방지한다. (보안)

한 편, 클래스 로더 객체에게 네트워크 통신으로 클래스 파일 적재 기능을 구현시킬 수 있기 때문에, 자바의 네트워크 이동성 특징을 지원하게 해 준다. (네트워크 이동성)

## 클래스 파일

자바 클래스 파일은 `플랫폼 독립`과 `네트워크 이동성`에 관련있다. 자바 클래스 파일은 어떤 하드웨어와 OS라도 JVM만 있으면 실행 가능한 바이너라 파일이다. 한편, 클래스 파일은 압축되도록 설계되어 네트워크 상에서의 이동이 용이하고, 자바 응용의 동적 링크와 동적 확장을 지원해준다. 

## 자바 API

자바 API는 `플랫폼 독립`과 `보안`에 관련있다. 자바 런타임 라이브러리는 시스템 리소스 접근을 위한 표준화된 방법을 제공한다. 모든 자바 플랫폼 구현에 자바 API 클래스 파일은 필수 컴포넌트로 요구된다. 따라서 자신의 자바 클래스가 자바 API를 참조한다면, JVM이 자바 API 클래스 파일들을 적재할 수 있다. 최종적으로 클래스 파일(자신의 클래스 + 자바 API 클래스) + 동적 라이브러리(네이티브 메서드)들이 함께 적재되어 프로그램의 실행을 지원한다. 

소프트웨어 JVM의 자바 API는 내부적으로 호스트 OS의 네이티브 메서드를 사용하게 된다. 프로그래머는 네이티브 메서드를 사용하지 않고, 자바 API를 사용하여 호스트 자원에 접근하면 된다. 

자바 API 메서드는 실행 전에 `Security Manager` 에게서 권한을 체크 받는다. `Security Manager`는 자바 응용이 커스텀 보안 정책을 정의하는 기능을 제공한다. 

## 아키텍처 트레이드 오프

자바 응용은 동적 링크를 사용하므로, 한 클래스 파일에서 다른 클래스 파일로의 참조 표현은 심볼릭이다.  정적 링크된 응용에서는 클래스 간 참조가 포인터 혹은 오프셋으로 표현된다. 

자바 클래스 파일을 보면, 

- 클래스에 대한 참조:  클래스 이름의 문자열로 표현.
- 필드에 대한 참조: 필드의 이름과 `descriptor` (필드 타입)으로 표현
- 메소드에 대한 참조: 그 메서드의 이름과 `descriptor` (반환 타입, 인자의 수, 인자의 타입)으로 표현.

이런 심볼릭 참조는 타 클래스 것을 표현할 때 뿐만아니라, 본인 클래스의 필드와 메서드에도 적용된다. 

바이트 코드에 심볼릭하게 풍부한 정보가 표현되기 때문에 리버스 엔지니어링이 용이하여 알고리즘 절취도 쉽다. 이를 방지하기 위한 수단으로서 클래스를 `obfuscate` 하는 방법이 있다. 심볼을 의미론적으로 무관하게 치환하여 해석을 어렵게 하는 기법이다.


JVM은 명세에서 추상적으로 정의된 기계이다. 자바 프로그램을 실행하려면 JVM 명세의 구현체가 필요하다. 우선 JVM의 명세에 대해 공부하고 대응하는 구현 방식을 논의해보자.

## JVM이 지칭하는 것

- 추상 **명세**: JVM 명세서에서 기술되는 컨셉
- **구현체**: 자바 플랫폼 벤더가 제작하는 JVM 명세 구현체. SW 혹은 HW 구현이 될 수 있다.
- 런타임 **인스턴스**: 자바 응용을 실행하는 런타임 인스턴스. 각 자바 응용은 하나의 JVM 런타임 인스턴스 위에서 돌아간다.

## 수명

JVM 인스턴스의 목표는 자바 응용 하나를 실행시키는 것이다. 자바 응용이 시작될 때 JVM 런타임 인스턴스가 생성되고, 응용이 끝날 때 같이 죽는다. 만약 한 컴퓨터에서 3개의 자바 응용을 동시에 시작시키면, 3개의 JVM 인스턴스를 보유하게 된다. 

`public static void main(String[] args)` 시그니쳐를 갖는 `main` 메서드가 있는 클래스라면 자바 응용의 첫 시작점이 될 수 있다. 메인 메서드는 응용의 첫 스레드가 시작되는 지점이다. 

자바에 2 종류의 스레드가 있다.

- 디먼

    JVM이 자시인 사용하는 스레드. ex) GC 수행 디먼

    다만, 응용도 임의 스레드를 디먼으로 지정할 수 있다.

- 논-디먼

    ex) 응용의 첫 스레드 (메인 함수에서 시작되는)

논-디먼 스레드가 살아있는 한, 자바 응용도 계속 실행된다. 논-디먼 스레드가 모두 죽었을 때 비로소 자바 응용이 종료되며 JVM 인스턴스도 종료하게 된다. `SecurityManager` 허용이 있다면 응용에서 `Runtime` 혹은 `System`의 `exit()` 메서드로 자체 종료를 진행할 수 있다.

## 아키텍처

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/de2a1ec7-2572-4487-9e39-4b01ace0453a/Untitled.png)

- **Class Loader Subsystem**

    fully qualified된 이름이 주어졌을 때 해당하는 타입(클래스, 인터페이스)을 적재한다.

- **Execution Engine**

    클래스 파일에 포함된 명령줄을 실행한다.

- **Runtime Data Areas**

    JVM이 프로그램을 실행하려면, 바이트코드와 클래스 파일에서 추출한 각종 정보를 저장해 둘 메모리 공간이 필요하다. 또 객체 인스턴스, 메서드의 파라미터, 메서드 반환값, 지역 변수, 연산 중간 결과값들도 저장해 두어야 한다. 

    **Method Area, Heap**은 동일 응용 내 여러 스레드가 공유할 수 있고, 나머지는 각 스레드가 독자적인 영역을 소유한다.

    ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/19ea3701-d125-4b32-988a-8881e3943bd1/Untitled.png)

    - **Method Area**

        JVM은 클래스 파일 적재 후 바이트 코드에서 타입 정보를 파싱하고 메소드 영역에 저장한다.

    - **Heap**

        JVM은 응용이 생성한 모든 객체를 힙에 저장한다. 

    - **PC Registers and Java Stacks**

        각 스레드는 자신만의 프로그램 카운터와 자바 스택을 갖는다. 프로그램 카운터는 해당 스레드가 다음 차례 수행할 명령줄을 가리킨다. 자바 스택은 스레드의 자바 메서드 호출 스택을 기록한다. 지역 변수, 매개변수, 중간 연산값 그리고 반환값 정보를 저장한다. 

        JVM은 레지스터가 없기 때문에 명령어 세트는 Java Stack을 저장공간으로 활용한다. 

    - **Native Method Stacks**

        네이티브 메서드의 상태는 `Native Method Stacks`에 따로 저장된다. 

    ### 스레드 별 데이터 공간

    ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/cc216e33-de0c-42f6-81fd-b6f2e4be63e4/Untitled.png)

    PC Register, Java Stack, Native Method Stack은 스레드 개인 공간이다. 다른 스레드는 해당 영역에 접근할 수 없다.

    ## 데이터 타입

    ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/0c526611-84fd-442b-9401-da8afe1073eb/Untitled.png)

    - 데이터 크기 단위: `Word`

        한 워드는 byte, short, int, char, float, returnValue, reference를 담을 수 있을 만큼 충분히 커야 한다.

        두 워드는 long과 double을 담을 수 있어야 한다. 

        결국 JVM 구현체는 한 워드의 크기를 최소 4바이트로 잡아야 한다. 일반적으로 호스트의 네이티브 포인터 크기를 한 워드로 설계한다. 

## 클래스 로더 서브시스템

두 종류의 클래스 로더: `원시 클래스 로더`와 `클래스 로더 객체`가 있다고 했다. 원시 클래스 로더는 JVM 구현체의 일부인 반면 클래스 로더 객체는 자바 응용의 일부이다. 서로 다른 클래스 로더가 적재한 클래스는 구분된 네임 스페이스를 갖는다. 

클래스 로더 서브시스템은 여러 JVM 파트와 `java.lang` 라이브러리를 포함한 것이다.

클래스 로더 객체는 `java.lang.ClassLoader`의 인스턴스인데, 이 클래스의 메서드는 응용에서 JVM의 클래스 적재 기능에 접근하도록 해 준다.  한편, JVM이 적재하는 타입들은 모두 `java.lang.Class` 인스턴스가 된다. `ClassLoader`와 `Class` 의 인스턴스들은 당연히 힙에, 타입 정보는 메서드 영역에 저장된다.

### 적재, 링크, 초기화

클래스 로더 서브시스템의 책임들이다. 이들은 정확한 순서에 맞추어 수행된다.

- 클래스 바이너리 위치를 식별하기 & 임포트 하기
- 임포트한 클래스의 정합성 검증
- 클래스 멤버 변수를 할당하고 초기화
- 심볼릭 참조를 리졸브
1. 적재: 특정 타입의 바이너리를 찾아 임포트하는 과정
2. 링크: 검증, 준비, 리졸브
    1. 임포트한 타입이 정확한지 검증
    2. 클래스 변수를 위한 메모리 할당과 기본값 초기화
    3. 심볼릭 참조를 직접 참조로 귀결
3. 초기화

설명한 프로레스는 **챕터7. 클래스 수명주기**에서 자세히 다룬다.

### 원시 클래스 로더

자바 API 포함, trusted 클래스를 적재하는 클래스 로더이다. 모든 JVM이 구현하고 있다.

"fully qualified" 형태로 타입 이름이 주어지면 원시 클래스 로더는 각자의 방식으로 해당 타입의 `.class` 파일을 찾아내야 한다. 

일반적으로 쓰이는 방식은 `CLASSPATH` 환경 변수가 지정한 디렉토리에서 부터 적합한 클래스 파일을 찾아 가는 것이다. 타입의 패키지 이름이 `CLASSPATH` 서브 디렉토리가 된다. `java.lang.Object` 타입이 있는 클래스 파일을 찾기 위해서, 원시 클래스 로더는 `CLASSPATH/java/lang` 디렉토리에서 `Object.class` 파일이 있나 살펴볼 것이다.

### 클래스 로더 객체

```java
protected final Class defineClass(byte data[], int offset, int length);
/* data는 .class 파일 포맷을 만족하는 데이터
 * 이 메서드가 호출되면 새 타입이 JVM의 메서드 영역에 추가되어야 한다. 
 */
protected final Class findSystemClass(String name);
/* name은 어떤 타입의 fully qualified name이다.
 * 이 메서드가 호출되면 JVM은 원시 클래스로더를 사용해 해당 타입을 적재해야 한다.
 * 대응하는 클래스 파일을 찾지 못하겠으면 ClassNotFoundException을 반환한다.
 */
protected final void resolveClass(Class c);
/* c는 클래스 객체이다. 
 * 이 메서드가 호출되면 c가 의미하는 타입이 링크되고 초기화 되어야 한다. 
 */
```

JVM 구현체는 `ClassLoader` 클래스의 각 메서드와, 대응하는 클래스 로더 서브시스템 기능을 연결하여야 한다.

`defineClass()` 의 경우 적재를 담당하는 메서드이다. 이 메서드가 `Class`를 잘 반환했다면 해당 타입의 바이너리가 메서드 영역에 저장되어 있다. 그러나 링크와 초기화 과정까지 진행된 것은 아니다. `resolveClass()` 메서드가 링크 및 초기화 과정을 담당한다. 

링크 및 초기화 프로세스는 **챕터6. 링킹 모델**에서 자세히 다룬다.

### 네임스페이스

각기 다른 클래스 로더는 서로 다른 네임스페이스를 지닌다. 따라서 두 클래스 로더가 동일한 타입을  적재한다 하더라도, 타입은 구분된다. 

이런 점에서 fully qualifed name만으로 타입을 식별하기가 충분하지 않을 수 있다. 하지만 JVM은 적재된 타입에 대한 데이터로서, 그 타입을 적재시킨 클래스 로더를 기억하고 있다. 그리고 클래스에 존재하는 심볼릭 참조를 귀결시킬 때, 참조되는 클래스는 역시 동일한 클래스 로더에 의해 적재되었다는 것을 요구하고 있다. 

## 메서드 영역

JVM 인스턴스가 타입을 적재해야 할 때, 클래스 로더 사용해 해당 타입이 있는 클래스 파일을 찾아내고 읽는다. 클래스 로더는 바이너리 스트림을 읽으면서 안에 포함된 타입 정보를 추출하고, 이들은 메서드 영역에 저장한다. 클래스 변수(static 변수) 역시 메서드 영역에 저장되는 정보이다. 

메서드 영역에 어떻게 타입 정보를 표현할지는 구현체 디자이너의 선택이다. 

메서드 영역은 모든 스레드가 공유하는 타입 정보이다. 그러니 메소드 영역의 자료구조는 thread-safe로 설계되어야 한다. 만약 두 스레드가 `Lava` 클래스를 필요로 하지만 `Lava`는 아직 적재되지 않았다면, 오직 한 스레드만이 `Lava` 를 적재하도록 해야하며 그 동안 다른 스레드는 기다려야 한다.

### 타입 정보

1. 타입의 이름
2. 부모 타입의 이름
    - 직접 상속한 클래스
    - 직접 상속한 인터페이스들
    - 자신이 인터페이스 혹은 `java.lang.Object`인 경우 제외
3. 타입이 인터페이스인가? 클래스인가?
4. 타입의 접근자

### 상수 풀

타입이 사용하는 상수 자료 집합이다. 배열처럼 인덱스로 엔트리에 접근한다.

1. 리터럴 상수

    스트링, 정수, 부동소수점 타입

2. 심볼릭 참조

    타입, 필드, 메서드에 대한 심볼릭 참조

    메서드 영역에 심볼릭 참조가 유지되기 때문에 동적 링크가 가능하다.

### 필드 정보

- 필드명
- 타입
- 접근자

### 메서드 정보

- 메서드 이름
- 반환 타입
- 인자의 개수와 타입들
- 접근자

### 스태틱 변수 (스태틱 상수 제외)

JVM이 클래스를 사용하기 전에, `non-final` 클래스 변수를 위한 공간이 메서드 영역에 할당되어야 한다.  `final` **클래스 변수는 타입의 상수 풀에 저장되므로 다르다**. 

`non-final`은 그들을 선언하는 클래스의 데이터로서 저장되는 것이며, `final`은 그들을 사용하는 모든 클래스를 위한 자료로서 저장된다.

### 클래스 로더 객체에 대한 참조

JVM은 타입을 적재할 때 사용한 클래스 로더를 추적한다. 이 정보가 메서드 영역에 있다.

### 클래스 객체에 대한 참조

JVM은 타입을 적재한 뒤 `Class` 객체를 생성하고 그 참조를 메서드 영역에 보관한다.

```java
public static Class forName(String className);
/* 이 메서드를 사용하여 className을 나타내는 Class 객체를 얻을 수 있다.
 * 해당 타입은 현재 네임스페이스에 적재될 수 있어야 한다. (혹은 이미 적재되어 있어야 한다.)
 * 네임스페이스에 타입을 적재할 수 없다면 ClassNotFoundException을 반환한다.
 */

public final Class getClass();
/* Object 클래스에 정의된 메서드이다.*/
```

`Class` 객체의 주기능은 메서드 영역에 있는 타입 정보를 응용에게 제공하는 것이다. 

```java
public String getName();
public Class getSuperClass();
public boolean isInterface();
public Class[] getInterfaces();
public ClassLoader getClassLoader();
```

### 메서드 영역 사용 예제

```java
class Lava {
	private int speed = 5;
	void flow() {
	}
}

class Volcano {
	public static void main(String[] args) {
		Lava lava = new Lava();
		lava.flow();
	}
}
```

`main()` 의 첫째 바이트 코드를 JVM이 어떻게 실행할까? JVM 구현마다 다를 수 있으나 개략적인 한 예를 적어본다.

- **Volcano를 적재하고 첫 바이트 코드를 실행한다.**
    1. 사용자는 `Volcano` 응용 프로그램을 JVM에서 실행시킨다.
    2. JVM은 `Volcano.class` 파일을 찾아 바이너리를 읽는다. 그러면서 타입 `Volcano` 에 대한 정보를 파싱하여 메서드 영역에 저장한다.
    3. JVM은 메서드 영역에 있는 `main()`의 바이트코드 첫 줄을 해석한다. 

        아직 `Lava` 타입에 대한 적재를 하지 않았다. 이 JVM 구현체는 레이지하게 타입을 적재한다.

    4. 첫 줄을 해석하니 의미가 이렇다.

        "상수 풀 0번 엔트리의 객체를 담을 수 있을 만큼 메모리를 할당하세요."

    5. JVM은 `Volcano` 의 상수 풀의 0번 엔트리를 얻는다. 이 값은 심볼 "Lava"이다.
- **Lava를 적재한다.**
    1. JVM은 `Lava` 가 적재된 상태인지 살핀다. 

        `Lava`가 적재되지 않았다면 `Lava.class` 파일을 찾고 바이너리를 읽는다. 그러면서 타입 `Lava` 에 대한 정보를 파싱하여 메서드 영역에 저장한다.

    2. `Lava`를 적재 후, `Volcano`의 상수 풀 0번 엔트리 값 "Lava"를 "Lava"의 클래스 데이터에 대한 참조로 치환한다.

        따라서 다음 번에 상수 풀 0번 엔트리를 사용하게 되면, 심볼 "Lava"를 해석하여 메소드 영역에 도달하지 않아도 된다. 바로 `Lava` 의 클래스 데이터를 사용할 수 있다. (`constant pool resolution`)

    3. JVM은 `Lava` 객체를 위한 메모리 공간을 할당할 수 있게 되었다. 메서드 영역에서 `Volcano` 의 상수 풀 0번 엔트리를 참조하고, `Lava` 데이터에 접근한다. 해당 정보를 토대로 힙 공간이 얼마나 필요한지 계산한다.

        JVM은 메서드 영역의 클래스 데이터를 보고 필요한 힙 영역 크기를 결정할 수 있어야 함.

    4. `Lava` 를 위한 힙을 할당한다. 멤버 변수 `speed` 는 0으로 초기화된다.
- **Lava를 사용한다.**

    `Lava` 에 대한 참조를 스택(지역변수 `lava`)에 저장한다. 

    다음 바이트 코드 명령어는 해당 참조의 `speed` 변수를 5로 초기화한다. 

    그 이후의 바이트 코드는 해당 참조의 `flow()` 메서드를 호출한다.

**Comment by JasonYoo1995** [comment]
## 로딩이란? 
컴파일된 *.class 파일을 ClassLoader를 통해 JVM 내의 메모리(Method 영역)에 탑재하는 것
[참고](https://dailyworker.github.io/fundamental-JVM-classloader/)

## 로딩의 종류
### 정적 로딩
- 프로그램 초기화 시 메모리에 로딩하는 것
- 전체 실행 시간 중 단 1번만 로딩
### 동적 로딩
- 프로그램 초기화 이후 특정 시점에 메모리에 로딩하는 것
- 전체 실행 시간 중 여러 번 로딩 가능
>Java classes aren’t loaded into memory all at once, but when required by an application. At this point, the Java ClassLoader is called by the JRE and these ClassLoaders load classes into memory dynamically.
출처 : https://www.geeksforgeeks.org/classloader-in-java/

## 정적 로딩과 동적 로딩의 지원 범위
- 플랫폼에 따라 다르다
 ex) 자바 JVM은 기본적으로 **동적 로딩**을 전적으로 지원
 ex) C언어는 기본적으로 **정적 로딩**을 하고, 예외적으로 dll 파일을 통해서 **동적 로딩** 가능
 ex) 일부 임베디드 시스템에서는 **정적 로딩**만 가능하나, 일부 임베디드 시스템에서는 **동적 로딩**도 지원
[참고](https://prepinsta.com/operating-systems/static-vs-dynamic-loading/)

## 동적 로딩의 종류
### 로드 타임 동적 로딩 (Load Time Dynamic Loading)
```java
package DynamicLoading;

/**
 * cmd 명령
 * 컴파일 : C:\Projects\Java Projects\Spring Study\src\main\java>javac DynamicLoading/LoadTimeDynamicLoadingTest.java -encoding UTF-8
 * 실행 : C:\Projects\Java Projects\Spring Study\src\main\java>java -verbose:class DynamicLoading.LoadTimeDynamicLoadingTest
 */

public class LoadTimeDynamicLoadingTest {
    static void sleep(int time) throws Exception{
        for (int i = 1; i <= time; i++) {
            System.out.println("SLEEP " + i + "sec");
            Thread.sleep(1000);
        }
    }

    public static void main(String[] args) throws Exception {
        System.out.println("My String");

        sleep(3);

        new B();
    }
}
```
https://dailyworker.github.io/fundamental-JVM-classloader/
(위 링크에 따르면, 해당 예시가 로딩 타임에 로딩이 되어야 하는데
제가 직접 실행하면 런타임에 로딩이 되네요. 왜 그런지 모르겠습니다.)

- B.class 파일을 삭제하고 실행하면, Class를 발견할 수 없다는 예외가 발생하는 것으로 보아, 런타임 중에 동적으로 파일을 읽어서 메모리에 로딩한다는 사실을 눈으로 확인할 수 있음

### 런타임 동적 로딩 (Runtime Dynamic Loading)
```java
package DynamicLoading;

/**
 * cmd 명령
 * 컴파일 : C:\Projects\Java Projects\Spring Study\src\main\java>javac DynamicLoading/RuntimeDynamicLoadingTest.java -encoding UTF-8
 * 실행 : C:\Projects\Java Projects\Spring Study\src\main\java>java -verbose:class DynamicLoading.RuntimeDynamicLoadingTest A
 *       또는 C:\Projects\Java Projects\Spring Study\src\main\java>java -verbose:class DynamicLoading.RuntimeDynamicLoadingTest B
 */

public class RuntimeDynamicLoadingTest {
    static void sleep(int time) throws Exception{
        for (int i = 1; i <= time; i++) {
            System.out.println("SLEEP " + i + "sec");
            Thread.sleep(1000);
        }
    }

    public static void main(String[] args) throws Exception {
        sleep(3);

        Class.forName("com.company." + args[0]);

        sleep(3);

        System.out.println("Before 1st A created");
        new A();
        System.out.println("After 1st A created");

        sleep(3);

        System.out.println("Before B created");
        new B();
        System.out.println("After B created");

        sleep(3);

        System.out.println("Before 2nd A created");
        new A();
        System.out.println("After 2nd A created");
    }
}
```

**추측**
아마도 리플렉션으로 새로운 코드를 삽입하는 것은
초기화 시간에 이미 메서드 영역에 탑재된 Class들의 바이트 코드를
런타임 중에 조작해 새로운 바이트 코드를 만들어
메서드 영역에 저장하는 등의 방법이 아닐까 추측해봅니다
 
## 3가지 타임의 구분
### 컴파일 타임
- 프로그램 시작 전에, 고수준 코드(고급 언어)를 저수준 코드(바이너리 코드)로 해석하는 시간
### 로드 타임
- 로드 타임이라는 공식 용어는 없는 듯하다. 사람마다 정의하기 나름인 듯
- 초기화 시간의 **정적 로드** 타임과, 초기화 시간 이후의 **동적 로드** 타임 둘 다를 지칭할 수 있는 듯 
### 런타임
- 좁은 의미로는 초기화 시간 이후의 실행 시간을 의미하는 듯
- 넓은 의미로는 초기화 시간을 포함한 전체 실행 시간을 의미하는 듯
- 로드 타임은 런타임 중에만 일어날 수 있는 시간이므로, 런타임이 로드 타임을 포함한다고 볼 수 있을 듯.
[참고](https://sujl95.tistory.com/28)

## 3가지 위빙의 구분
- 컴파일 타임 위빙 : 컴파일 타임에 위빙 ex) 롬복 등
- 로드 타임 위빙 : 로드 타임에 위빙 
- 런타임 위빙 : 런 타임에 위빙 

[참고](https://jaehun2841.github.io/2018/07/22/2018-07-22-spring-aop4/#%EB%9F%B0%ED%83%80%EC%9E%84-%EC%8B%9C-%EC%9C%84%EB%B9%99-rtw-runtime-weaving)
