### ISSUE TITLE
[keyword] 5장 스프링 AOP 소개 (1) 키워드 정리

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#38]
## 주제
[5장] 스프링 AOP 소개(1)을 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요
## 연관 챕터
#37

**Comment by emiling** [comment]
### 마커 인터페이스 (5.4.10)
>  [p.351] ThrowsAdvice는 지금까지 살펴본 인터페이스와는 달리 메서드를 정의하지 않습니다. 해당 인터페이스는 그저 스프링이 사용하는 마커 인터페이스에 지나지 않습니다.

- 아무 메서드도 담고 있지 않고, 단지 자신을 구현하는 클래스가 특정 속성을 가짐을 표시해주는 것 (ex. Serializable)
```java
public interface SomethingObject{}
```
- 주된 목적은 간단하게 해당 인터페이스로 선언되었는지 안되어 있는지 체크 정도 하는 **타입 체크** 역할
  - `ObjectOutputStream.writeObject0` 참고
- [p.351] ThrowsAdivce 메서드가 어떤 메서드도 정의하지 않는 이유는 스프링이 타입이 지정된 스로우 어드바이스를 지원하기 때문입니다


### 편리한 Advisor 구현체 (5.5.10)

- **DefaultPointcutAdvisor + NameMatchMethodPointcut**
```java
NameMatchMethodPointcut pc = new NameMatchMethodPointcut();
pc.addMethodName("sing");
pc.addMethodName("rest");
Advisor advisor = new DefaultPointcutAdvisor(pc, new SimpleAdvice());
```
- **NameMatchMethodPointcutAdvisor**
```java
NameMatchMethodPointcutAdvisor advisor = new NameMatchMethodPointcutAdvisor(new SimpleAdvice());
advisor.setMappedNames("sing");
advisor.setMappedNames("rest");
```
