### ISSUE TITLE
[question] Filter vs Interceptor vs AOP - 인증 로직을 담기 좋은 위치?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#39]
## 질문
Filter vs Interceptor vs AOP - 인증 로직을 담기 좋은 위치?

## 상세 내용
책 `5.4.7 비포 어드바이스를 사용한 메서드 접근 보호`에서 AOP를 통해 사용자 인증을 거친 후 메서드를 실행하는 일종의 보안 로직을 구현하고 있습니다.

`비포 어드바이스`는 사용자의 요청을 담당하는 핸들러에 도달하기 전에 특정한 로직을 수행한다는 점에서 
Servlet `Filter` 및 `Interceptor`와 비슷한 역할을 하는듯 하고, 실제로 세 가지를 비교하며 설명하는 경우가 많은 것으로 알고 있습니다.

그렇다면 `사용자 인증 로직`은 Filter, Interceptor, AOP 중 어떤 위치에서 수행하는 것이 좋은지 경험에 기반한 이야기나, 기술적인
근거에 기반한 논리를 풀어보면 좋을 것 같아 해당 이슈를 발행하였습니다.

## 연관 챕터
#37 

## 참고
![Filter AOP Interceptor](https://user-images.githubusercontent.com/19742896/128888049-c67d56d6-5825-4d77-9ee0-f972000820f0.png)

**Comment by wooyounggggg** [comment]
관련해서 서칭을 해보고, 저는 아래와 같은 결론을 도출할 수 있었습니다.

### Filter를 사용해 인증/인가 구현하기
**Filter**는 위 그림에서 보시는 것처럼, 사용자 요청 발생시 가장 앞 단에서 요청을 검사하는 녀석이기 때문에, Filter에서 인증/인가 로직을 수행한다면 필요하지 않은 처리를 걸러내어 성능상 가장 이점을 가져가는 방법일 것이라 생각했습니다. 하지만 문제점이 있다면, 스프링의 관할 영역이 아니라 서블릿 영역이기 때문에, 스프링의 지원을 받을 수 없다는 부분이 있겠습니다.

### Interceptor를 사용해 인증/인가 구현하기
**Interceptor**는 Filter가 요청에 대한 Filtering을 거친 후 `DispatcherServlet`으로 요청을 전달하면, DispatcherServlet이 Interceptor를 호출하는 방식으로 동작합니다. Filter보다는 성능상 단점이 있을 순 있겠지만, 스프링의 지원을 받을 수 있다는 부분이 크다고 생각합니다.

### AOP를 사용해 인증/인가 구현하기
**AOP**는 Interceptor의 preHandle 영역이 종료된 이후 본격적인 스프링 컨텍스트가 시작되면서 스프링이 로직을 적용하게 됩니다. 개인적인 의견으로, 굳이 Filter나 Interceptor등 앞 단에서 걸러낼 수 있는 요청들을 미뤄 AOP 단에서 수행하는 것은 이유 없는 요청 부하를 발생시키는 것이나 다름없기 때문에 AOP에서는 인증/인가 로직을 구현하는 것이 좋은 방법이 아니라고 생각됩니다.

### Filter vs Interceptor  
그래서 저는 Filter와 Interceptor 두 가지가 인증/인가를 적용할 후보군이라고 생각하는데요, 그 문제에 대해서는 아래와 같이 생각합니다.

- 다른 라이브러리나 프레임워크 없이 스프링만 사용하는 경우 -> **Interceptor**
순수하게 스프링만을 사용해서 인증/인가 로직을 구현할 때에는 개인적으로 Interceptor를 사용하는 것이 더 좋다고 생각됩니다. 프레임워크를 사용하면서, 프레임워크가 제시하는 패턴을 따라 개발을 할 텐데, 프레임워크의 외부 영역에 있는 것이 프레임워크에게 영향을 주는 형태로 개발을 하게 되면 유지보수가 어렵게 될 것이라고 생각해서입니다.

- 스프링 시큐리티와 같은 인증/인가 프레임워크 또는 라이브러리 사용
[스프링 시큐리티](https://docs.spring.io/spring-security/site/docs/current/reference/html5/)는 `Filter`를 기반으로 동작하는 프레임워크입니다.
아마 위에서 언급한 `스프링 지원` 영역과 `성능 이슈` 문제를 둘 다 잡고자 이러한 프레임워크가 발생하지 않았나하는 예측을 해봅니다. 😃

**Comment by emiling** [comment]
추가적으로 궁금한 것은 JWT/세션 방식에 따라 Filter/Interceptor를 사용처가 달라지는지 궁금합니다
=> 두 가지를 각각 구현해보는 것도 좋을 것 같습니다
