### ISSUE TITLE
[keyword] 1-2장 스프링 소개 및 스프링 시작하기 키워드 정리

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/pro-spring-5#4]
## 주제
[1-2장] 스프링 소개 및 스프링 시작하기 를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요
## 연관 챕터
#3

**Comment by wooyounggggg** [comment]
## 키워드
`결합도`와 `응집도`의 개념은 객체지향 설계 과정에서 자주 사용되고, 앞으로 스터디 과정에 전반적으로 등장할 개념이라고

생각해서 결합도와 응집도의 개념부터 구체적 사례까지 살펴보면 좋을 것 같아 해당 키워드를 선정하였습니다.

이미 아시는 분은 한번 더 깊게 개념을 살펴보시고, 모르시는 분은 같이 공부해봅시다 😃 

## 세부 키워드
1. 결합도란?

    - 결합도의 개념
    - 결합도가 높은 코드와 결합도가 낮은 코드 사례
    - 결합도는 높아야 할까, 낮아야 할까? 그 이유는?
    - 결합도를 높이는(낮추는) 방법
    - 결합도와 관련깊은 객체지향 특성은 무엇일까

2. 응집도란?

    - 응집도의 개념
    - 응집도가 높은 코드와 결합도가 낮은 코드 사례
    - 응집도는 높아야 할까, 낮아야 할까? 그 이유는?
    - 응집도를 높이는(낮추는) 방법

**Comment by wooyounggggg** [comment]
결합도와 응집도에 대한 키워드 이슈를 발행했습니다.

추가적으로 더 조사해보면 괜찮을 만한 주제를 수정이 가능하다면 직접 수정해주시고, 아니면 comment로 남겨주시면 반영해보겠습니다~!

**Comment by binchoo** [comment]
## 메이븐과 그레이들 프로젝트

### 디렉토리 구조
눈에 익은 구조이고 직관적이라, 저는 한 번도 살펴보지 않았는데요. 책에서 짚어 주고 있어서 이 기회에 다시 눈도장을 찍어두면 좋을 것 같습니다.
![image](https://user-images.githubusercontent.com/15683098/125148627-c2748380-e16e-11eb-947f-f07da09a3fd1.png)

### 아티팩트
- 아티팩트가 무엇인지
- 아티팩트 경로의 구성요소는
- 메이븐 프로젝트에서 아티팩트를 어떻게 가져오는지
- 그레이들 프로젝트에서는 어떻게 가져오는지

### 전이 의존성
메이븐과 그레이들은 전이 의존성을 지원하는 빌드 도구라고 합니다.
아래 설명된 모듈들의 의존 관계를 봤을 때, 스프링의 `ApplicationContext` 인터페이스를 사용하려면 어떤 아티팩트들을 가져와야 할까요.

[spring-context에 대한 설명]
![image](https://user-images.githubusercontent.com/15683098/125149075-af16e780-e171-11eb-9100-f5a3b480bdb8.png)

[모듈 의존성]
`spring-context` -> `spring-beans` -> `spring-core`
![image](https://user-images.githubusercontent.com/15683098/125149027-64956b00-e171-11eb-9ef4-d125977e2d6a.png)

**Comment by binchoo** [comment]
## 인터페이스 의존 -> 결합도 낮아짐
예제 코드 2-9는 결합도가 낮아진 코드라고 주장하고 있습니다. https://github.com/caffeine-library/pro-spring-5/issues/4#issuecomment-874166560 와 관련하여 이 주장을 뒷받침 할 수 있어야 하겠습니다.
```java
    public static void main(String... args) {
        MessageRenderer mr = new StandardOutMessageRenderer();
        MessageProvider mp = new HelloWorldMessageProvider();
        mr.setMessageProvider(mp);
        mr.render();
```

**Comment by emiling** [comment]
### 의존성(Dependency)

스프링의 시작은 의존성에 대한 이해라고 생각합니다.

의존성을 어떻게 처리할 것인지에 대한 고민에 대해 스프링은 IoC/DI 라는 해결책을 제시했고
비단 스프링 뿐만 아니라 객체지향적으로 더 나은 설계를 위해선 반드시 고민해보아야 하는 부분입니다.

- 의존성
  - 개요
  - 클래스 의존성/패키지 의존성
- 의존성 설계 가이드
- 예제 
  - 설계 개선

**참고**
원본 영상 : https://www.youtube.com/watch?v=dJ5C4qRqAgA
코드 : https://github.com/eternity-oop?tab=repositories

**Comment by emiling** [comment]
### 팩토리 패턴

[예제 2-10](https://github.com/gilbutITbook/006987/blob/dd53d8cc299fdc6858aa86476aea53a1b501cec4/chapter02/hello-world/src/main/java/com/apress/prospring5/ch2/decoupled/MessageSupportFactory.java#L12-L23) 에서는 팩터리 클래스를 만들어 특정 객체를 반환하고 있는데요

이와 관련하여 팩토리 패턴에 대해 같이 짚고 넘어가면 좋을 듯 합니다. 
그리고 여담으로 가볍게 다형성과 조건문에 대한 부분도 함께 생각해볼만해서 넣어두었습니다.

**참고**
- 팩토리패턴 정리 
  - [팩토리 패턴 이해](http://wiki.gurubee.net/pages/viewpage.action?pageId=1507401#4.%ED%8C%A9%ED%86%A0%EB%A6%AC%ED%8C%A8%ED%84%B4-1.%EA%B0%84%EB%8B%A8%ED%95%9C%ED%8C%A9%ED%86%A0%EB%A6%AC)
- 다형성과 조건문
  - http://redutan.github.io/2016/03/31/anti-oop-if
  -  https://www.slipp.net/questions/566

**Comment by JasonYoo1995** [comment]
test

**Comment by JasonYoo1995** [comment]
@binchoo 님께서 [위 comment](https://github.com/caffeine-library/pro-spring-5/issues/4#issuecomment-877541695)에서 언급해주신 '전이 의존성'을 손쉽게 한 눈에 볼 수 있는 IntelliJ의 메뉴를 공유하겠습니다.

Maven 프로젝트의 경우 오른쪽의 Ant 아래에 있는 Maven 버튼을 누르면 Dependency를 통해 '전이 의존 관계'를 계층적으로 확인할 수 있습니다.
![image](https://user-images.githubusercontent.com/66045861/126151174-9f491979-fd76-4240-b079-56829200f905.png)

Gradle 프로젝트도 마찬가지입니다.
![image](https://user-images.githubusercontent.com/66045861/126151965-6f73fd24-b9d7-4792-9073-f0d9c0a612d0.png)
