### ISSUE TITLE
[question] Exception

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#40]
## 질문
Exception

## 상세 내용
`Exception`과 관련한 복수개의 질문이 있어 이슈로 발행하였습니다.

## 연관 챕터
#37

**Comment by wooyounggggg** [comment]
## 질문
`ThrowsAdvice` vs `ExceptionHandler`

## 상세내용
`5.4.10 스로우 어드바이스 만들기`에서 ThrowsAdvice를 구현하여 발생한 예외에 대한 일종의 핸들러 로직인 afterThrowing() 메서드를 구현하고 있습니다.

```java
public class SimpleThrowsAdvice implements ThrowsAdvice {

    ...

    /* Exception 타입의 Exception 발생 시 수행되는 로직 */
    public void afterThrowing(Exception ex) throws Throwable {
        System.out.println("***");
        System.out.println("Generic Exception Capture");
        System.out.println("Caught: " + ex.getClass().getName());
        System.out.println("***\n");
    }

    /* IllegalArgumentException 타입의 Exception 발생 시 수행되는 로직 */
    public void afterThrowing(Method method, Object args, Object target,
        IllegalArgumentException ex) throws Throwable {
        System.out.println("***");
        System.out.println("IllegalArgumentException Capture");
        System.out.println("Caught: " + ex.getClass().getName());
        System.out.println("Method: " + method.getName());
        System.out.println("***");
    }
}
```

해당 방식을 보면서 (이후에 보게 될) 스프링 MVC의 `ExceptionHandler`를 활용한 예외 처리 로직이 떠올랐는데, 두 방식에는 어떠한 연관성이나 차이점이 있는지 궁금하고, 어떻게 사용하는 것이 좀 더 적합한 방식인지 궁금해 질문 남깁니다.

**Comment by wooyounggggg** [comment]
## 질문
`ThrowsAdvice`는 어떻게 핸들러 로직을 찾아내나요?

## 상세내용
ThrowsAdvice 인터페이스 내부에는 별다른 메서드가 선언되어 있지 않기 때문에, 해당 인터페이스를 구현하더라도 Overriding할
메서드가 존재하지 않습니다.

그럼에도 불구하고 [윗 질문](https://github.com/caffeine-library/pro-spring-5/issues/40#issuecomment-896974399)에서의 코드처럼 `afterThrowing` 메서드를 작성하고, 형식에 맞게 argument를 작성해주면 추가적인 처리 없이 argument로 작성된 Exception이 발생할 때 핸들러 로직이 작동되는 것으로 보아, 핸들러 로직이 정상적으로 등록 되었음을 알 수 있습니다.

추측하기로는 스프링이 `Reflection API`를 통해 클래스 메타 정보를 읽어 내부적으로 핸들러를 등록하는 것 같은데, 실제로 그렇게
동작하고 있는 것인지 궁금합니다.

**Comment by JasonYoo1995** [comment]
[위 질문](https://github.com/caffeine-library/pro-spring-5/issues/40#issuecomment-896978430)에 대한 답변을
오늘 발표 때 말씀드리겠습니다.
