### ISSUE TITLE
[question] 동적 포인트컷은 왜 정적 검사를 캐싱하지 않을까요?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#41]
## 질문
동적 포인트컷은 왜 정적 검사를 캐싱하지 않을까요?

## 상세 내용
`책 5.5.5 DynamicMethodMatcherPointcut을 사용해 동적 포인트컷 만들기`에서, 동적 포인트컷을 생성해 어드바이스를 적용할 대상을 런타임에 동적으로 검사하여 어드바이스를 지정해주는 코드를 구현하고 있습니다.

예제 5-30의 코드 설명 부분(P.366~367)에서는 `foo() 메서드는 모든 메서드를 검사하는 초기화 단계와 메서드가 처음 호출되는 단계에서 두 번의 정적 검사를 받았다는 것입니다.`라고 언급하면서, 동적 포인트컷을 적용한 대상은 매 메서드 호출시마다 정적 검사를 거치게 됨을 이야기하고 있습니다.

이해가 가지 않는 부분은, 일반적으로 `정적 검사`라 함은 클래스의 `메타데이터`를 기반으로 어드바이스를 적용할 지 여부를 따지는 부분이고, 런타임에 클래스의 메타데이터가 변할 일이 없을 것 같은데 왜 계속해서 정적 검사를 해서 성능 저하를 유발하는가? 라는 부분입니다.

무언가 이유가 있을 것 같은데, 명확하게 그려지지 않는 것 같아 질문 발행합니다 😄 

## 연관 챕터
#37

**Comment by JasonYoo1995** [comment]
``foo() 메서드는 모든 메서드를 검사하는 초기화 단계와 메서드가 처음 호출되는 단계에서 두 번의 정적 검사를 받았다는 것입니다.``라는 말은 사실입니다.
하지만 이 말은 ``동적 포인트컷을 적용한 대상은 매 메서드 호출시마다 정적 검사를 거치게 된다``는 뜻은 아닌 것 같습니다.
첫 메서드 호출 때만 정적 검사를 거치고, 두번째 호출 때부터는 정적 검사 없이 동적 검사만 거치게 됩니다.

아마 책에 출력 결과에 **초기화 단계**와 **메서드 호출부** 간의 구분선이 없어서 헷갈렸을 것 같습니다.

아래 코드를 직접 실행해보면 명확해집니다.
**초기화 단계**와 **메서드 호출부** 간에 구분선을 추가해 주었습니다.


### 실행 코드
```java
SampleBean target = new SampleBean();
Advisor advisor = new DefaultPointcutAdvisor(new SimpleDynamicPointcut(), new SimpleAdvice());
ProxyFactory pf = new ProxyFactory();
pf.setTarget(target);
pf.addAdvisor(advisor);
SampleBean proxy = (SampleBean) pf.getProxy();

System.out.println("=============================="); // 구분선

proxy.foo(1);
proxy.foo(10);
proxy.foo(100);

proxy.bar();
proxy.bar();
proxy.bar();
```

### 출력 결과
```
Static check for bar
Static check for foo
Static check for toString
Static check for clone
==============================
Static check for foo
Dynamic check for foo
>> Invoking foo
Invoked foo() with : 1
>> Done

Dynamic check for foo
>> Invoking foo
Invoked foo() with : 10
>> Done

Dynamic check for foo
Invoked foo() with : 100
Static check for bar
Invoked bar()
Invoked bar()
Invoked bar()
```

출력 결과를 보면, 초기화 이후 메서드를 아무리 여러 번 호출해도
정적 검사는 1번 밖에 이루어지지 않은 것을 확인할 수 있습니다.

좀 더 정확히 알아보기 위해, 실행 코드 6번째 줄의
```java
SampleBean proxy = (SampleBean) pf.getProxy();
```
이 코드까지만 실행해보면

```
Static check for bar
Static check for foo
Static check for toString
Static check for clone
```
이와 같은 출력 결과가 나옵니다.
이는 초기화까지만 시키고 메서드 호출은 수행하지 않았을 때의 결과입니다.

**Comment by wooyounggggg** [comment]
그렇네요! 그러면 질문을

**왜 초기화 단계와 메서드 초기 호출 단계에서 두 번의 정적 검사를 할까요?**로 조금 바꿔보겠습니다.

**Comment by emiling** [comment]
답을 아직 찾지 못했음

더 조사를 해보거나 질문을 올리거나... 코드를 까보거나 해보도록 합시다아...

**Comment by binchoo** [comment]
(이 글은 StaticMethodPointcut 예제를 보고 귀납적인 추측을 내린 것입니다.)

## 정적 검사가 수행된 두 시점
예제로 확인했듯이 정적 메서드 검사는 **두 시점**에 수행되고 있습니다.  
- `pf.getProxy()`를 호출하여 프록시를 생성하는 시점
- 타겟 메서드의 첫 호출 시점

## 정적/동적 포인트컷 동일한 동작이다
해당 동작은 동적 포인트컷에 국한되지 않습니다. 
정적 포인트컷 예제에 프린트 구문을 추가해서 확인이 가능합니다.

```java
public class StaticPointcutDemo {
    public static void main(String... args) {
        GoodGuitarist johnMayer = new GoodGuitarist();
        GreatGuitarist ericClapton = new GreatGuitarist();

        Singer proxyOne;
        Singer proxyTwo;

        Pointcut pc = new SimpleStaticPointcut();
        Advice advice = new SimpleAdvice();
        Advisor advisor = new DefaultPointcutAdvisor(pc, advice);

        ProxyFactory pf = new ProxyFactory();
        pf.addAdvisor(advisor);
        pf.setTarget(johnMayer);
        proxyOne = (Singer)pf.getProxy();

        pf = new ProxyFactory();
        pf.addAdvisor(advisor);
        pf.setTarget(ericClapton);
        proxyTwo = (Singer)pf.getProxy();

        proxyOne.sing();
        proxyOne.sing();

        proxyTwo.sing();
        proxyTwo.sing();
    }
}
public class SimpleStaticPointcut extends StaticMethodMatcherPointcut {
    @Override
    public boolean matches(Method method, Class<?> cls) {
        System.out.println("[static-pointcut] " + cls.getName() + "." + method.getName() + "메서드에 대한 정적 검사 실행");
        return ("sing".equals(method.getName()));
    }

    @Override
    public ClassFilter getClassFilter() {
        return cls -> (cls == GoodGuitarist.class || cls == GreatGuitarist.class);
    }
}
--- 수행결과 ---


```

## `AdvisedSupport`

스프링 AOP는 타겟 클래스의 모든 메서드를 정적 검사후 값을 캐싱하여 사용한다고 했습니다.
이 역할은 `AdvisedSupport`의 이름이 긴 메서드가 수행하고 있었습니다.

### `AdvisedSupport.getInterceptorsAndDynamicInterceptionAdvice()`
```java
public List<Object> getInterceptorsAndDynamicInterceptionAdvice(Method method, @Nullable Class<?> targetClass) {
    MethodCacheKey cacheKey = new MethodCacheKey(method);
    List<Object> cached = this.methodCache.get(cacheKey);
    if (cached == null) {
        cached = this.advisorChainFactory.getInterceptorsAndDynamicInterceptionAdvice(
                this, method, targetClass);
        this.methodCache.put(cacheKey, cached);
    }
    return cached;
}
```
[코드](https://github.com/spring-projects/spring-framework/blob/bb45a7ae5ea45670884434ba15924d3490527e8a/spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java#L466-L475)는 인수로 받은 `Method`에 대해  
1. 어드바이스 적용 대상인지 판단 후
2. 이 메서드에 대응되는 인터셉터 리스트를 캐싱합니다.

- 내부적으로 [DefaultAdvisorChainFactory.getInterceptorsAndDynamicInterceptionAdvice()](https://github.com/spring-projects/spring-framework/blob/bb45a7ae5ea45670884434ba15924d3490527e8a/spring-aop/src/main/java/org/springframework/aop/framework/DefaultAdvisorChainFactory.java#L51-L107)를 호출합니다.
  - 내부에서 `ClassFilter`와 **`MethodMatcher`를 사용해** 주어진 메서드가 어드바이스 적용 대상인지 판단
  - 적용대상이 맞으면 NULL이 아닌 인터셉터 리스트를 반환

## 두 번의 정적 검사 로그를 보게 된 원인
프록시 초기화 시점 & 메서드 첫 사용 시점에
- `AdvisedSupport`의 `getInterceptorsAndDynamicInterceptionAdvice`가 호출되기 때문.
- 따라서 `MethodMatcher`도 두 번 호출되기 때문입니다.

## 초기화 시점에 캐싱한 값은 왜 안 쓰이는 걸까요?

- 명백한 원인은 두 시점에 사용되는 `AdvisedSupport` 객체가 다르기 때문입니다.
- 이 행태의 의미까지도 결론지어야 한다면...
  - 프록시 생성 시점의 `getInterceptorsAndDynamicInterceptionAdvice` 호출은, 단지 메서드의 어드바이스 적용 여부를 얻기 위함이기 때문이라고 <u>생각합니다</u>.

### 프록시 생성 과정에서 `AdvisedSupport`로 향하는 메시지
코드를 따라가며 받은 인상을 개략적으로 표현한 것입니다.  `@숫자`는 디버거가 표시해준 객체 식별자입니다.

![image](https://user-images.githubusercontent.com/15683098/132940963-7b3f0b12-fb5b-4471-a361-1de34505a885.png)

마지막 `ProxyCallbackFilter`가 `AdvisedSupport@1477` 객체를 쓰는 모습을 보면
그저 `haveAdvice` 불리언을 얻기 위한 호출일 뿐입니다.  [코드](https://github.com/spring-projects/spring-framework/blob/bb45a7ae5ea45670884434ba15924d3490527e8a/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L872-L877)
```java
List<?> chain = this.advised.getInterceptorsAndDynamicInterceptionAdvice(method, targetClass);
boolean haveAdvice = !chain.isEmpty();
boolean exposeProxy = this.advised.isExposeProxy();
boolean isStatic = this.advised.getTargetSource().isStatic();
boolean isFrozen = this.advised.isFrozen();
if (haveAdvice || !isFrozen) {
    // If exposing the proxy, then AOP_PROXY must be used.
```

### 프록시 메서드 첫 사용시 `AdvisedSupport`로 향하는 메시지
![image](https://user-images.githubusercontent.com/15683098/132941596-d194fbfc-7766-4b54-b564-32b4d445cb25.png)

식별자 `1482`에 주목해보면 클라이언트가 생성한 `ProxyFactory@1482`가 메서드 첫 호출 단계에서 캐싱의 역할을 한다는 점을 발견할 수 있습니다. `ProxyFactory` 클래스는 부모로 `AdvisedSupport`를 갖습니다.  [코드](https://github.com/spring-projects/spring-framework/blob/bb45a7ae5ea45670884434ba15924d3490527e8a/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L664-L706) 

```java
List<Object> chain = this.advised.getInterceptorsAndDynamicInterceptionAdvice(method, targetClass);
Object retVal;
// Check whether we only have one InvokerInterceptor: that is,
// no real advice, but just reflective invocation of the target.
if (chain.isEmpty() && Modifier.isPublic(method.getModifiers())) {
    // We can skip creating a MethodInvocation: just invoke the target directly.
    // Note that the final invoker must be an InvokerInterceptor, so we know
    // it does nothing but a reflective operation on the target, and no hot
    // swapping or fancy proxying.
    Object[] argsToUse = AopProxyUtils.adaptArgumentsIfNecessary(method, args);
    retVal = methodProxy.invoke(target, argsToUse);
}
else {
    // We need to create a method invocation...
    retVal = new CglibMethodInvocation(proxy, target, method, args, targetClass, chain, methodProxy).proceed();
}
```

메소드 호출 절차에서 `AdvisedSupport` 이용은 타겟 메서드 호출을 가로챌 인터셉터를 얻으려는 뉘앙스입니다. 
그렇기 때문에 인터셉터 리스트의 캐싱이 더 의미있을 것입니다.


## 결론
- 프록시 작성 시점: 어드바이스 적용 여부만을 판단할 목적으로 `AdvisedSupport`가 이용된다.
- 프록시 메서드 호출 시점: 우리가 생성한 `ProxyFactory`가 어드바이스 적용 여부만을 판단 & 인터셉터 리스트를 캐싱한다.
- 각 시점에 사용되는 `AdvisedSupport` 인스턴스가 다르며, 활용 뉘앙스도 다르다. 

### 참고
- 프록시 생성 시점 스택 프레임  
![image](https://user-images.githubusercontent.com/15683098/132940032-58b80ce8-2e09-493a-9e45-d20c991f40ca.png)
- 프록시된 메서드 사용 시점 스택 프레임  
![image](https://user-images.githubusercontent.com/15683098/132940051-49ed5841-70f5-40ec-9835-f07b22b73b1a.png)
