### ISSUE TITLE
[keyword] 5장 스프링 AOP 소개 (2) 키워드 정리

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#44]
## 주제
[5장] 스프링 AOP 소개(2)를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요

## 연관챕터
#43

**Comment by JasonYoo1995** [comment]
### 조인포인트
### 
### 
### 
### 
### 
### 
### 

### 마커 인터페이스


5장에서 마커 인터페이스를 통한 AOP 얘기가 나오면서
저는 마커 인터페이스를 사용하는 또 다른 예가 떠올랐는데요
바로 JpaRepository 인터페이스입니다.

앞으로 6~8장에 걸쳐서 JDBC와 JPA에 대해서 공부할 텐데요
JpaRepository 인터페이스가 스프링에서 DAO를 어떻게 지원하는지
오늘 모임을 통해 실제 동작되는 코드를 통해 설명 드리겠습니다.

추가적으로 제가 개인적으로 JPA를 사용해 개발한 프로젝트가 있는데
이것에 대해서도 궁금하시다면 모임 때 설명 드리도록 하겠습니다.

**Comment by wooyounggggg** [comment]
### 7주차 스터디 정리

1. Keyword
#### 단어 정리
- AOP와 관련한 단어 정리가 명확하게 되지 않아 단어를 정리함
- JoinPoint의 의미 재정리(위 키워드에 반영하였습니다)

2. Question
#### 스프링 빈 라이프사이클 정리 #27
- 스프링 빈 라이프사이클(생성, 소멸)에 대한 순서 정리

#### 컴파일 타임 VS 로드 타임 VS 런타임 구분에 대해 명확히 알고 싶습니다 #34
- 내용이 길어져서 노션으로 이동
- Java
    - 자바는 다양한 의미를 가짐
    - 프로그래밍 언어 / 자바 가상머신 / API / 클래스 파일
- 자바 가상머신
    - 클래스 로더 Subsystem과 Execution Engine(바이트 코드 실행)으로 구성
    - Host OS 위에서 돌아감

- 자바 프로그래밍의 2가지 환경
    - Compile-time environment
        - IDE에서 작업하고, 컴파일러를 통해 .class 파일로 변환하는 과정
    - Run-time environment
        - 터미널 환경에서 java 명령어를 이용해 JVM 인스턴스를 실행했을 때의 과정

- 클래스 로더: bytestream을 읽어들임
    - 클래스 로더는 2가지 유형으로 구별 가능
        - JVM 내의 객체로 존재하는 ClassLoader: 개발자가 구성한 방식대로 클래스를 가져옴
        - JVM의 구현체인 ClassLoader(원시 클래스 로더): 자바 API를 불러옴
    - 동작
        - ClassLoader는 bytestream을 JVM 위로 올려야 함
        - JVM은 어떠한 클래스 로더가 클래스를 JVM에 올렸는지 기록하고 있음
        - 하나의 ClassLoader에서 올려둔 클래스들끼리만 참조가 가능함
        - ClassLoader는 클래스들의 네임 스페이스를 구성한다

- JVM?
    - JVM이 지칭하는 것
        - 추상 명세
        - 구현체
        - 런타임 인스턴스
    - 수명
        - JVM 인스턴스의 목표 = 자바 응용 하나를 실행시키는 것
        - 자바 응용 프로그렘이 시작될 때 JVM 런타임 인스턴스가 생성되고, 응용이 끝날때 사라짐
        - main method가 실행될 때가 응용의 첫 스레드가 시작되는 지점
    - 자바 스레드
        - 두 종류의 스레드가 존재
        - 디먼 스레드
            - JVM 자신이 사용하는 스레드. ex) GC 수행 디먼
            - 응용도 임의 스레드를 디먼으로 지정할 수 있긴 함
        - 논-디먼 스레드
            - ex) 응용의 첫 스레드
    - JVM 아키텍처
        - Method Area: 타입 정보를 저장
        - Heap: 타입의 인스턴스(객체) 저장 영역
        - Java stacks: 자바 응용 콜스택
        - pc registers: PC 역할을 하는 레지스터
        - Native method stacks: 시스템 콜과 같은 녀석을 호출할 때 사용되는 call stack
    - Execution Engine = 응용의 스레드

- 스레드 별 데이터 공간
    - PC registers
    - Java stacks
    - Native method stacks

- 클래스 로더 서브시스템
    - 로딩의 과정을 설명함
    - 클래스가 언제 JVM에 올라오고, 언제 JVM에서 빠져 나가는가(클래스 생명주기)
    - 적재 -> 링크 -> 초기화의 과정을 가짐
    - 적재
        - 클래스 로더 서브시스템에게 .class 파일을 가져오게 함 - classpath를 따라가서 .class를 가져오는 등의 처리
        - Method Area에 정리하여 넣어줌
        - Class Object를 Heap에 적재
    - 링크
        - 검증-verify
            - 자바의 다양한 제약 조건에 맞게 구현되어 있는지 검사
            - 검증시 에러가 발생하면 처음 해당 타입을 사용할 때 에러를 뱉음
        - 준비-prepare
            - 클래스 변수(static && non-final 변수)들을 초기화 함: 해당 타입의 기본값을 넣어줌
        - (귀결-resolve)
            - 심볼릭 참조를 실제 주소로 변환함
            - 추후에 동적으로 resolve 할 수도 있기 때문에 생략됨
    - 초기화(우리가 생각하는 초기화가 이것임)
        - 항상 적재 및 링크가 끝나고 진행됨
        - 부모 타입은 항상 자식 타입보다 먼저 초기화 된다
        - 인터페이스는 초기화 될 필요 없음
        - 타입이 처음 사용될 때 이전에 반드시 초기화가 되어 있어야 함
        - 즉, 클래스가 처음 사용될 때는 이미 적재, 링크 및 초기화 과정을 다 거친 상태여야 한다

- 예제 톺아보기
    - 예제 코드(Son, Super, ...) 분석

- 객체 생명주기
    - void finalize()
    - 결론 - 쓰지 않는것을 권유함

- 타입 Unloading(타입의 소멸)
    - 타입의 소멸을 위한 정책
    - 메서드 영역이 무한히 커지는 것을 방지하기 위해 타입을 동적 로드하고, 소멸시킴
    - Unloading 가능한 타입
        - 원시 클래스로더가 가져온 타입은 적재 해제가 불가능
        - 클래스 로더 객체가 가져온 타입만 가능
    - Unloading 정책
        - JVM에서 메서드 영역에 타입 정보가 있으며, 해당 타입의 Class 인스턴스에 접근할 수 없을 때 unloading 가능
        - 그림을 보면 더 이해하기 쉬움

- 결론: 클래스 로딩이란 무엇인가?
    - 타입 데이터를 적재 및 링크하는 시점은 JVM의 스펙에 따라 다름
        - 타입의 심볼릭 참조를 처음 만났을 때
        - 등등..
    - 초기화 타임은 정해져있다.
        - Static block이 실행되는 시점

- 질문: 인터페이스는 메모리에 실제로 존재하는가?
