### ISSUE TITLE
[keyword] 6장 스프링 JDBC (1) 키워드 정리 

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/pro-spring-5#47]
## 주제
[6장] 스프링 JDBC (1)를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요

## 연관챕터
#46

**Comment by binchoo** [comment]
## 원격 데이터 접근을 위한 추상화 방식

### `java.sql.Connection`

`java.sql.DriverManager`의 `getConnection()` 메서드 혹은,

`java.sql.Driver` 의 `connect()` 메서드로 `Connection` 객체를 획득하여 SQL 쿼리를 날리는 방식.

### `javax.sql.DataSource`

`javax.sql.Datasource` 구현체에 원격 저장소 정보를 캡슐하고, `getConnection()` 메서드로 `Connection` 객체를 획득하여 SQL 쿼리를 날리는 방식.

- `org.springframework.jdbc.datasource` 패키지

  - `DriverManagerDataSource`

     내부에서 `DriverManager.getConnection()` 를 사용하는 구현체.

    ```java
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName(driverClassName); //or, Class.forName(dirverClassName);
    dataSource.setUrl(url);
    dataSource.setUsername(username);
    dataSource.setPassword(password);
    
    conn = datasource.getConnection();
    ```

  - `SimpleDriverDataSource`

    `driver.getConnection`

    내부에서 `Driver.connect()`를 사용하는 구현체. 이 친구는 `driverClassName` setter가 없습니다.

    ```java
    SimpleDriverDataSource dataSource = new SimpleDriverDataSource();
    Class<? extends Driver> driver = (Class<? extends Driver>) Class.forName(driverClassName);
    dataSource.setDriverClass(driver);
    dataSource.setUrl(url);
    dataSource.setUsername(username);
    dataSource.setPassword(password);
    
    conn = datasource.getConnection();
    ```

- `org.apache.commons.dbcp2` 패키지

  - `BasicDataSource`

    커넥션 풀을 사용하는 구현체. `getConnection()` 호출은 커넥션 풀이 관리하는 `Connection` 객체를 빌려다 반환한다. 커넥션 풀의 maxActive=5라면 최대 5개의 쿼리가 동시에 진행될 수 있다.

    ```java
    DriverManagerDataSource dataSource = new BasicDataSource();
    dataSource.setDriverClassName(driverClassName); //or, Class.forName(dirverClassName);
    dataSource.setUrl(url);
    dataSource.setUsername(username);
    dataSource.setPassword(password);
    
    conn = datasource.getConnection();
    ```

### `org.springframework.jdbc.core.JdbcTemplate`

아래에서 설명됨.

## 임베디드 데이터베이스

### XML 설정

- `<beans>`에 `jdbc` 스키마 선언
- `<jdbc:embedded-database>` 태그로 임베디드 데이터베이스 구성
- 기본 type은 HSQL이며 의존성 추가 필요하다.

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:jdbc="http://www.springframework.org/schema/jdbc"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/jdbc 
        http://www.springframework.org/schema/jdbc/spring-jdbc.xsd">

    <jdbc:embedded-database id="dataSource" type="H2"> <!--type 기본값: HSQL-->
        <jdbc:script location="classpath:db/h2/schema.sql"/>
        <jdbc:script location="classpath:db/h2/test-data.sql"/>
    </jdbc:embedded-database>

    <bean id="jdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate"
          p:dataSource-ref="dataSource" />

    <bean id="singerDao" class="com.apress.prospring5.ch6.JdbcSingerDao"
          p:jdbcTemplate-ref="jdbcTemplate" />

    <bean class="com.apress.prospring5.ch6.CleanUp" c:jdbcTemplate-ref="jdbcTemplate"
           destroy-method="destroy"/>
</beans>
```

### EmbededDatabaseBuilder 로 DataSource 획득하기

```java
@Bean
public DataSource dataSource() {
	try {
        EmbeddedDatabaseBuilder builder = new EmbeddedDataBasebuilder();
        return builder.setType(EmbeddeddatabaseType.DERBY)
            .addScripts("classpath:db/derby/schema.sql", "classpath:db/derby/test-data.sql")
            .build();
    } catch (Exception e) {
        ...
    }
    return null;
}
```

## JdbcTemplate 클래스

![jdbcTemplate](https://user-images.githubusercontent.com/15683098/131225392-9a7bdbda-56d6-4a04-b788-fb2454c14514.gif)

`import org.springframework.jdbc.core.JdbcTemplate`

- 모든 유형의 SQL 문을 실행할 수 있음
- 실행 결과로 모든 타입을 반환할 수 있음.
- Thread-safe: 하나의 JdbcTemplate 인스턴스를 여러 DAO가 사용하여도 무방함.

## JdbcTemplate 사용 패턴

### 초기화 패턴

- DAO의 `setDataSource(dataSource)`에서

     1. DAO에 DataSource를 생성자 주입한다.

     2. JdbcTemplate 객체를 생성하고 DataSource를 수정자 주입한다.

    ```java
    public class ConcreteDAO implements DAO {
        ...
    	public void setDataSource(DataSource dataSource) {
            this.dataSource = dataSource;
            this.jdbcTemplate = new JdbcTemplate();
            jdbcTemplate.setDataSource(dataSource);
        }
    }
    ```

- JdbcTemplate 객체가 Thread-safe 한 점을 활용해 싱글톤 빈으로 등록해 사용하는 방식.

  ```java
  @Bean 
  DataSource dataSource() { 
      ...
      return dataSource;
  }
  
  @Bean
  public JdbcTemplate jdbcTemplate() {
      JdbcTemplate jdbcTemplate = new JdbcTemplate();
      jdbcTemplate.setDataSource(dataSource)
      return jdbcTemplate;
  }
  ```

### 조회 연산

```java
public class JdbcSingerDao implements SingerDao, InitializingBean {
	private JdbcTemplate jdbcTemplate;
    public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }
    @Override
    public String findNameById(Long id) {
        return jdbcTemplate.queryForObject(
        	"select first_name || ' ' || last_name from SINGER where id=?",
            new Object[]{id}, String.class);
    }
}
```

위치 지정자 `?` 순서와 Object[] 매핑이 결합되는 불편함이 존재하므로, `NamedParameterJdbcTemplate`을 사용하여 위치 지정자 대신 Named Parameter를 이용할 수 있다.

```java
public class JdbcSingerDao implements SingerDao, InitializingBean {
	private NamedParameterJdbcTemplate jdbcTemplate;
    public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }
    @Override
    public String findNameById(Long id) {
        String sql = "SELECT first_name || ' ' || last_name"
            + "FROM SINGER WHERE id=:singerId";
        HashMap<String, Object> namedParameters = new HashMap();
        namedParameters.put("singerId", id);
        return jdbcTemplate.queryForObject(sql, namedParameter, String.class);
    } // Java에 인라인 해시 맵 선언은 없는가? mapOf("singerId", id) 같은..
}
```

### 조회 결과 객체 매핑

`RowMapper<T>` 를 상송하여 `ResultSet`의 각 행(row)을 POJO로 매핑하는 로직을 구현할 수 있다.

`RowMapper<T>` 는 `@FunctionalInterface` 이므로 구현체 작성 대신에, 람다식을 작성하여 주입해도 좋다.

- `RowMapper<Singer>` 구현

```java
@Override
public List<Singer> findAll() {
    String sql = "select id, first_name, last_name, birth_date from singer";
    return namedParameterJdbcTemplate.query(sql, new SingerMapper());
}

private static final class SingerMapper implements RowMapper<Singer> {
    @Override
    public Singer mapRow(ResultSet rs, int rowNum) throws SQLException {
        Singer singer = new Singer();
        singer.setId(rs.getLong("id"));
        singer.setFirstName(rs.getString("first_name"));
        singer.setLastName(rs.getString("last_name"));
        singer.setBirthDate(rs.getDate("birth_date"));
        return singer;
    }
}
```

- 람다식 사용

```java
@Override
public List<Singer> findAll() {
    String sql = "select id, first_name, last_name, birth_date from singer";
    return namedParameterJdbcTemplate.query(sql, (rs, rowNum) -> {
        Singer singer = new Singer();
        singer.setId(rs.getLong("id"));
        singer.setFirstName(rs.getString("first_name"));
        singer.setLastName(rs.getString("last_name"));
        singer.setBirthDate(rs.getDate("birth_date"));
        return singer;
    });
}
```

### 중첩 도메인 조회 결과 (조인 결과)를 객체 매핑

`ResultSetExtractor<T>`를 구현하여 결과 튜플의 정보를 토대로 POJO 매핑을 수행하면 된다.

[책 예제 참조](https://github.com/gilbutITbook/006987/blob/master/chapter06/spring-jdbc-resultsetextractor/src/main/java/com/apress/prospring5/ch6/JdbcSingerDao.java#L29-L55)

`Singer`는 `Album`과 다대일 관계로, `Album`이 `Singer` 외래키를 참조하는 구조를 갖고 있어서

프로그래머가 조회 결과를 토대로 `Singer`에 직접 `Album` 객체를 작성해 주입해야 한다.

**Comment by binchoo** [comment]
## 도커로 mysql과 mysql 클라이언트 실행

- 윈도우용 batch파일
  ```cmd
  :: mysql과 클라이언트 접속용 두 컨테이너가 사용할 네트워크 생성
  docker network create mysqlnet
  
  :: 네트워크 게이트웨이 주소 획득
  FOR /F "tokens=*" %%h IN ('docker network inspect -f "{{range .IPAM.Config}}{{.Gateway}}{{end}}" mysqlnet') do SET HOST=%%h
  
  :: mysql 컨테이너 생성 -이름: springmysql -비번: springmysql
  docker run --name springmysql --network mysqlnet -e MYSQL_ROOT_PASSWORD=springmysql -p 3306:3306 -d mysql:latest
  
  :: mysql 클라이언트 접속 컨테이너
  docker run -it --rm --network mysqlnet mysql mysql -h%HOST% -uroot -pspringmysql
  ```

**Comment by JasonYoo1995** [comment]
## JDBC vs SQLMapper vs ORM
![image](https://user-images.githubusercontent.com/66045861/131237456-b2540bc8-fc2e-4b42-9d7c-dda84222b8bb.png)
### JDBC
![image](https://user-images.githubusercontent.com/66045861/131237458-a40ed719-8669-4f63-a80c-ac6c17616f2b.png)
### Spring JDBC
![image](https://user-images.githubusercontent.com/66045861/131237475-140d90a3-50d7-40c7-a5a6-3c019c270fb9.png)
### JPA + Hibernate
![image](https://user-images.githubusercontent.com/66045861/131237493-9896ab91-0a52-4d4f-853a-f08ae883b6ec.png)

## Database 관련 모듈
### Driver
- Vendor가 표준 Interface에 맞춰서 만든 Driver 구현체를 제공
- 자기 자신을 DriverManager에게 등록
### DriverManager
- getConnection() 메서드 제공
- Connection Pool 제공 X
### DataSource
- getConnection() 메서드 제공
- Connection Pool 제공 O
- (Connection 객체를 소멸시키지 않고 재사용하므로) Connection를 반복적으로 얻을 때 사용
- JNDI를 통해 얻어올 수 있음
### Statement
- SQL 구문을 실행하는 역할
- 스스로는 SQL 구문 이해 못 함 -> 전달 역할
### PreparedStatement
- Statement 클래스를 상속 받음
- Statement 클래스와 장단점이 달라서 상호보완적 (혼용)
→ ResultSet, PreparedStatement, Connection 모두 close()하지 않으면 메모리 누수 발생

## DriverManager vs DataSource
### DriverManager 
- DriverManager.getConnection() : Connection 객체 생성 및 DB와 연결
- Connection.close() : DB와 연결 해제 및 Connection 객체 소멸
### DataSource
- DataSource.getConnection() : Pool에서 Connection을 빌림
- Connection.close() : Pool에 Connection을 반납

## CRUD가 DAO에 넘기는 타입
- Create와 Update는 DAO에게 Entity 객체 타입으로 전달
- Read와 Delete는 DAO에게 id 등의 필드 타입으로 전달

**Comment by emiling** [comment]
### 용어 정리
- POJO : 
- 엔티티 (Entitiy) : 테이블에 있는 데이터가 매핑되는 클래스
- DTO : 
- DAO : 모든 데이터 엑세스 서비스를 캡슐화하며 크게 CRUD의 형태의 메서드 포함
  - 저수준 데이터 엑세스 API 및 데이터 조작을 고수준 비지니스 서비스와 분리할 때 사용
  - 많은 양의 코드를 공통 유틸리티 클래스로 옮겨야 하며 그렇지 않으면 각 DAO 사이에 많은 중복 코드 발생
  - 동일 로직을 수행하는 중복 코드 제거 및 비지니스 로직에 집중

### JDBC 드라이버 로딩 (p.452)
드라이버 로딩 → 드라이버는 자신을 `java.sql.DriverManager`클래스(드라이버 목록 관리 및 어플리케이션에서 데이터베이스에 연결하는데 사용할 수 있도록 정적 메서드 제공)에 등록 →DriverManager의 `getConnection()` 메서드로 반환된 `java.sql.Connection` 인터페이스로 SQL 문장 실행 가능

### PreparedStatement (p.455)

### DataSource와 Connection
- 스프링은 `javax.sql.DataSource`를 구현한 빈을 제공하며 이 빈을 통해 DB Connection 관리
  - 스프링의 `DrvierManagerDataSource` :`DataSource`의 가장 간단한 구현체로 DB Connection을 얻을 때 DriverManager만 호출 
    -  따라서 DB connection pool을 지원하지 않으므로 테스트 외에는 사용하지 않도록 함
  - 스프링의 `SimpleDriverDataSource`: `DataSource`의 구현체 ([DrvierManagerDataSource vs SimpleDriverDataSource](https://stackoverflow.com/questions/55258148/difference-between-drivermanagerdatasource-and-simpledriverdatasource))
  - 혹은 apache commons의 `BasicDataSource`

### 체크 예외와 언체크 예외
> 스프링이 체크 예외 보다는 런타임 예외를 사용할 것을 주장하므로 체크 예외인 SQLException을 런타임 스프링 JDBC 예외로 변환하는 메커니즘이 필요합니다 (p.474)

- Exception?
  - Exception은 주로 자바에서 제공하는 java.lang.Exception 클래스와 Exception 클래스의 서브클래스들이 쓰이는 상황을 말한다.
  - 언체크 예외는 RuntimeException을 상속한 것들을 말하고
  - 체크 예외는 이외의 예외들을 말한다.

### JDBC Template

- 초기화
  - DataSource 객체를 생성자에게 넘긴 뒤 JdbcTemplate 인스턴스를 만든다
    ```java
    public void setDataSource(DataSource dataSource){
        this.dataSource = dataSource
        this.jdbcTemplate = new JdbcTemplate();
        this.jdbcTemplate.setDataSource(this.dataSource);
    }
    ```
    - JdbcTemplate은 한 번 구성하고 나면 스레드 세이프하다. 
- 유형
   -  `NamedParameterJdbcTemplate` → 위치 지정자를 통한 파라미터 전달
   - 함수
      - `queryForObject` 
      - `query`
        -  `RowMapper<T>` → `ResultSet`의 특정 레코드를 원하는 도메인 객체로 변환하는 `mapRow` 메서드 구현 (람다식 👍🏻)
        - `ResultSetExtractor<T>` → 단일 도메인 객체 외의 로우를 매핑하는 경우 사용 

### JOIN
