### ISSUE TITLE
[miscellaneous] JPA 책 요약 발표

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/pro-spring-5#54]
## 제목
JPA 책 요약 발표

## 내용
![image](https://user-images.githubusercontent.com/66045861/131839047-99946893-878b-4a08-b142-a4837c6adc1d.png)

앞으로 저는 DB 관련 Chapter들을 다루는 몇 주 동안
배달의 민족 개발팀장 김영한님이 쓰신 JPA 책을 공부해서
매주 요약 발표를 하도록 하겠습니다.

이 책은 총 16장으로 구성되어있으나
그 중 핵심 기초는 10장까지의 내용이므로
1장부터 10장까지의 내용을 모두 설명 드리는 것을 목표로 하고 있습니다.

## 관련 issue
#52 

## 스터디 일정
|날짜|챕터|제목|완료여부|
|------|---|---|---|
|2021.09.05|1장 / 2장|JPA 소개 / JPA 시작|완료|

@caffeine-library/readers-pro-spring-5

**Comment by emiling** [comment]
@JasonYoo1995 

저도 이 책 집에 있는데 사두고 안 읽고 있는데요 ㅎ...
괜찮으시면 주마다 한 챕터씩 번갈아 읽으면서 다른 분들께 공유하실래요?

**Comment by JasonYoo1995** [comment]
저는 좋습니다!

**Comment by emiling** [comment]
@JasonYoo1995 긍정적인 검토 감사합니다 :)

- 분량은 주 2챕터씩 괜찮으신가요? (혹시 부족하면 더 추가하셔도 좋습니다)
  - 혹은 1장은 인트로니 패스하고 2장부터 시작해도 괜찮을 듯 싶습니당
- 혹시 하고 하고 싶은 챕터 있으시면 코멘트로 남겨주세요 :) (없으시면 제가 1장 가져가겠습니다 😎)
- 혹시 더 참여하고 싶은 분들도 같이 코멘트 남겨주시면 좋을 듯 합니다 😃 (@binchoo @wooyounggggg )

**Comment by JasonYoo1995** [comment]
저는 이미 1장과 2장 준비를 다 해놨는데
제가 1, 2장을 해도 될까요?ㅎㅎ
1장 읽어보니까 JPA를 왜 쓰며
어떤 중요한 특징이 있는지 다루고 있어서
생각보다 할 얘기가 꽤 있네요~

**Comment by emiling** [comment]
@JasonYoo1995 

오호 알겠습니다 
저는 두 챕터 읽기는 시간상 촉박하니 일단 3장만 읽어갈게용

**Comment by binchoo** [comment]
@JasonYoo1995 @emiling 
JPA2로 서브 주제 진행해 주셔서 감사합니다
저는 이 기술에 관심이 있으니 추후 참여도 긍적적으로 생각중입니다
오늘 책 내용 맛본 후 확답하겠습니다~

**Comment by JasonYoo1995** [comment]
**1장 요약**
https://bird-yarn-6ac.notion.site/1-JPA-e8b28b7e08a3429287bef4a3d6679af6

**2장 요약**
https://bird-yarn-6ac.notion.site/2-JPA-e535f0d3f50c411f90d5822345972664

**Comment by JasonYoo1995** [comment]
Random 레포로 이동
[#2](https://github.com/caffeine-library/random/issues/2)
