### ISSUE TITLE
[keyword] 8장 스프링에서 JPA2로 데이터 액세스하기 (2)

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/pro-spring-5#64]
## 주제
8장 스프링에서 JPA2로 데이터 액세스하기 (2)를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요.

## 연관챕터
#63

**Comment by JasonYoo1995** [comment]
# 8.7 JpaRepository 사용하기
- JpaRepository는 CrudRepository를 상속 받고, 추가적인 메서드를 더 제공
# 8.8 스프링 데이터 JPA로 커스텀 쿼리 사용하기
### `@Query`
- JpaRepository를 상속 받은 인터페이스의 메서드 시그니처 위에
- `@Query` 애너테이션을 붙임으로써 커스텀 쿼리 사용 가능

**Comment by binchoo** [comment]
## Hibernate Envers Auditing 이력 테이블 예시

https://github.com/caffeine-library/pro-spring-5/issues/64#issuecomment-939415148 주제가 직관적으로 와닿지 않아
실제 이력 테이블 모습을 살펴본 것입니다.

### 시나리오 1
```
1. 김이름 추가
2. 이이름 추가
3. 박이름 추가
4. 김이름->김삼름 변경
5. 이이름->이삼름 변경
6. 박이름->박삼름 변경
```
위 시나리오를 수행하면 `SINGER_AUDIT` 테이블은 그림 처럼 됩니다.
![image](https://user-images.githubusercontent.com/15683098/137574006-d9c3f791-06e4-4b84-911d-cdd99dbc1d4d.png)


이제 엔버스의 감사 전략에 따른 `SINGER_AUDIT_H` (이력 테이블) 모습을 살펴 봅니다.

### 기본 감사 전략  
![image](https://user-images.githubusercontent.com/15683098/137574025-c18a0c80-a929-49de-b8cc-ac613aa5d7a3.png)
붉게 가린 곳은 기본 감사 전략에선 쓰지 않는 리던던트한 칼럼입니다.
시나리오는 한 번에 한 row씩 자료를 삽입하였고, 감사 테이블은 각 조작에 `AUDIT_REVSION` 값을 증가시켜 기록해 주었습니다.

### Validity 감사 전략  
![image](https://user-images.githubusercontent.com/15683098/137574036-6dc2b4ee-e536-4bad-ad49-475e8983287d.png)
`AUDIT_REVISION` 뿐만 아니라 `AUDIT_REVISION_END` 값도 기록됩니다.
`AUDIT_REVISION_END` 값이 null이 아니라면 해당 엔터티는 해당 조작에 의해 무효가 되었음을 나타냅니다.

4번 조작에서 '김이름'이 '김삼름'이 되었으므로 김이름은 1~3 버전동안 유효하고 4버전부터 무효입니다.

### 핵심 개념
- `AUDIT_REVISION`은 글로벌로 관리되는 값이다
- 이력 테이블의 한 row가 갖는 의미
  -  해당 엔터티가 `AUDIT_REVISION` ~ AUDIT_REVISION_END - 1` 버전동안 유효한 엔터티였다.
