### ISSUE TITLE
[question] 2 phase commit 동작 방식

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/pro-spring-5#69]
## 질문
2 phase commit 동작 방식

## 상세 내용
책 9.1.1에서, 글로벌 트랜잭션을 통해 여러 백엔드 리소스에 대한 트랜잭션을 일괄적으로 적용할 때
`2 phase commit 프로토콜`을 기반으로 모든 자원에 대해 `commit` 또는 `rollback`을 수행한다고 합니다.
2 phase commit 프로토콜이 어떻게 작동하는지, 원리를 조사해보면 깊은 이해에 도움이 될 것 같아 이슈를 발행합니다.

## 연관 챕터
#66

**Comment by emiling** [comment]
https://github.com/caffeine-library/pro-spring-5/issues/67#issuecomment-944987768  에서 설명 완료 되었습니다 😊
