### ISSUE TITLE
[question] Class.forName에서 사용되는 자바의 동적 로딩에 대해 구체적으로 알고 싶습니다

### ISSUE THREAD

**Issue by emiling** [caffeine-library/pro-spring-5#8]
## 질문
Class.forName에서 사용되는 자바의 동적 로딩

## 상세 내용

Class.forName 메서드는 런타임 시점에 **해당 경로의 클래스를 동적으로 로드**합니다.
JVM에 의해 발생하는 클래스 동적로드와 [해당 코드](https://github.com/gilbutITbook/006987/blob/dd53d8cc299fdc6858aa86476aea53a1b501cec4/chapter02/hello-world/src/main/java/com/apress/prospring5/ch2/decoupled/MessageSupportFactory.java#L7)에서 왜 `static`으로 설정했어야 하는지 연관지어 생각해볼 필요가 있을 것 같습니다.

더 나아가 JDBC 드라이버를 사용할 때 

```java 
Class.forName("com.mysql.cj.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root", "password");
``` 
어떻게 DriverManager는 MySQL 드라이버가 있는지 알고 진행하는 것인지까지 생각해봅시다.

## 연관 챕터
#3 

## 참고
- 책 페이지 : [p.72 예제 2-10](https://github.com/gilbutITbook/006987/blob/dd53d8cc299fdc6858aa86476aea53a1b501cec4/chapter02/hello-world/src/main/java/com/apress/prospring5/ch2/decoupled/MessageSupportFactory.java#L18) 

cc. @caffeine-library/readers-pro-spring-5

**Comment by emiling** [comment]
## 기본 지식 
(수정중...)

### Class Loader
JVM은 간략히 표현하면 다음의 구조를 갖습니다.

![image (2)](https://user-images.githubusercontent.com/30731518/125183234-cdebab80-e24f-11eb-840a-f7a8595f4060.png)

이 중 살펴볼 것은 주황색 박스 친 Class Loader로 
자바는 동적으로 클래스를 읽기 때문에 이를 통해 **런타임 시에 모든 코드가 JVM에 링크 후 로딩 되도록 하는 것**을 가능하게 만듭니다.

즉, 이를 다시 말하면 JVM은 class 파일에 대한 어떠한 정보(상속여부, 메서드, 필드 등등)을 알고 있지 않다는 것이다.

### Class Loading Way

클래스를 로딩하는 방식은 로드타임 동적 로딩과 런타임 동적 로딩으로 나뉘어 집니다.

- 로드타임 동적 로딩(load-time dynamic loading)
  - 클래스를 로딩하는 과정에서 다시 필요한 클래스를 로딩한다.
  - ex. HelloWorld 클래스 내에 System.out.println이 있다면 java.lang.System 클래스를 로딩한다.

- 런타임 동적 로딩(run-time dynamic loading)
  - 클래스를 로딩이 끝난 뒤, 클래스 내 코드를 실행하는 과정에서 필요한 클래스를 로딩한다.
  - ex. Class.forName()을 사용

**Comment by emiling** [comment]
JDK 1.6 에서부터는 Class.forName을 안 써도 서비스 로더에 의해 대체된다고 합니다.
이것과 연관지어 다음 시간에 얘기해보면 좋을 것 같습니다.

**Comment by JasonYoo1995** [comment]
# 자바 리플렉션

## 정적 언어 vs 동적 언어

### 정적 언어
컴파일 시점에 타입을 결정
ex) Java, C, C++ 등
### 동적 언어
런타임 시점에 타입을 결정
ex) Javascript, Python, Ruby 등

→ Java와 같은 **정적 언어**는 런타임 중에 타입을 결정시키는 코딩 방식에 한계가 있었다
→ 이러한 한계를 **리플렉션**이 해결

## 리플렉션
### 리플렉션의 정의
클래스 이름을 통해 클래스의 정보를 분석해내는 프로그래밍 기법

### 리플렉션의 원리
- 컴파일 시 자바 클래스 파일의 바이트 코드가 Static 영역에 위치
- 클래스 이름만 알고 있다면, 언제든지 이 Static 영역을 뒤져서 클래스에 대한 정보를 가져올 수 있음
- 이때, 이미 로딩이 완료된 클래스를 가지고, 또 다른 클래스를 동적으로 로딩(Dynamic Loading)할 수 있음
- 그러니까, 컴파일 시점(Compile Time)이 아니라 실행 시점(Run Time)에 동적으로 특정 클래스의 정보를 객체화를 통해 분석 및 추출해낼 수 있는 프로그래밍 기법이라고 표현할 수 있음

### 리플렉션의 사용 방법
별도의 외부 라이브러리 필요 없이
자바에서 기본적으로 제공하는 java.lang.reflect를 import하기만 하면 사용 가능하다.
이 패키지는 Constructor, Field, Method, Parameter, Modifier 등의 클래스를 제공합니다.
[참고](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/package-summary.html)

**클래스 선언**
```java
interface MyInterface {};

class MySuperClass {};

class MyClass extends MySuperClass implements MyInterface {
    String myField = "My Field";

    public MyClass() {
        System.out.println("Basic Constructor Invoked");
    }

    public MyClass(int constructorArg0, int constructorArg1) {
        System.out.println("constructorArg0 = " + constructorArg0);
        System.out.println("constructorArg1 = " + constructorArg1);
    }

    public int myMethod(int methodArg0, int methodArg1) {
        System.out.println(methodArg0 + " + " + methodArg1);
        return methodArg0 + methodArg1;
    }
};
```

**클래스 정보를 담고 있는 클래스 객체 추출**
```java
Class reflectClass = MyClass.class;
```
또는
```java
Class reflectClass = Class.forName("com.company.MyClass");
```
또는
```java
MyClass myClass = new MyClass();
Class reflectClass = myClass.getClass();
```
(Wrapper 타입의 경우 `Class reflectClass = Integer.TYPE;` 도 가능)

**클래스 정보(메서드, 필드, 생성자, 인터페이스, 부모 클래스 등) 얻기**
```java
Class reflectClass = MyClass.class;

Field[] reflectField = reflectClass.getDeclaredFields();
Method[] reflectMethod = reflectClass.getMethods();
Constructor[] reflectConstructor = reflectClass.getConstructors();
Class[] reflectInterface = reflectClass.getInterfaces();
Class reflectSuperClass = reflectClass.getSuperclass();
```

**메서드 호출**
```java
Class reflectClass = MyClass.class;

// 2개의 int를 매개변수로 갖는 myMethod라는 이름의 메서드 얻기
String methodName = "myMethod";
Class parameterType[] = new Class[2];
parameterType[0] = Integer.TYPE;
parameterType[1] = Integer.TYPE;
Method reflectMethod = reflectClass.getMethod(methodName, parameterType);

// 메서드 호출
Object reflectObject = reflectClass.newInstance();
Object argList[] = new Object[2];
argList[0] = 10;
argList[1] = 20;
Object returnObject = reflectMethod.invoke(reflectObject, argList);

// 호출 결과 출력
Integer returnValue = (Integer) returnObject;
System.out.println(returnValue.intValue());
```

**객체 생성**
```java
Class reflectClass = MyClass.class;

// 2개의 int를 매개변수로 갖는 생성자 얻기
Class parameterType[] = new Class[2];
parameterType[0] = Integer.TYPE;
parameterType[1] = Integer.TYPE;
Constructor reflectConstructor = reflectClass.getConstructor(parameterType);

// 생성자 호출 및 객체 생성
Object argList[] = new Object[2];
argList[0] = 30;
argList[1] = 40;
Object returnObject = reflectConstructor.newInstance(argList);

// 생성된 객체의 필드 출력
System.out.println( ((MyClass) returnObject).myField );
```
**필드값 변경**
```java
Class reflectClass = MyClass.class;

// 필드 얻기
String fieldName = "myField";
Field reflectField = reflectClass.getDeclaredField(fieldName);

// 변경 전
MyClass myClass = new MyClass();
System.out.println(myClass.myField);

// 변경 후
reflectField.set(myClass, "My New Field");
System.out.println(myClass.myField);
```

**Static 멤버 사용**
인자에 null을 넣는 것 외에는 위의 방법과 동일

### 리플렉션의 장단점
**장점**
- Runtime 시점에서 사용할 Instance를 선택하고 동작시킬 수 있는 **유연성**을 제공한다.
- 특정 객체를 감싸 추가적인 기능을 제공할 수 있다 ex) JDK Dynamic Proxy
  - 참고) JDK Proxy는 Reflection을 사용하지만, CGLIB Proxy는 Enhancer를 사용 [참고](https://huisam.tistory.com/entry/springAOP)

**단점**
- Compile time에 Type, Exception 등의 검증을 진행할 수 없다. (Runtime에 가져오기 때문)
- Runtime에서 Instance가 선택되기 때문에 해당 로직의 구체적인 동작 흐름을 파악하는 것에 대해 어려움을 가지게 된다.
- Private 접근 제어자로 캡슐화된 필드, 메서드에 대해 접근 가능하기 때문에 기존 동작을 무시하고 깨트리는 행위가 가능해진다. (Singleton 객체, Internal API 사용 등)
- Java 보안 관리자에게 Runtime 때 특정 권한을 지정받게 되는데, 이는 Linux의 Root 계정처럼 보안 취약점을 만들고, 제약 사항을 위반할 수 있다.

### 리플렉션의 성능
- 리플렉션은 성능이 느리고 높은 비용을 사용한다.
- 그 이유는 Reflection API의 Method Invoke() 실행 시간을 측정하는 많은 테스트들이 존재하고,
- 동적으로 Class를 Load하고, Heap에 객체를 띄우는 절차가 존재하기 때문이다.
- 또한, 리플랙션은 초기 호출 시 JVM이 해당 정보를 미리 최적화할 수 없다.
   (JIT Compiler의 Bytecode Caching, Opcode Optimization 등을 통한 성능 향상)
- 하지만 초기 호출 이후로는 캐싱을 통해서 Reflection API를 통한 메서드 호출도 최적화된다.
- 즉, 초기 호출에서는 5배 이상의 차이를 보이더라도, 이후 호출부터는 그러한 간격이 줄어들게 된다.
- 다만, setAccessible과 같은 Class 정보 설정 기능을 사용하는 경우에는 성능이 느려진다.

### 리플렉션은 언제 사용하는가?
- 리플렉션 없이는 요구사항대로 구현할 수 없는 경우
  - 불가피하게 리플렉션을 사용한다.
- 리플렉션 없이도 요구사항대로 구현할 수 있는 경우
  - 리플렉션을 쓰는 것이 더 유리한 경우에만 리플렉션을 사용한다
  - 고려해야 할 Trade Off에는 **유연한 코드 / 코딩 용이성 / 유지 보수 / 성능 / 안정성** 등이 있다.

### 리플렉션 사용 시 주의 사항
  - OOP 원칙을 벗어나는 코딩은 최소한으로 줄이기
    - private 필드를 접근할 수 있게 되어 OOP 원칙을 벗어나기 쉽기 때문
  - 리플렉션이 불필요한 부분까지 리플렉션으로 구현하면 성능이 좋지 않다. 
    - 그러나 적절히 사용한 Reflection은 오히려 성능을 향상시킬 수 있으며, 또한 많은 이득을 제공한다
  - 리플렉션을 사용하면 가독성이 떨어져 디버깅이 어려워진다.
    - 리플렉션은 컴파일 시 타입 체킹을 할 수 없으므로, 런타임시 잘못된 파라미터로 인해 런타임 에러가 발생하기 쉽다.
    - 하지만, 적절히 사용된 런타임 에러 메시지를 이용해 충분히 디버깅이 쉬운 환경으로 만들 수 있다.
    - 클래스의 타입을 비교하여 객체를 생성하는 경우, 대량의 if/else문을 사용하는 것보다 리플렉션을 이용하는 것이 오히려 코드가 단순하다.

### 리플렉션 사용 예시 (Use Case)
1
AOP Reflection
- Bean을 Wrapping 하는 Proxy Bean을 런타임 시점에 동적으로 생성
- Reflection을 통해 횡단 관심사(Cross-cutting Concern) 코드를 하드 코딩하지 않아도 됨
- 따라서, 애플리케이션 전반에 걸친 행동을 한 곳에서 관리하여, 코드의 양을 줄일 수 있음

2
- 외부에 공개되지 않는 private 멤버도 접근과 조작이 가능하므로 주의해야 합니다.
- private 멤버는 Field.setAccessible() 메서드를 true로 지정하면 접근이 가능합니다.

3
 - Late binding
 - Security (introspect code for security reasons)
 - Code analysis
 - Dynamic typing (duck typing is not possible without reflection)
 - Metaprogramming
 - Developed plugin system based on reflection
 - Used aspect-oriented programming model
 - Performed static code analysis
 - Used various Dependency Injection frameworks

4
- 리플렉션은 애플리케이션 개발에서보다는 프레임워크/라이브러리에서 많이 사용됩니다.
- 프레임워크/라이브러리는 사용하는 사람이 어떤 클래스를 만들지 모릅니다.
- 대표적인 사용 예로는 스프링의 DI, Proxy, ModelMapper 등이 있습니다.

5
IntelliJ의 자동완성

6
- 자바 가상머신이 동작을 시작하고, 코드가 실행되기 전까지는 어떠한 JDBC의 드라이버가 사용될 지 알 수 없습니다.
- JAVA에서 DB를 연동할때 다음과 같은 코드가 존재합니다.

```java
Class.forName("oracle.jdbc.driver.OracleDriver");
```

위 코드를 사용하여 런타임(Runtime) 시에 동적으로 클래스(OracleDriver)를 로딩하게 합니다.

7
- Jackson, GSON 등의 JSON Serialization Library
- Log4 j2, Logback 등의 Logging Framework
- Apache Commons BeanUtils 등의 Class Verification API
- Spring의 @Autowired와 같은 DL, DI 기능 (processInject(), inject())
  (내부적으로 Spring의 ReflectionUtils라는 Abstraction Library를 사용한다)
- JUnit, Hamcrest와 같은 Test Framework

8
JUnit4에서 @Test 애너테이션이 붙은 메서드들을 실행하는 경우

**Comment by JasonYoo1995** [comment]
Q. 왜 Spring DI는 컴파일 타임에 수행하지 않고, 굳이 로드 타임에 reflection을 할까요?

컴파일 타임에도 DI를 수행하는 것은 가능한데도 말이에요.

주어진 인터페이스에 여러 구현체가 동적으로 교체될 가능성을 열어두기 위해서 일까요?
하지만 이것 역시 리플렉션이 아니어도 가능할텐데 말이에요.

https://prc2.fontysvenlo.org/pdf/042_reflection_dependecy_injection_sheets_en.pdf (DI에 대한 좀 더 깊은 설명)
https://stackoverflow.com/questions/57201129/how-do-i-use-reflection-to-configure-all-implementations-of-interface-for-di-as (리플렉션을 사용하는 이유는 Generic 타입이기 때문)

DI 메커니즘 자체가 모든 타입의 객체를 지원하도록 열어놓았기 때문에
리플렉션만으로 가능한 것일까요?

https://sowhat4.tistory.com/59 (DI 과정 중 reflection이 사용 되는 정확한 시점)

https://better-dev.netlify.app/java/2020/08/15/thejava_7/ (컴파일 시점에 주입되지 않는 증거)
의존 객체에 협력 객체를 주입하는 코드를 작성하지 않은 상태로 컴파일하면
의존 객체는 NULL인 상태에서 프로그램이 시작되고
따라서 컴파일 시점에는 도저히 협력 객체의 주입이 이루어질 수 없음

Q. reflection은 런타임에 일어나는 것일까요, 로드 타임에 일어나는 것일까요? 로드 타임은 정확히 무엇인가요?

https://nhj12311.tistory.com/466

**Comment by JasonYoo1995** [comment]
오늘 발표 예정
