### ISSUE TITLE
[keyword] 12장 스프링 리모팅 사용하기 키워드 정리

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/pro-spring-5#81]
## 주제
**12장 스프링 리모팅 사용하기**를 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요.

## 연관챕터
#80

@caffeine-library/readers-pro-spring-5

**Comment by JasonYoo1995** [comment]
# 12.4 스프링에서 JMS 사용하기
## MQ 서버
 - 애플리케이션들을 서로 연동하는 데 비동기적으로 느슨한 결합 방식 제공
 - 메시지를 큐, 토픽에 저장
## 토픽
 - 발행-구독(publish-subscribe), 생산자-소비자(producer-consumer) 모델 지원
 - 다수의 client가 토픽 내의 메시지 구독 가능
## JMS 리스너 (=consumer)
<img src="https://user-images.githubusercontent.com/66045861/141666132-ed12ea96-534a-40a3-b9c5-d90915d8a881.png" width="500" />

## JMS Template (=producer)
<img src="https://user-images.githubusercontent.com/66045861/141666162-959963c0-a4fe-47ec-86f6-830ea291620c.png" width="500" />

 - setDeliveryDelay() : 배치로 전송하기 전 버퍼링 시간 설정
## 송수신 테스트
<img src="https://user-images.githubusercontent.com/66045861/141667196-d4c6c72a-8a38-4cbb-862f-0cbafc43e017.png" width="500" />

## 참고 : JMS / AMQP와 관련된 주제인 카프카에 대한 책 요약

**Comment by binchoo** [comment]
# SOA
서비스는 비즈니스 요구사항이 잘 정의되고 잘 분화된 독립적인 컴포넌트입니다.
그러므로 재사용과 컴포지션에 유용합니다.

큰 서비스는 작은 서비스를 조합하여 사용합니다.

![image](https://user-images.githubusercontent.com/15683098/141666752-0fdc071e-8952-4e3a-8aef-33c4a87c5f63.png)

클라이언트는 서비스 디렉토리를 조회하여 적합한 서비스를 찾아 호출할 수 있습니다.

## Remote Procedure Call

클라이언트의 코드는 마치 함수를 호출하는 것처럼 원격지 서비스를 호출합니다.
이를 위해 원격지 서비스에 대한 메타 정보를 활용하여 RPC 지원 라이브러리가 추상화를 제공해야 합니다.

### SOAP

![image](https://user-images.githubusercontent.com/15683098/141667078-8a2bd951-cd0b-4602-bfb2-ae74dcee05e3.png)


XML 기반의 메타정보를 주고 받습니다. (WDSL, Envelop)
- 웹 서비스 제공자는 웹 서비스가 제공하는 기능의 이름, 요구 매개변수 등을 서술한 WSDL 파일을 제공함.
- SOAP 라이브러리가 WSDL 파일의 정보를 활용하여 인터페이스를 생성한다.
  클라이언트 코드가 이를 호출해서 원격 서비스를 제공받을 수 있음.
- 클라이언트가 작성한 HTTP 헤더에는 호출하는 기능의 이름과 매개변수 등이 적재되어 있음.

>  WSDL 파일 예제
  https://github.com/sensepost/wikto/blob/master/Web%20References/com.google.api/GoogleSearch.wsdl 

> 클라이언트 코드 예제  
![image](https://user-images.githubusercontent.com/15683098/141666996-f09c744f-425c-4494-acea-e1af923dbc42.png)

> 클라이언트 측 HTTP 헤더에 적재된 SOAP Envelop
![image](https://user-images.githubusercontent.com/15683098/141667006-ad8e9e7a-128e-497d-92a2-b56cae486033.png)

SOAP는 HTTP 프로토콜 위에 Envelop이라는 계층을 하나 더 얹은 구조입니다.
Envelop 내용은 원격 프로시저의 시그니쳐 정보에 의존하기 때문에 수시로 바뀌지만 
HTTP 패킷 구조는 변하지 않습니다. (요청 URL & HTTP Method는 POST로 일정함)

따라서 HTTP 요청의 단순함을 활용하지 못합니다.

### REST & RPC Hybrid
SOAP의 Envelop 대신에 HTTP 요청 URL에 호출하는 프로시저 시그니처를 담았습니다.
REST의 이론에 어긋나는 설계이며, 실서비스 곳곳에서 발견되는 API입니다.
![image](https://user-images.githubusercontent.com/15683098/141667228-0a238d6f-9cd7-4fd4-b3e0-2d4c106a63e5.png)


## ROA
RPC는 원격 프로시저의 시그니쳐를 메타 정보로 요구하는 반면에
리소스 기반 REST는 리소스의 URI에 집중합니다.
리소스는 URI를 통해 고유하게 식별되며 자원에 대한 연산(조회, 생성, 수정, 삭제 ..) 은 Envelop이 아닌
HTTP의 기본 메서드들을 이용합니다.

### ROA기반 REST
덕분에 RESTful 웹 서비스의 요청 포맷은 매우 단순해졌습니다. 
클라이언트와 서버는 리소스 객체를 직렬화한 JSON 또는 마샬링한 XML을 교환합니다.
![image](https://user-images.githubusercontent.com/15683098/141667086-26e7639f-5b7d-4300-8ac6-0f299126750c.png)

**Comment by binchoo** [comment]
## REST와 `@ResponseBody` 어노테이션

스프링MVC에서 컨트롤러의 메서드는 "논리적인 뷰"를 반환하는 것으로 상정한다.
하지만 `@ResponseBody`가 붙은 메서드의 반환 값은 뷰가 되는 것이 아니고, 즉시 HTTP 응답 스트림으로 사용된다.

따라서 REST 서비스를 작성할 때는, 
컨트롤러 메서드가 리소스를 반환하게끔 하고, `@ResponseBody` 붙여준다.
리소스는 디스패쳐 서블릿에 등록된 메시지 컨버터 빈을 거쳐 JSON 및 XML로 변환되고 HTTP 응답 스트림에 쓰인다.

```java
@Controller
@ResquestMapping(value="/singer")
public class SingerController {
  final Logger logger = LoggerFactory.getLogger(SingerController.class);
  @Autowired private SingerService singerService;

  @ResponseStatus(HttpStatus.OK)
  public Singers listData() {
     return new Singers(singerService.findAll());
  }
}
```

### 스프링 4.0부터는 `@RestController`
`@RestController` 이 클래스 수준 어노테이션을 사용하면,
`@RequestMapping`이 붙은 메서드에 자동으로 `@ResponseBody`가 적용된다.
`@GetMapping`, `@PostMapping` 등은 `@RequestMapping`을 래핑한 버전이므로 역시 적용된다.

**Comment by binchoo** [comment]
RestTemplate을 사용하는 서비스 레이어 구조 및 구현

# 요약

서비스가 비즈니스 객체를 다른 곳에서 획득해 오는 경우가 있다. 그 출처는 DB가 될 수도 있고, 다른 웹 서비스가 되기도 한다. DB와 퍼시스턴스 레이어를 거쳐 객체를 뽑아오든, 웹 API를 호출하여 객체를 얻어오든 두 방식을 구현하는 코드 패턴은 스프링에서 거의 유사하다.

두 방식 모두 3티어 아키텍쳐로 책임이 나뉘어진다. 또 티어 객체 간 매핑이 공통적으로 요구되는 사항이다.

# 3티어 아키텍처 비교

## DB에서 객체를 얻을 때

![서비스는 레포지토리 레이어를 통해 DB 데이터에 접근한다. 레포지토리 단은 JPA 구현체 Hibernate 기술 등을 채용하여 ORM(객체-관계형 매핑)을 제공한다. ResultSet에 담긴 관계형 데이터를 자바 엔터티 객체로 변경하는 것은 중요한 요구사항이다.](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/3ac18197-330c-42ae-8df1-ddb5168980ab/Untitled.png)

서비스는 레포지토리 레이어를 통해 DB 데이터에 접근한다. 레포지토리 단은 JPA 구현체 Hibernate 기술 등을 채용하여 ORM(객체-관계형 매핑)을 제공한다. ResultSet에 담긴 관계형 데이터를 자바 엔터티 객체로 변경하는 것은 중요한 요구사항이다.

## 웹 서비스 호출로 객체를 얻을 때

![가장 익숙하고 유명한 리모팅 프로토콜인 HTTP(S)를 사용하여 웹 서비스 API가 제공되었다고 가정하자. 서비스 단은 다시 웹 클라이언트에게 부탁하여 원격지 서비스의 API를 호출토록 한다. 그 결과로 돌아오는 HTTP(S) 응답 패킷의 Body에는 JSON 혹은 XML 포맷을 갖는 객체가 담겨있다. 따라서 JSON, XML 혹은 형식 없는 스트링을 자바 엔터티 객체로 변경하는 것은 중대한 요구사항이다. ](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/e6d35914-e865-48fb-abe4-c1bfc81f3ac9/Untitled.png)

가장 익숙하고 유명한 리모팅 프로토콜인 HTTP(S)를 사용하여 웹 서비스 API가 제공되었다고 가정하자. 서비스 단은 다시 웹 클라이언트에게 부탁하여 원격지 서비스의 API를 호출토록 한다. 그 결과로 돌아오는 HTTP(S) 응답 패킷의 Body에는 JSON 혹은 XML 포맷을 갖는 객체가 담겨있다. 따라서 JSON, XML 혹은 형식 없는 스트링을 자바 엔터티 객체로 변경하는 것은 중대한 요구사항이다. 

# REST 클라이언트의 요구사항

- 서비스는 클라이언트 레이어를 거쳐 비즈니스 엔터티를 획득한다.
    - 엔터티의 출처는 웹 서비스가 제공한 API이다. 서비스는 엔터티를 DB에서 읽거나, 웹 서비스 API로 가져오거나 어찌됐건 관심 사항이 아니다.
- 클라이언트는 웹 API가 스펙이 요구하는대로 HTTP 요청을 작성하고 이를 타겟 서비스에 전송해야 한다.  요청 완료 후 타겟 서비스로부터 HTTP 응답을 받아야한다.
    - HTTP 요청 패킷에 대응하여 추상화된 객체가 **요청 엔터티**이다.
    - HTTP 응답 패킷에 대응하여 추상화된 객체는 **응답 엔터티**이다.

## 엔터티 식별하기

### 비즈니스 엔터티

비즈니스에 중요한 정보와 로직을 캡슐화한 객체

```java
@ToString
@EqualsAndHashCode
@Setter
@Getter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class Movie {

    Long id;

    String title;

    String titleEng;

    @JsonFormat(pattern = "yyyy-MM-dd")
    DateTime date;

    Float userRating;

    Float audienceRating;

    Float reviewerRating;

    Float reservationRate;

    Long reservationGrade;

    Long grade;

    String thumb;

    String image;

    String photos;

    String videos;

    String outlinks;

    String genre;

    Long duration;

    Long audience;

    String synopsis;

    String director;

    String actor;

    Long like;

    Long dislike;
}
```

### HTTP 엔터티

- **HttpEntity**
    
    HttpHeaders + 비즈니스 엔터티(HTTP Body가 됨)
    
    HTTP 요청 패킷과 HTTP 응답 패킷의 추상화.
    
- **RequestEntity** extends **HttpEntity**
    
    HTTP Method + HttpHeaders + 비즈니스 엔터티(HTTP Body)
    
    요청 메서드도 함께 캡슐화 함. 
    
    스태틱 메서드들은 빌더 패턴으로 쉽게 HTTP 헤더 및 바디를 작성하는 편의 기능 제공.
    
    RestTemplate API 중 `exchange`의 인자로 사용 가능.
    
    ```java
    RequestEntity requestEntity = RequestEntity.post(URI.create(URL_READ_MOVIE_LIST))
                    .header(HttpHeaders.COOKIE, "PHPSESSIONID=123456", "token=8855")
                    .header(HttpHeaders.AUTHORIZATION, "Basic YWxhZGRpbjpvcGVuc2VzYW1l")
                    .body(new Movie());
    restTemplate.exchange(requestEntity, Movie.class);
    ```
    
- **ResponseEntity** extends **HttpEntity**
    
    HTTP Status Code + HttpHeaders + 비즈니스 엔터티(HTTP Body)
    
    응답 상태 코드도 함께 캡슐화 함.
    
    스태틱 메서드들은 빌더 패턴으로 각 응답 코드에 대응하는 HTTP 헤더 및 바디를 작성하도록 편의 기능 제공.
    

## HTTP 요청하고 응답하기

[[spring-web] RestTemplate API](https://www.notion.so/8f007273ebba49608f8e7e490aa71d80)

### 요청 엔터티 작성 & 전송 & 응답 엔터티 수신 & 비즈니스 객체로 매핑

헬퍼 클래스들의 도움으로 HTTP 요청 패킷은 직관적으로 작성 가능하다.

RestTemplate API를 사용하면 요청 패킷 전송 & 응답 수신 & 비즈니스 객체 매핑이 진행된다. 

- getForObject 예시
    
    ```java
    RequestEntity requestEntity = RequestEntity.post(URI.create(URL_READ_MOVIE_LIST))
                    .header(HttpHeaders.COOKIE, "PHPSESSIONID=123456", "token=8855")
                    .header(HttpHeaders.AUTHORIZATION, "Basic YWxhZGRpbjpvcGVuc2VzYW1l")
                    .body(new Movie());
    restTemplate.exchange(requestEntity, Movie.class);
    ```
    
- getForObject + 요청 파라미터 예시
    
    ```java
    @Override
    public List<Movie> readMovie(Long id, String name) {
        UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromHttpUrl(URL_READ_MOVIE);
        Optional.ofNullable(id).ifPresent(it-> uriBuilder.queryParam("id", it));
        Optional.ofNullable(name).ifPresent(it-> uriBuilder.queryParam("name", name));
    
        String url = uriBuilder.build().toUriString(); // build string without encoding
        MovieResponse response = restTemplate.getForObject(url, MovieResponse.class); // because restTemplate will encodes the url
        return Optional.of(response.getResult())
                .orElseThrow(InternalError::new);
    }
    ```
    

### UriComponentsBuilder로 요청 파라미터 삽입 시 주의사항

`UriComponentsBuilder` 는 `RestTemplate` 과 같이 사용할 때 인코딩에 주의가 필요하다.

restTemplate의 API는 String URL를 받거나 URI 받고 있다. 

문자열 URL을 전달하게 되면, restTemplate의 내부에서 UTF-8로 인코딩을 해 주므로, `UriComponentsBuilder` 로 URL 생성 시 인코딩 적용이 필요하지 않다.

인코딩이 2번 적용되면 한글 표현 등 문제가 생기니 유의.

```java
String url = uriBuilder.toUriString(); // bad - 인코딩 진행함
String url = uriBuilder.build().encode().toUriString(); // bad - 인코딩 진행함
String url = uriBuilder.build().toUriString(); // good - 인코딩 진행 안 함
```

## 엔터티 간 매핑하기

HTTP 패킷은 문자열이다. 

고로 자바 객체 - 문자열 포맷간 직렬화/역직렬화가 꼭 필요하지만, 엔터티 마다 이런 로직을 구현하기는 매우 까다롭다. 다행히도 `RestTemplate`에겐 `MessageConverter`가 존재하여 그런 역할을 수행해 주고 있다.

- **비즈니스 엔터티** ➡️ **요청 엔터티**
    
    비즈니스 엔터티 `Movie` 객체는 HTTP 요청의 바디에 들어갈 때 적절한 문자열 형태가 되어야 한다. RestTemplate을 사용하는 개발자는 직렬화 로직을 작성하지 않고 RestTemplate의 MessageConverter에게 맡기면 된다.
    
    ```java
    RequestEntity requestEntity = RequestEntity.post(URI.create(URL_READ_MOVIE_LIST))
                    .header(HttpHeaders.COOKIE, "PHPSESSIONID=123456", "token=8855")
                    .header(HttpHeaders.AUTHORIZATION, "Basic YWxhZGRpbjpvcGVuc2VzYW1l")
                    .body(new Movie());
    ```
    
- **응답 엔터티** ➡️ **비즈니스 엔터티**
    
    HTTP 응답의 바디에서 문자열로 표현된 객체는 비즈니스 객체 `MovieResponse`로 매핑이 되어야 한다. RestTemplate을 사용하는 개발자는 역직렬화 로직을 작성하지 않고 RestTemplate의 MessageConverter에게 맡기면 된다.
    
    ```java
    @Override
    public List<Movie> readMovie(Long id, String name) {
        UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromHttpUrl(URL_READ_MOVIE);
        if (id != null)
            uriBuilder.queryParam("id", id);
        if (name != null)
            uriBuilder.queryParam("name", name);
        MovieResponse response = restTemplate.getForObject(uriBuilder.toUriString(), MovieResponse.class);
        return Optional.of(response.getResult())
                .orElseThrow(InternalError::new);
    }
    ```
    

### [jaskson-databind] Object Mapper 구성 예시

- **자바 객체 - JSON 간 매핑**
    
     `MappingJackson2HttpMessageConverter` 빈을 구성하고 `ObjectMapper` 빈을 주입하여 사용하는 것이 다수이다.
    
    ```java
    @ComponentScan(basePackages = "org.binchoo.study.spring.resttemplate.movieservice")
    @Configuration
    public class ClientConfig {
    
        @Bean
        public RestTemplate restTemplate() {
            RestTemplate restTemplate = new RestTemplate();
            restTemplate.setMessageConverters(Arrays.asList(messageConverter()));
            return restTemplate;
        }
    
        @Bean
        public MappingJackson2HttpMessageConverter messageConverter() {
            MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
            converter.setObjectMapper(objectMapper());
            return converter;
        }
    
        @Bean
        public ObjectMapper objectMapper() {
            ObjectMapper objectMapper = new ObjectMapper();
            objectMapper.registerModule(jodaModule());
            return objectMapper;
        }
    
        @Bean
        public JodaModule jodaModule() {
            return new JodaModule();
        }
    }
    ```
    
- **자바 객체 - XML 간 매핑**
    
    pro spring 5 예제에서는 자바 객체와 XML간 매핑도 다루고 있다.
    
    이 경우 `MarshallingHttpMessageConverter`빈을 구성하고 마샬/언마샬러로 Castor XML 라이브러리를 사용할 수 있다.
    

### [jaskson-databind] 참고할 어노테이션

```java
@JsonNaming(PropertyNamingStrategy.SankeCaseStrategy.class)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonProperty("name")
@JsonFormat("yyyy-MM-dd")
```

### [jaskon-datatype-joda] 간편하게 JodaTime 매핑 설정하기

```java
@Bean
public ObjectMapper objectMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.registerModule(jodaModule());
    return objectMapper;
}

@Bean
public JodaModule jodaModule() {
    return new JodaModule();
}

---
@ToString
@EqualsAndHashCode
@Setter
@Getter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class Movie {
    Long id;
    @JsonFormat(pattern = "yyyy-MM-dd")
    DateTime date; //joda의 DateTime
    ...
}
```

# 디버깅

## Fiddler4 프록시

### 기본 설정

### HTTPS 캡쳐 설정

### JVM 發 요청이 프록시를 거쳐가도록 설정

```java
---proxy-config.properties 파일---
http.proxyHost=127.0.0.1
https.proxyHost=127.0.0.1
http.proxyPort=8888
https.proxyPort=8888
javax.net.ssl.trustStore=C:\\Users\\wnwoq\\.jdks\\azul-1.8.0_275\\bin\\FiddlerKeystore
javax.net.ssl.trustStorePassword=password

---ProxyEnabler.java---
@Profile("proxy")
@Component
public class ProxyEnabler {

    @PostConstruct
    void enableProxy() {
        Properties props = new Properties();
        try {
            props.load(new ClassPathResource("proxy-config.properties").getInputStream());
            System.setProperties(props);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by binchoo** [comment]
# 디버깅
![image](https://user-images.githubusercontent.com/15683098/145709988-c56cbaa5-7403-4b57-8c21-0ad5afc1d1da.png)

## Fiddler4 프록시
단말에서 송수신하는 HTTP(S) 패킷을 조회하는 데스크톱 앱. 브라우저 개발자 모드의 네트워크 탭의 기능과 거의 흡사하다.
차이점은 해당 데스크탑을 프록시 서버로 만들 수 있다는 점. 

따라서 스마트폰에서 네트워크를 프록시 모드를 활성하고, 오고가는 HTTP(S) 패킷을 디버깅 하는 용도로 사용한다.
오고 가는 모든 패킷은 인터셉트하여 커스터마이징 하는 기능도 있다.

JVM 위의 앱이 주고 받는 패킷을 디버깅하는 용도로도 프록시 서버를 활용할 수 있다.

### 프록시 서버 열기 & HTTPS 캡쳐 설정
https://azureossd.github.io/2017/04/26/capture-java-vm-traffic-using-fiddler/

### [JVM 發 요청이 프록시를 거쳐가도록 설정](https://azureossd.github.io/2017/04/26/capture-java-vm-traffic-using-fiddler/)

1. 인증서와 키스토어를 생성해야 합니다.
  a. Fiddler4> Tools 메뉴> Options> HTTPS> Actions> Export Root Certificate to Desktop 클릭
  b. CMD 열기
  c. echo %JAVA_HOME%
  d. 자바 홈의 bin 폴더로 이동> keytool 명령어로 키스토어 생성 (1단계에서 만든 인증서 필요함)
  e. `keytool.exe -import -file C:\Users\\\Desktop\\FiddlerRoot.cer -keystore FiddlerKeystore -alias Fiddler`
  f. 키스토어 비밀번호 설정 후 인증서 신뢰 Y
  ![](https://azureossd.github.io/media/2017/04/fiddler-keystore.png)
2. HTTP(S) 요청이 프록시를 거치도록 JVM 실행 옵션을 줍니다.
  ```java
   -DproxySet=true 
   -DproxyHost=127.0.0.1 
   -DproxyPort=8888
   -Djavax.net.ssl.trustStore="path\to\java_home\bin\FiddlerKeyStore" 
   -Djavax.net.ssl.trustStorePassword="password_used_during_keystore_creation"
  ```
3. 혹은, `System.setProperty()` 를 사용하여 런타임 관련 설정을 진행합니다. 아래 코드는 프로퍼티 파일에 프록시 연결 설정을 담고서 자바 구성에서 관련 프로퍼티를 로드하는 모습입니다.
```java
---proxy-config.properties 파일---
http.proxyHost=127.0.0.1
https.proxyHost=127.0.0.1
http.proxyPort=8888
https.proxyPort=8888
javax.net.ssl.trustStore=C:\\Users\\wnwoq\\.jdks\\azul-1.8.0_275\\bin\\FiddlerKeystore
javax.net.ssl.trustStorePassword=password

---ProxyEnabler.java---
@Profile("proxy")
@Component
public class ProxyEnabler {

    @PostConstruct
    void enableProxy() {
        Properties props = new Properties();
        try {
            props.load(new ClassPathResource("proxy-config.properties").getInputStream());
            System.setProperties(props);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
4. JVM 발 요청이 피들러 프록시에 캡쳐되는 지 확인해 봅니다.
![image](https://user-images.githubusercontent.com/15683098/145710477-61328552-8e94-4d0c-b750-099dae4e30de.png)
