### ISSUE TITLE
[keyword] 16장 스프링 웹 애플리케이션 키워드 정리 (1)

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/pro-spring-5#91]
## 주제
16장 스프링 웹 애플리케이션을 읽고 중요✨ 하다고 생각하는 키워드와 선택한 이유에 대해서 코멘트로 달아주세요.

**Comment by JasonYoo1995** [comment]
## 1. MVC 소개

- 모델 : 상태
- 뷰 : 사용자에게 데이터 제공. 사용자와 상호 작용
- 컨트롤러 : 서비스 레이어와의 상호 작용. 모델 업데이트. 적절한 뷰로 이동시킴

![image](https://user-images.githubusercontent.com/66045861/144702590-ddedbdd8-4d0e-43d6-9361-947677bd53fd.png)

- 뷰를 응답
    1. 요청 : 사용자가 수행한 이벤트나 액션을 뷰가 받아들여, 디스패처로 전달
    2. 호출 : 적절한 컨트롤러로 요청 전달
    3. 서비스 호출 : 적절한 서비스에 전달 및 응답
    4. 모델 채움 : 서비스 응답을 토대로 모델 채움
    5. 뷰 생성 : 모델을 기반으로 뷰 생성
    6. 응답 : 컨트롤러가 사용자에게 뷰 응답
- 데이터만 응답
    1. 요청 : 뷰에서 Ajax 호출 → 디스패터가 컨트롤러에게 요청 전달 → 서비스 호출 및 응답
    2. 응답 : 뷰가 아닌 데이터만 전달. (기존 뷰의 부분적 업데이트)

## 3. 스프링 MVC WebApplicationContext 구조

<img src="https://user-images.githubusercontent.com/66045861/144702600-5e0a1777-bd40-45e5-966c-7c4f43743813.png" width="500" />

- DispatcherServlet은 여러 개
- 각 '서블릿 레벨 WebApplicationContext'는 각 'DispatcherServlet'과 매핑
- '서블릿 레벨 WebApplicationContext'들의 공통 사항은 '루트 WebApplicationContext'에서 처리

## 4. 스프링 MVC 요청 라이프사이클

<img src="https://user-images.githubusercontent.com/66045861/144702604-ee12b6cd-7e89-44ce-9d8e-efcdbcc43bca.png" width="500" />

## 5. 스프링 MVC 구성

- CharacterEncodingFilter, HiddenHttpMethodFilter
- https://github.com/JasonYoo1995/Microservice_Practice

![image](https://user-images.githubusercontent.com/66045861/144702608-4432772b-b606-40e1-87f1-102183fb6207.png)

**Comment by binchoo** [comment]
# MVC 설정
## 서블릿 이니셜라이저 (web.xml 대체)
![image](https://user-images.githubusercontent.com/15683098/144728782-d30c1f45-7e0a-4715-8e0f-3fa473a65a3e.png)

### getServletMappings()
DispatcherServlet이 처리할 요청 주소 패턴을 설정한다.
`return new String[]{"/"}` 는 모든 요청에 대한 처리를 의미함.

### 필터 설정
필터는 서블릿으로 들어오는 모든 요청뿐만 아니라, 나가는 응답에도 적용하는 로직이다.
![image](https://user-images.githubusercontent.com/15683098/144728838-4750eb16-ea3d-462c-a81d-825a7a05ddba.png)

#### 필터 CharacterEncodingFilter
요청의 문자열 인코딩을 설정한다. `forceEncoding=true`로 주면 응답 문자열의 인코딩도 지정한다.
![image](https://user-images.githubusercontent.com/15683098/144728969-81a8cbb9-694c-44bf-b072-b41aacd205b0.png)

#### 필터 HiddenHttpMethodFilter 
`<form>`, `<input>` 태그 사용 시 GET, POST 요청 메서드 이외는 원하지 않는 브라우저가 있다.
스프링은 이를 우회하여  PUT, PATCH, DELETE 메서드도 사용할 수 있도록 꼼수를 제공한다.

<input>` 태그 작성 시, `hidden` 타입 + `_method` 이름을 갖도록하면
스프링이 이를 인식하여 PUT, PATCH, DELETE용 컨트롤러를 호출할 수 있다.
```html
<input type="hidden" name="_method" value="put"/>
```

`HiddenHttpMethodFilter`를 추가하면 위 기능이 활성된다.

#### OpenEntityManagerInView 필터 (주의할 필터)

EntityManager는 트랜잭션 단위로 유지되므로 다음과 같은 문제를 경험할 수 있다.

- Spring Security: `DelegatingFilterProxy`로 시큐리티 필터 체인을 호출하여 유저 정보를 획득했을 때, 해당 트랜잭션이 종료된 상태에서 컨트롤러에 `@CurrentUser`로 유저 정보를 주입할 경우 유저 정보는 준영속화 상태라 획득할 수 없다.
  
  시큐리티 필터 체인은 다른 필터보다 우선하여 호출되고 있다. 중요한 점은 콘트롤러 보다 앞서 호출된다는 점이다.
  ![image](https://user-images.githubusercontent.com/15683098/144729274-d4188183-4c8f-4de7-a8b7-c3c735caae3f.png)
  따라서 언급된 이슈를 경험할 수 있다.
  Spring Boot는 옵션 `spring.jpa.open-in-view=true`로 지정하여 OSIV가 적용된 상태로 어플리케이션을 구성해 준다.

- 연관관계 엔터티 지연 로딩: 엔터티가 다른 엔터티와 `@OneToMany`, `@ManyToMany` 관계를 가질 때 개발자는 해당 어트리뷰트의 지연 로딩을 선호한다. 
Singer와 Album이 일대다 관계이고 singer.albums 어트리뷰트가 지연로딩 된다고 가정하자. 만약 트랜잭션 내에서 지연로딩을 끝마치지 못 했다면, 뷰에서 singer.albums를 이용할 때 문제가 생긴다. 
  ![image](https://user-images.githubusercontent.com/15683098/144729445-ac1c5a93-df1a-414d-9b81-d1fe68f2ac55.png)

영속성 컨텍스트는 트랜잭션 범위 밖에서 조회 기능만을 제공한다. 지연 로딩 기능도 조회기능이므로 동작을 보장한다. 
OSIV 패턴을 적용하면 뷰에서도 영속성 컨텍스트가 살아 있기 때문에 지연 로딩을 동작시킬 수 있다.
  ![image](https://user-images.githubusercontent.com/15683098/144729473-092ddde2-cde0-4af2-8991-e6d4768e5cf4.png)

**OSIV 패턴의 단점**
장시간 DB 커넥션 리소스를 사용한다. 실시간 및 대량 트래픽이 중요한 애플리케이션에서는 자원이 모자랄 수 있다. 이것은 결국 장애로 이어진다.

**OSIV 패턴의 대안**
- 지연 로딩을 트랜잭션 내에서 전부 처리하여 DTO에 연관 엔터티를 욱여 넣거나
- 뷰에서 ajax 등을 활용하여 REST 호출로 연관 관계의 엔터티만을 획득해 오는 패턴을 사용한다.

**Comment by binchoo** [comment]
## DispatcherServlet 설정
![image](https://user-images.githubusercontent.com/15683098/144733712-9a353474-f957-4e8e-82a3-2cdc449a3cae.png)

**Comment by binchoo** [comment]
### 스태틱 리소스 내려주기
여태껏 사용한 구성설정에서 
`addResourceHandler()`나 `configureDefaultServletHandling()` 부분을 주석처리 했을 때

스태틱 리소스 파일 요청이 어떻게 달라지는 지 확인해 봅니다.
얻고자 하는 파일은 프로젝트에서 /src/main/resources/styles/stadard.css 에 위치하던 파일입니다.

- 리소스 핸들러 X + Default Servlet X
  스태틱 파일을 요청할 수 없음.
  
- 리소스 핸들러 X + Default Servelet O
  - ROOT로 배포 시 
    `localhost:8080/styles/standard.css`
  - 일반 배포 시 
    `localhost:8080/서블릿명/styles/standard.css`

- 리소스 핸들러 O + Default Servelet *
  `localhost:8080/resources/styles/standard.css`
  리소스 핸들러를 사용하면,
